# aircraft_settings.py — DCS Switch Randomizer (DSR) Aircraft Settings Dialog

import sys, os, json, copy
from math import gcd
from functools import reduce
from fractions import Fraction

from PyQt5.QtWidgets import (
    QApplication, QDialog, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton, QFrame, QScrollArea, QSpinBox,
    QCheckBox, QSizePolicy, QMessageBox
)
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QFont, QColor, QPainter, QPixmap

# ── Palette ───────────────────────────────────────────────────────────────────
BG    = "#111111"
PANEL = "#222222"
TB    = "#111111"
HL    = "#9ae69b"
ACC   = "#9ae69b"
FG    = "#777777"
MUTED = "#666666"
WHITE = "#ffffff"
GREEN = "#9ae69b"
DARK  = "#111111"

TYPE_COLOR = {
    "discrete":   "#9ae69b",
    "continuous": "#c9be24",
    "run":        "#8c00ff",
    "select_one": "#9ae69b",
}
TYPE_LABEL = {
    "discrete":   "SWITCH",
    "continuous": "KNOB",
    "run":        "SPECIAL",
    "select_one": "SWITCH",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def load_metadata(key: str, scripts_dir: str | None = None) -> dict | None:
    """
    JSON metadata'yı yükler.
    Arama sırası (DÜZELTME: scripts_dir öncelikli):
      1. scripts_dir/DSR/<key>.json  ← kaydedilmiş ayarlar burada
      2. Bu .py dosyasıyla aynı dizinde <key>.json
      3. THIS_DIR/DSR/<key>.json
      4. THIS_DIR/metadata/<key>.json
    """
    here = os.path.dirname(os.path.abspath(__file__))

    search_paths = []

    # 1. Önce scripts_dir içine bak (Save & Apply buraya yazar)
    if scripts_dir:
        search_paths.append(os.path.join(scripts_dir, "DSR", f"{key}.json"))

    # 2. exe/script yanı
    search_paths.append(os.path.join(here, f"{key}.json"))
    search_paths.append(os.path.join(here, "DSR", f"{key}.json"))
    search_paths.append(os.path.join(here, "metadata", f"{key}.json"))

    for path in search_paths:
        print(f"[DEBUG load_metadata] araniyor: {path!r}")
        if os.path.isfile(path):
            print(f"[DEBUG load_metadata] BULUNDU: {path!r}")
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)

    print("[DEBUG load_metadata] BULUNAMADI")
    return None


def weights_to_vals(positions: list) -> list:
    fracs = [Fraction(p["weight"]).limit_denominator(10000) for p in positions]
    denoms = [fr.denominator for fr in fracs]
    lcm_d = reduce(lambda a, b: a * b // gcd(a, b), denoms)
    ints = [int(fr * lcm_d) for fr in fracs]
    g = reduce(gcd, ints)
    result = []
    for i, p in enumerate(positions):
        val = None if p.get("skip_command") else p["delta"]
        result += [val] * (ints[i] // g)
    return result


def format_delta(v) -> str:
    if v is None:
        return "false"
    if isinstance(v, float) and v == int(v):
        return str(int(v))
    return str(v)


_LABEL_ABBREVS = [
    ('Brightness', 'Brt.'),
    ('Rheostat',   'Rheo.'),
    ('Instrument', 'Instr.'),
    ('Altitude',   'Alt.'),
    ('Setting',    'Set.'),
    ('Switch',     'Sw.'),
    ('Station',    'Stn.'),
    ('Secondary',  'Sec.'),
    ('Console',    'Cons.'),
    ('Squelch',    'Sql.'),
    ('Selector',   'Sel.'),
    ('Sighting',   'Sight.'),
    ('Frequency',  'Freq.'),
    ('Receiver',   'Rcvr.'),
    ('control',    'ctrl.'),
    ('Master',     'Mstr.'),
    ('Control',    'Ctrl.'),
    ('Lights',     'Lts.'),
    ('Panel',      'Pnl.'),
    ('Light',      'Lt.'),
]
_LABEL_THRESHOLD = 36


def abbreviate_label(label: str) -> str:
    """Shorten display labels that would cause horizontal scroll.
    Only trailing/middle words are replaced; JSON data is untouched."""
    if len(label) <= _LABEL_THRESHOLD:
        return label
    result = label
    for word, short in _LABEL_ABBREVS:
        if len(result) <= _LABEL_THRESHOLD:
            break
        result = result.replace(word, short)
    return result


def style_msgbox(dlg: QMessageBox) -> None:
    dlg.setStyleSheet(f"""
        QMessageBox {{ background-color: #222222; }}
        QMessageBox QLabel {{ color: {FG}; font-size: 11pt; font-family: Consolas; }}
        QMessageBox QPushButton {{
            background: #1a1a1a; color: {FG};
            font-size: 11pt; font-family: Consolas;
            border: 1px solid #333333; border-radius: 6px;
            padding: 6px 20px; min-width: 70px;
        }}
        QMessageBox QPushButton:hover {{ background: #222222; border: 1px solid {ACC}; }}
        QMessageBox QPushButton:default {{ background: {ACC}; color: #111111; border: none; }}
        QMessageBox QPushButton:default:hover {{ background: #eae8eb; }}
    """)


def generate_lua(metadata: dict) -> str:
    lines = []
    lines.append(f'-- Generated by DCS Switch Randomizer (DSR)')
    lines.append(f'-- Aircraft: {metadata["display_name"]}')
    lines.append(f'-- DO NOT EDIT MANUALLY — use the Settings dialog\n')
    lines.append(f'CR.register("{metadata["aircraft"]}", {{')
    lines.append('')

    CONTINUOUS_VALS = "{0, 0.25, 0.5, 0.75, 1.0}"

    for ctrl in metadata["controls"]:
        enabled = ctrl.get("enabled", True)
        t       = ctrl["type"]
        label   = ctrl["label"]
        dev     = ctrl["dev"]
        cmd     = ctrl.get("cmd")
        comment = f"    -- {label}"

        if t == "run":
            run_note = ctrl.get("run_note", "")
            lua_body = ctrl.get("lua_body", "")
            cmd_str  = str(cmd) if cmd is not None else "nil"
            if not enabled:
                lines.append(f"    -- [DISABLED] {label} (dev={dev}, cmd={cmd_str})")
                if run_note:
                    lines.append(f"    -- {run_note}")
            else:
                lines.append(comment)
                if run_note:
                    lines.append(f"    -- {run_note}")
                lines.append(f"    {{")
                lines.append(f"        dev={dev}, cmd={cmd_str}, label=\"{label}\",")
                lines.append(f"        run=function(device)")
                if lua_body:
                    for body_line in lua_body.splitlines():
                        lines.append(body_line)
                else:
                    lines.append(f"            -- [lua_body tanımsız]")
                lines.append(f"        end")
                lines.append(f"    }},")
            lines.append('')

        elif t == "continuous":
            if not enabled:
                lines.append(
                    f"    -- [DISABLED] {{ dev={dev}, cmd={cmd}, "
                    f"vals={CONTINUOUS_VALS}, label=\"{label}\" }},")
            else:
                lines.append(comment)
                lines.append(
                    f"    {{ dev={dev}, cmd={cmd}, "
                    f"vals={CONTINUOUS_VALS}, label=\"{label}\" }},")
            lines.append('')

        elif t == "select_one":
            # Radio-group: each position has its own cmd.
            # Build a weighted vals list of cmd indices, then emit a run block.
            positions = ctrl.get("positions", [])
            if not enabled:
                lines.append(f"    -- [DISABLED] {label} (select_one, dev={dev})")
            else:
                lines.append(comment)
                pos_comment = " / ".join(
                    f"{p['label']}={p['weight']}%{'(default)' if p.get('is_default') else ''}"
                    for p in positions
                )
                lines.append(f"    -- {pos_comment}")
                # Build weighted cmd list
                from math import gcd
                from functools import reduce
                from fractions import Fraction
                fracs = [Fraction(p["weight"]).limit_denominator(10000) for p in positions]
                denoms = [fr.denominator for fr in fracs]
                lcm_d = reduce(lambda a, b: a * b // gcd(a, b), denoms)
                ints  = [int(fr * lcm_d) for fr in fracs]
                g     = reduce(gcd, ints)
                weighted_cmds = []
                for i, p in enumerate(positions):
                    weighted_cmds += [p["cmd"]] * (ints[i] // g)
                cmds_str = "{" + ", ".join(str(c) for c in weighted_cmds) + "}"
                lines.append(f"    {{")
                lines.append(f"        dev={dev}, cmd=nil, label=\"{label}\",")
                lines.append(f"        run=function(device)")
                lines.append(f"            local cmds = {cmds_str}")
                lines.append(f"            device:performClickableAction(cmds[math.random(#cmds)], 1)")
                lines.append(f"        end")
                lines.append(f"    }},")
            lines.append('')

        elif t == "discrete":
            positions = ctrl.get("positions", [])
            vals = weights_to_vals(positions)
            vals_str = "{" + ", ".join(format_delta(v) for v in vals) + "}"
            pos_comment = " / ".join(
                f"{p['label']}={p['weight']}%{'(default)' if p.get('is_default') else ''}"
                for p in positions
            )
            if not enabled:
                lines.append(
                    f"    -- [DISABLED] {{ dev={dev}, cmd={cmd}, "
                    f"vals=..., label=\"{label}\" }},")
                lines.append(f"    -- {pos_comment}")
            else:
                lines.append(comment)
                lines.append(f"    -- {pos_comment}")
                lines.append(
                    f"    {{ dev={dev}, cmd={cmd}, "
                    f"vals={vals_str}, label=\"{label}\" }},")
            lines.append('')

    lines.append(f'}}, {metadata.get("delay", 3.0)})')
    lines.append('')
    return "\n".join(lines)


# ── RepeatButton ──────────────────────────────────────────────────────────────

class RepeatButton(QPushButton):
    INITIAL_DELAY  = 400
    START_INTERVAL = 80
    MIN_INTERVAL   = 25
    ACCEL_STEP     = 4

    def __init__(self, text: str, callback, **kwargs):
        super().__init__(text, **kwargs)
        self._callback   = callback
        self._locked     = False
        self._timer      = QTimer(self)
        self._timer.setSingleShot(False)
        self._timer.timeout.connect(self._on_tick)
        self._interval   = self.START_INTERVAL
        self._hold_steps = 0

    def set_locked(self, locked: bool, style_locked: str, style_normal: str):
        self._locked = locked
        self.setStyleSheet(style_locked if locked else style_normal)
        if locked:
            self._timer.stop()

    def mousePressEvent(self, e):
        if e.button() == Qt.LeftButton and not self._locked:
            self._callback()
            self._interval   = self.START_INTERVAL
            self._hold_steps = 0
            self._timer.start(self.INITIAL_DELAY)
        super().mousePressEvent(e)

    def mouseReleaseEvent(self, e):
        self._timer.stop()
        super().mouseReleaseEvent(e)

    def _on_tick(self):
        if self._locked:
            self._timer.stop()
            return
        if self._timer.interval() == self.INITIAL_DELAY:
            self._timer.setInterval(self._interval)
        self._callback()
        self._hold_steps += 1
        new_interval = max(self.MIN_INTERVAL, self._interval - self.ACCEL_STEP)
        if new_interval != self._interval:
            self._interval = new_interval
            self._timer.setInterval(self._interval)


# ── PositionRow ───────────────────────────────────────────────────────────────

class PositionRow(QWidget):
    def __init__(self, pos_data: dict, all_rows_ref: list, is_default: bool,
                 change_callback=None):
        super().__init__()
        self._pos             = pos_data
        self._rows            = all_rows_ref
        self._is_default      = is_default
        self._updating        = False
        self._change_callback = change_callback

        lay = QHBoxLayout(self)
        lay.setContentsMargins(0, 2, 0, 2)
        lay.setSpacing(8)

        def_lbl = QLabel("★" if is_default else "  ")
        def_lbl.setFixedWidth(18)
        def_lbl.setStyleSheet(f"color: {ACC}; font-size: 11pt; background: transparent;")
        lay.addWidget(def_lbl)

        name_lbl = QLabel(pos_data["label"])
        name_lbl.setMinimumWidth(60)
        name_lbl.setStyleSheet(f"color: {FG}; font-size: 12pt; "
                                f"font-family: Consolas; background: transparent;")
        lay.addWidget(name_lbl)

        lay.addStretch()

        self.spin = QSpinBox()
        self.spin.setRange(0, 100)
        self.spin.setValue(int(pos_data["weight"]))
        self.spin.setFixedWidth(56)
        self.spin.setFixedHeight(32)
        self.spin.setAlignment(Qt.AlignRight)
        self.spin.setReadOnly(True)
        self.spin.setButtonSymbols(QSpinBox.NoButtons)

        spin_border_color = MUTED if is_default else ACC
        self.spin.setStyleSheet(f"""
            QSpinBox {{
                background: {DARK};
                color: {FG};
                border: 1px solid {spin_border_color};
                border-radius: 4px;
                font-family: Consolas;
                font-size: 12pt;
                padding: 2px 6px;
            }}
            QSpinBox::up-button   {{ width: 0px; }}
            QSpinBox::down-button {{ width: 0px; }}
        """)

        btn_style = f"""
            QPushButton {{
                background: {ACC}; color: #111111;
                border: none; border-radius: 3px;
                font-size: 10pt; padding: 0px;
            }}
            QPushButton:hover   {{ background: #eae8eb; }}
            QPushButton:pressed {{ background: #22cc00; }}
        """

        spin_grp = QHBoxLayout()
        spin_grp.setContentsMargins(0, 0, 0, 0)
        spin_grp.setSpacing(3)
        spin_grp.addWidget(self.spin)

        self._btn_up = None
        if not is_default:
            self._btn_up = RepeatButton("▲", lambda: self.spin.setValue(min(100, self.spin.value() + 1)))
            self._btn_up.setFixedSize(22, 15)
            self._btn_up.setStyleSheet(btn_style)
            self._btn_up.setCursor(Qt.PointingHandCursor)

            btn_dn = RepeatButton("▼", lambda: self.spin.setValue(max(0, self.spin.value() - 1)))
            btn_dn.setFixedSize(22, 15)
            btn_dn.setStyleSheet(btn_style)
            btn_dn.setCursor(Qt.PointingHandCursor)

            btn_col = QVBoxLayout()
            btn_col.setContentsMargins(0, 0, 0, 0)
            btn_col.setSpacing(2)
            btn_col.addWidget(self._btn_up)
            btn_col.addWidget(btn_dn)
            spin_grp.addLayout(btn_col)
        else:
            spacer = QWidget()
            spacer.setFixedSize(22 + 3, 32)
            spin_grp.addWidget(spacer)

        lay.addLayout(spin_grp)
        self.spin.valueChanged.connect(self._on_change)

        if is_default:
            self._update_color()

    def _on_change(self, val):
        if self._updating:
            return
        if self._is_default:
            self._pos["weight"] = val
            return

        self._pos["weight"] = val
        default_row = next((r for r in self._rows if r._is_default), None)
        if default_row is not None:
            others_sum = sum(r.spin.value() for r in self._rows if r is not default_row)
            new_default = max(0, 100 - others_sum)
            default_row._updating = True
            default_row.spin.setValue(new_default)
            default_row._pos["weight"] = new_default
            default_row._updating = False
            default_row._update_color()
            self._sync_up_buttons(locked=(new_default == 0))
        if self._change_callback is not None:
            self._change_callback()

    def _update_color(self):
        color = GREEN if self.spin.value() == 100 else FG
        self.spin.setStyleSheet(f"""
            QSpinBox {{
                background: {DARK}; color: {color};
                border: 1px solid {MUTED};
                border-radius: 4px;
                font-family: Consolas; font-size: 12pt;
                padding: 2px 6px;
            }}
            QSpinBox::up-button   {{ width: 0px; }}
            QSpinBox::down-button {{ width: 0px; }}
        """)

    def _sync_up_buttons(self, locked: bool):
        btn_style_disabled = f"""
            QPushButton {{
                background: #222222; color: {MUTED};
                border: none; border-radius: 3px;
                font-size: 10pt; padding: 0px;
            }}
        """
        btn_style_normal = f"""
            QPushButton {{
                background: {ACC}; color: #111111;
                border: none; border-radius: 3px;
                font-size: 10pt; padding: 0px;
            }}
            QPushButton:hover   {{ background: #eae8eb; }}
            QPushButton:pressed {{ background: #22cc00; }}
        """
        for row in self._rows:
            if row._btn_up is not None:
                row._btn_up.set_locked(locked, btn_style_disabled, btn_style_normal)

    def get_weight(self) -> float:
        return self.spin.value()


# ── ControlCard ───────────────────────────────────────────────────────────────

class ControlCard(QFrame):
    def __init__(self, ctrl: dict, change_callback=None):
        super().__init__()
        self._ctrl            = ctrl
        self._pos_rows: list[PositionRow] = []
        self._change_callback = change_callback

        self.setObjectName("panel")
        self.setStyleSheet(f"QFrame#panel {{ background: rgba(34, 34, 34, 77); border-radius: 6px; }}")

        outer = QVBoxLayout(self)
        outer.setContentsMargins(10, 8, 6, 8)
        outer.setSpacing(4)

        top = QHBoxLayout()
        top.setSpacing(8)

        self.chk = QCheckBox()
        self.chk.setChecked(ctrl.get("enabled", True))
        self.chk.setStyleSheet(f"""
            QCheckBox::indicator {{
                width: 18px; height: 18px;
                border: 2px solid {MUTED};
                border-radius: 3px;
                background: {DARK};
            }}
            QCheckBox::indicator:checked {{
                background: {ACC};
                border: 2px solid {ACC};
                image: none;
            }}
            QCheckBox::indicator:unchecked {{
                background: #1a0000;
                border: 2px solid #c0392b;
                image: none;
            }}
        """)
        self.chk.stateChanged.connect(self._on_toggle)
        top.addWidget(self.chk)

        lbl = QLabel(abbreviate_label(ctrl["label"]))
        lbl.setStyleSheet(f"color: {FG}; font-size: 12pt; "
                           f"font-family: Consolas; font-weight: bold; background: transparent;")
        top.addWidget(lbl)
        top.addStretch()

        t = ctrl["type"]
        badge = QLabel(TYPE_LABEL.get(t, t.upper()))
        badge.setStyleSheet(
            f"background: {TYPE_COLOR.get(t, ACC)}; color: #111111; "
            f"font-size: 9pt; font-family: Consolas; font-weight: bold; "
            f"border-radius: 3px; padding: 2px 6px;")
        top.addWidget(badge)

        outer.addLayout(top)

        self._body = QVBoxLayout()
        self._body.setContentsMargins(26, 0, 0, 0)
        self._body.setSpacing(2)
        outer.addLayout(self._body)

        if t == "discrete":
            self._build_discrete()
        elif t == "select_one":
            self._build_select_one()

        self._set_body_enabled(ctrl.get("enabled", True))

    def _build_discrete(self):
        positions = self._ctrl.get("positions", [])
        non_defaults = [p for p in positions if not p.get("is_default", False)]
        defaults     = [p for p in positions if p.get("is_default", False)]
        for pos in non_defaults + defaults:
            is_def = pos.get("is_default", False)
            row = PositionRow(pos, self._pos_rows, is_def,
                              change_callback=self._change_callback)
            self._pos_rows.append(row)
            self._body.addWidget(row)

    def _build_select_one(self):
        # Same visual as discrete — positions shown with weights.
        # Default position is last (bottom), non-defaults first.
        positions = self._ctrl.get("positions", [])
        non_defaults = [p for p in positions if not p.get("is_default", False)]
        defaults     = [p for p in positions if p.get("is_default", False)]
        for pos in non_defaults + defaults:
            is_def = pos.get("is_default", False)
            row = PositionRow(pos, self._pos_rows, is_def,
                              change_callback=self._change_callback)
            self._pos_rows.append(row)
            self._body.addWidget(row)

    def _on_toggle(self, state):
        enabled = bool(state)
        self._ctrl["enabled"] = enabled
        self._set_body_enabled(enabled)
        if self._change_callback is not None:
            self._change_callback()

    def _set_body_enabled(self, enabled: bool):
        for i in range(self._body.count()):
            item = self._body.itemAt(i)
            if item and item.widget():
                item.widget().setEnabled(enabled)
                item.widget().setStyleSheet(item.widget().styleSheet())

    def is_valid(self) -> tuple[bool, str]:
        if self._ctrl["type"] not in ("discrete", "select_one") or not self._ctrl.get("enabled", True):
            return True, ""
        total = sum(r.get_weight() for r in self._pos_rows)
        if abs(total - 100) > 1:
            return False, self._ctrl["label"]
        return True, ""

    def flush_to_data(self):
        if self._ctrl["type"] in ("discrete", "select_one"):
            positions = self._ctrl["positions"]
            # _pos_rows are ordered non-defaults first, then defaults.
            # Match by label to avoid index mismatch.
            label_to_weight = {r._pos["label"]: r.get_weight() for r in self._pos_rows}
            for p in positions:
                if p["label"] in label_to_weight:
                    p["weight"] = label_to_weight[p["label"]]


# ── AircraftSettingsDialog ────────────────────────────────────────────────────

class AircraftSettingsDialog(QDialog):
    def __init__(self, aircraft_key: str | None, scripts_dir: str | None = None,
                 parent=None):
        super().__init__(parent)
        self._key         = aircraft_key
        self._scripts_dir = scripts_dir
        self._cards: list[ControlCard] = []

        self.setWindowTitle("DCS Switch Randomizer — Settings")
        self.setFixedSize(800, 1280)
        self.setStyleSheet(f"QDialog {{ background: transparent; }}")
        self.setWindowFlags(Qt.Dialog | Qt.FramelessWindowHint)

        # Arka plan görseli
        _this_dir = os.path.dirname(os.path.abspath(__file__))
        bg_path = os.path.join(_this_dir, "DSR", "right-side-bg.png")
        self._bg_pixmap = QPixmap(bg_path) if os.path.isfile(bg_path) else None

        # Placeholder modu — uygulama açılışında hiçbir uçak seçilmemiş
        if aircraft_key is None:
            self._build_placeholder_ui()
            return

        # DÜZELTME: scripts_dir'i load_metadata'ya ilet — kaydedilmiş ayarlar orada
        self._meta = load_metadata(aircraft_key, scripts_dir)
        if self._meta is None:
            self._show_no_metadata()
            return

        self._build_ui()

    def paintEvent(self, event):
        painter = QPainter(self)
        if self._bg_pixmap and not self._bg_pixmap.isNull():
            scaled = self._bg_pixmap.scaled(
                self.size(), Qt.KeepAspectRatioByExpanding, Qt.SmoothTransformation)
            x = (scaled.width()  - self.width())  // 2
            y = (scaled.height() - self.height()) // 2
            painter.setOpacity(0.3)
            painter.drawPixmap(-x, -y, scaled)
            painter.setOpacity(1.0)
        super().paintEvent(event)

    def load_aircraft(self, aircraft_key: str | None, scripts_dir: str | None = None):
        """Mevcut dialog penceresini yeni uçakla yeniden doldur. None → placeholder."""
        self._key         = aircraft_key
        self._scripts_dir = scripts_dir if scripts_dir is not None else self._scripts_dir
        self._cards       = []

        # Mevcut layout'u temizle
        old_layout = self.layout()
        if old_layout:
            while old_layout.count():
                item = old_layout.takeAt(0)
                if item.widget():
                    item.widget().deleteLater()
            QWidget().setLayout(old_layout)

        if aircraft_key is None:
            self._build_placeholder_ui()
            return

        self._meta = load_metadata(aircraft_key, self._scripts_dir)
        if self._meta is None:
            self._show_no_metadata()
            return
        self._build_ui()

    def _build_placeholder_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)

        # Başlık çubuğu
        tb = QWidget()
        tb.setFixedHeight(40)
        tb.setStyleSheet("background: transparent;")
        tb_lay = QHBoxLayout(tb)
        tb_lay.setContentsMargins(16, 0, 8, 0)

        title_lbl = QLabel("Switch Settings")
        title_lbl.setStyleSheet(
            f"color: {FG}; font-family: Consolas; font-size: 10pt; background: transparent;")
        tb_lay.addWidget(title_lbl)
        tb_lay.addStretch()

        self._drag_pos = None
        def _tb_press_ph(e):
            if e.button() == Qt.LeftButton:
                self._drag_pos = e.globalPos() - self.frameGeometry().topLeft()
        def _tb_move_ph(e):
            if e.buttons() == Qt.LeftButton and self._drag_pos:
                self.move(e.globalPos() - self._drag_pos)
                p = self.parent()
                if p is not None and hasattr(p, "width"):
                    geo = self.frameGeometry()
                    p.move(geo.left() - p.width() - 10,
                           geo.top() + (geo.height() - p.height()) // 2)
        tb.mousePressEvent = _tb_press_ph
        tb.mouseMoveEvent  = _tb_move_ph

        root.addWidget(tb)

        # Divider
        div = QFrame(); div.setFixedHeight(1)
        div.setStyleSheet(f"background: #222222;")
        root.addWidget(div)

        # Ortalanmış mesaj
        body = QWidget()
        body.setStyleSheet(f"background: transparent;")
        body_lay = QVBoxLayout(body)
        body_lay.setContentsMargins(32, 0, 32, 0)
        body_lay.setSpacing(0)

        hint = QLabel("Click the gear icon next to an aircraft\nto configure its switch settings.")
        hint.setStyleSheet(
            f"color: {WHITE}; font-family: Consolas; font-size: 13pt; background: transparent;")
        hint.setAlignment(Qt.AlignCenter)
        hint.setWordWrap(True)

        status_title = QLabel("CURRENT TESTING STATUS")
        status_title.setStyleSheet(
            "color: #e74c3c; font-family: Consolas; font-size: 11pt; "
            "font-weight: bold; background: transparent;")
        status_title.setAlignment(Qt.AlignCenter)

        notice = QLabel(
            'Second-stage testing for the F/A-18C has been completed.<br>'
            'First-stage testing for the F-16C, F-5E, F-4E, and F-14B has been completed.<br><br>'
            '<span style="color:#ffd255;">All other aircraft are still undergoing first-stage testing.</span><br><br>'
            'As a result, you may occasionally encounter switches or knobs that are '
            'randomized contrary to your settings, incorrectly named, or otherwise '
            'behaving unexpectedly.<br><br>'
            'Please report any incorrect switch mappings, naming errors, or unexpected '
            'randomization behavior by opening an issue on '
            '<a href="https://github.com/onur-karabiber/dcs-switch-randomizer/issues" '
            'style="color:#4ea3ff; text-decoration:underline;">GitHub</a>.')
        notice.setTextFormat(Qt.RichText)
        notice.setOpenExternalLinks(True)
        notice.setStyleSheet(
            "color: #e74c3c; font-family: Consolas; font-size: 10pt; background: transparent;")
        notice.setAlignment(Qt.AlignLeft)
        notice.setWordWrap(True)

        from PyQt5.QtWidgets import QSpacerItem, QSizePolicy
        body_lay.addItem(QSpacerItem(0, 290, QSizePolicy.Minimum, QSizePolicy.Fixed))
        body_lay.addWidget(hint)
        body_lay.addItem(QSpacerItem(0, 72, QSizePolicy.Minimum, QSizePolicy.Fixed))
        body_lay.addWidget(status_title, alignment=Qt.AlignHCenter)
        body_lay.addItem(QSpacerItem(0, 14, QSizePolicy.Minimum, QSizePolicy.Fixed))
        body_lay.addWidget(notice)
        body_lay.addStretch()

        root.addWidget(body, stretch=1)

    def _show_no_metadata(self):
        lay = QVBoxLayout(self)
        lbl = QLabel(f"No metadata found for '{self._key}'.\n\n"
                     f"Expected: {self._key}.json next to this script.")
        lbl.setStyleSheet(f"color: {HL}; font-family: Consolas; font-size: 12pt;")
        lbl.setAlignment(Qt.AlignCenter)
        lay.addWidget(lbl)
        btn = QPushButton("Close")
        btn.clicked.connect(self.reject)
        lay.addWidget(btn)

    def _build_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)

        # ── Başlık çubuğu ─────────────────────────────────────────────────
        tb = QWidget()
        tb.setFixedHeight(40)
        tb.setStyleSheet("background: transparent;")
        tb_lay = QHBoxLayout(tb)
        tb_lay.setContentsMargins(16, 0, 8, 0)

        title_lbl = QLabel(
            f"{self._meta.get('display_name', self._key)}  —  Switch Settings")
        title_lbl.setStyleSheet(
            f"color: {FG}; font-family: Consolas; font-size: 11pt; background: transparent;")
        tb_lay.addWidget(title_lbl)
        tb_lay.addStretch()

        cls_btn = QPushButton("✕")
        cls_btn.setFixedSize(32, 32)
        cls_btn.setStyleSheet(f"""
            QPushButton {{ background: transparent; color: {MUTED};
                          font-size: 13pt; border: none; }}
            QPushButton:hover {{ background: #1a0000; color: #e74c3c; }}
        """)
        cls_btn.setCursor(Qt.PointingHandCursor)
        cls_btn.clicked.connect(self._cancel)
        tb_lay.addWidget(cls_btn)

        self._drag_pos = None
        def _tb_press(e):
            if e.button() == Qt.LeftButton:
                self._drag_pos = e.globalPos() - self.frameGeometry().topLeft()
        def _tb_move(e):
            if e.buttons() == Qt.LeftButton and self._drag_pos:
                self.move(e.globalPos() - self._drag_pos)
                p = self.parent()
                if p is not None and hasattr(p, "width"):
                    geo = self.frameGeometry()
                    p.move(geo.left() - p.width() - 10,
                           geo.top() + (geo.height() - p.height()) // 2)
        tb.mousePressEvent = _tb_press
        tb.mouseMoveEvent  = _tb_move

        root.addWidget(tb)

        # Divider
        div1 = QFrame(); div1.setFixedHeight(1)
        div1.setStyleSheet(f"background: #222222;")
        root.addWidget(div1)

        # ── Scroll area ────────────────────────────────────────────────────
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.NoFrame)
        scroll.viewport().setStyleSheet("background: transparent;")
        scroll.setStyleSheet(f"""
            QScrollArea {{ background: transparent; border: none; }}
            QScrollBar:vertical {{
                background: {TB}; width: 8px; margin: 0;
            }}
            QScrollBar::handle:vertical {{
                background: {MUTED}; border-radius: 4px; min-height: 20px;
            }}
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{ height: 0px; }}
        """)

        inner = QWidget()
        inner.setStyleSheet(f"background: transparent;")
        inner.setAttribute(Qt.WA_TranslucentBackground)
        inner_lay = QVBoxLayout(inner)
        inner_lay.setContentsMargins(16, 12, 16, 12)
        inner_lay.setSpacing(8)

        controls = self._meta.get("controls", [])
        for ctrl in controls:
            card = ControlCard(ctrl, change_callback=self._mark_pending)
            self._cards.append(card)
            inner_lay.addWidget(card)

        inner_lay.addStretch()
        scroll.setWidget(inner)
        root.addWidget(scroll)

        # Divider
        div2 = QFrame(); div2.setFixedHeight(1)
        div2.setStyleSheet(f"background: #222222;")
        root.addWidget(div2)

        # ── Alt butonlar ───────────────────────────────────────────────────
        bottom = QWidget()
        bottom.setStyleSheet("background: transparent;")
        bot_lay = QHBoxLayout(bottom)
        bot_lay.setContentsMargins(16, 10, 16, 10)
        bot_lay.setSpacing(8)

        self._status_lbl = QLabel("")
        self._status_lbl.setStyleSheet(
            f"color: {MUTED}; font-family: Consolas; font-size: 10pt; background: transparent;")
        bot_lay.addWidget(self._status_lbl)
        bot_lay.addStretch()

        for text, style, slot in [
            ("Cancel",        "secbtn", self._cancel),
            ("Save && Apply", "apply",  self._save),   # [3] && = literal &
        ]:
            btn = QPushButton(text)
            btn.setFixedHeight(40)
            btn.setMinimumWidth(150)
            btn.setCursor(Qt.PointingHandCursor)
            if style == "apply":
                btn.setStyleSheet(f"""
                    QPushButton {{ background: transparent; color: {FG};
                        font-family: Consolas; font-size: 12pt; font-weight: bold;
                        border: 1px solid {ACC}; border-radius: 6px; padding: 0 16px; }}
                    QPushButton:hover {{ background: rgba(154,230,155,0.12); }}
                    QPushButton:pressed {{ background: rgba(154,230,155,0.25); }}
                """)
            else:
                btn.setStyleSheet(f"""
                    QPushButton {{ background: transparent; color: {WHITE};
                        font-family: Consolas; font-size: 12pt;
                        border: 1px solid #333333; border-radius: 6px; padding: 0 16px; }}
                    QPushButton:hover {{ background: rgba(34,34,34,0.5); border: 1px solid {ACC}; }}
                """)
            btn.clicked.connect(slot)
            bot_lay.addWidget(btn)
            if style == "apply":
                self._btn_save = btn
            else:
                self._btn_cancel = btn

        root.addWidget(bottom)

    # ── Pending state ─────────────────────────────────────────────────────────

    def _mark_pending(self):
        """Bir parametre değişti — Save & Apply butonunu amber renge boyar."""
        btn = getattr(self, "_btn_save", None)
        if btn is not None:
            btn.setStyleSheet(f"""
                QPushButton {{ background: #ebd805; color: #111111;
                    font-family: Consolas; font-size: 12pt; font-weight: bold;
                    border: none; border-radius: 6px; padding: 0 16px; }}
                QPushButton:hover   {{ background: #d4a017; }}
                QPushButton:pressed {{ background: #8b6508; }}
            """)
        cancel_btn = getattr(self, "_btn_cancel", None)
        if cancel_btn is not None:
            cancel_btn.setText("Close")
        self._status("Click Save & Apply to save changes.", "#f0c040")

    def _clear_pending(self):
        """Kayıt tamamlandı — Save & Apply butonunu normal stiline döndür."""
        btn = getattr(self, "_btn_save", None)
        if btn is not None:
            btn.setStyleSheet(f"""
                QPushButton {{ background: transparent; color: {ACC};
                    font-family: Consolas; font-size: 12pt; font-weight: bold;
                    border: 1px solid {ACC}; border-radius: 6px; padding: 0 16px; }}
                QPushButton:hover   {{ background: rgba(154,230,155,0.12); }}
                QPushButton:pressed {{ background: rgba(154,230,155,0.25); }}
            """)
        cancel_btn = getattr(self, "_btn_cancel", None)
        if cancel_btn is not None:
            cancel_btn.setText("Close")

    # ── Save ──────────────────────────────────────────────────────────────────

    def _save(self):
        try:
            self._save_impl()
        except Exception as e:
            import traceback
            print(f"[SAVE ERROR]\n{traceback.format_exc()}")
            try:
                self._status(f"Error: {e}", HL)
            except Exception:
                pass

    def _save_impl(self):
        errors = []
        for card in self._cards:
            card.flush_to_data()
            ok, label = card.is_valid()
            if not ok:
                errors.append(label)

        if errors:
            msg = QMessageBox(self)
            msg.setWindowTitle("Cannot Save — Weight Errors")
            msg.setIcon(QMessageBox.Warning)
            style_msgbox(msg)
            detail_lines = "\n".join(f"  • {name}" for name in errors)
            msg.setText(
                "The weights for the following switches do not add up to 100 %.\n"
                "Correct them before saving.\n\n" + detail_lines
            )
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
            self._status(
                f"⚠  {len(errors)} switch{'es' if len(errors) > 1 else ''} with invalid weights — not saved.",
                HL)
            return

        lua_content = generate_lua(self._meta)

        if self._scripts_dir:
            cr_dir    = os.path.join(self._scripts_dir, "DSR")
            lua_path  = os.path.join(cr_dir, f"{self._key}.lua")
            json_path = os.path.join(cr_dir, f"{self._key}.json")
            print(f"[DEBUG _save] lua_path:  {lua_path!r}")
            print(f"[DEBUG _save] json_path: {json_path!r}")
            with open(lua_path, "w", encoding="utf-8") as f:
                f.write(lua_content)
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(self._meta, f, indent=2, ensure_ascii=False)
            self._clear_pending()
            self._status("Saved.", GREEN)
        else:
            print("\n" + "="*60)
            print(lua_content)
            print("="*60)
            self._status("Generated (test mode)", MUTED)

    def reject(self):
        p = self.parent()
        if p is not None and hasattr(p, "_persistent_settings_dlg"):
            self.load_aircraft(None)
        else:
            super().reject()

    def _cancel(self):
        self.reject()

    def _after_save(self):
        # Kalıcı mod: parent MainWindow — placeholder'a dön
        from PyQt5.QtWidgets import QWidget as _QW
        p = self.parent()
        if p is not None and hasattr(p, "_persistent_settings_dlg"):
            self.load_aircraft(None)
        else:
            self.accept()

    def _status(self, msg: str, color: str = MUTED):
        self._status_lbl.setStyleSheet(
            f"color: {color}; font-family: Consolas; font-size: 10pt; background: transparent;")
        self._status_lbl.setText(msg)


# ── Standalone test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyle("Fusion")
    dlg = AircraftSettingsDialog("fa18c", scripts_dir=None)
    dlg.show()
    sys.exit(app.exec_())
