# aircraft_settings.py — CockpitRandomizer Aircraft Settings Dialog
# Prototype: JSON metadata → PyQt5 UI → .lua generator
#
# Entegrasyon notu: Bu dosya mevcut dcs-cockpit-randomizer-qt.py ile
# birlikte çalışır. AircraftRow'daki çark ikonuna tıklanınca
# AircraftSettingsDialog(key, scripts_dir, parent) çağrılır.

import sys, os, json, copy
from math import gcd
from functools import reduce
from fractions import Fraction

from PyQt5.QtWidgets import (
    QApplication, QDialog, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton, QFrame, QScrollArea, QSpinBox,
    QCheckBox, QSizePolicy, QMessageBox
)
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QFont, QColor

# ── Palette (mevcut uygulamayla aynı) ────────────────────────────────────────
BG    = "#1a1d2e"
PANEL = "#16213e"
TB    = "#0d0f1e"
HL    = "#e05c7a"
ACC   = "#2d5fa0"
FG    = "#c0c8f0"
MUTED = "#5a6080"
GREEN = "#2e7d32"
DARK  = "#0d1020"

# ── Tip renkleri ──────────────────────────────────────────────────────────────
TYPE_COLOR = {
    "discrete":   "#2d5fa0",
    "continuous": "#4a6a3a",
    "run":        "#6a4a2a",
}
TYPE_LABEL = {
    "discrete":   "SWITCH",
    "continuous": "KNOB",
    "run":        "SPECIAL",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def load_metadata(key: str) -> dict | None:
    """
    JSON metadata'yı yükler.
    Arama sırası:
      1. Bu .py dosyasıyla aynı dizinde <key>.json
      2. CockpitRandomizer/<key>.json  (Lua dosyalarıyla aynı yer)
      3. metadata/<key>.json
    """
    here = os.path.dirname(os.path.abspath(__file__))
    print(f"[DEBUG load_metadata] key={key!r}")
    print(f"[DEBUG load_metadata] here={here!r}")
    for path in [
        os.path.join(here, f"{key}.json"),
        os.path.join(here, "CockpitRandomizer", f"{key}.json"),
        os.path.join(here, "metadata", f"{key}.json"),
    ]:
        print(f"[DEBUG load_metadata] araniyor: {path!r}")
        if os.path.isfile(path):
            print(f"[DEBUG load_metadata] BULUNDU: {path!r}")
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
    print("[DEBUG load_metadata] BULUNAMADI")
    return None


def weights_to_vals(positions: list) -> list:
    """
    [{"delta": 0, "weight": 90}, {"delta": -1, "weight": 10}]
    → [0, 0, 0, 0, 0, 0, 0, 0, 0, -1]
    Fraction ile tam sayı GCD — 0.5 gibi weight'leri de destekler.
    """
    fracs = [Fraction(p["weight"]).limit_denominator(10000) for p in positions]
    denoms = [fr.denominator for fr in fracs]
    lcm_d = reduce(lambda a, b: a * b // gcd(a, b), denoms)
    ints = [int(fr * lcm_d) for fr in fracs]
    g = reduce(gcd, ints)
    result = []
    for i, p in enumerate(positions):
        result += [p["delta"]] * (ints[i] // g)
    return result


def format_delta(v) -> str:
    """Lua'da yazılacak delta değerini formatla."""
    if isinstance(v, float) and v == int(v):
        return str(int(v))
    return str(v)


def style_msgbox(dlg: QMessageBox) -> None:
    """QMessageBox'a tutarlı stil uygula."""
    dlg.setStyleSheet(f"""
        QMessageBox {{
            background-color: #2a2d3e;
        }}
        QMessageBox QLabel {{
            color: {FG};
            font-size: 11pt;
            font-family: Consolas;
        }}
        QMessageBox QPushButton {{
            background: {ACC}; color: white;
            font-size: 11pt; font-family: Consolas;
            border: none; border-radius: 6px;
            padding: 6px 20px; min-width: 70px;
        }}
        QMessageBox QPushButton:hover {{ background: #1e5799; }}
        QMessageBox QPushButton:default {{ background: {HL}; }}
        QMessageBox QPushButton:default:hover {{ background: #c73652; }}
    """)


def generate_lua(metadata: dict) -> str:
    """
    JSON metadata → fa18c.lua içeriği.
    run ve continuous tipler template'ten olduğu gibi gelir;
    disabled olanlar yorum satırına alınır.
    """
    lines = []
    lines.append(f'-- Generated by CockpitRandomizer GUI')
    lines.append(f'-- Aircraft: {metadata["display_name"]}')
    lines.append(f'-- DO NOT EDIT MANUALLY — use the Settings dialog\n')
    lines.append(f'CR.register("{metadata["aircraft"]}", {{')
    lines.append('')

    # Continuous kontroller için sabit vals
    CONTINUOUS_VALS = "{0, 0.25, 0.5, 0.75, 1.0}"

    for ctrl in metadata["controls"]:
        enabled = ctrl.get("enabled", True)
        t       = ctrl["type"]
        label   = ctrl["label"]
        dev     = ctrl["dev"]
        cmd     = ctrl["cmd"]
        comment = f"    -- {label}"

        if t == "run":
            run_note = ctrl.get("run_note", "")
            lua_body = ctrl.get("lua_body", "")
            cmd_str  = str(cmd) if cmd is not None else "nil"
            if not enabled:
                lines.append(f"    -- [DISABLED] {label} (dev={dev}, cmd={cmd_str})")
                if run_note:
                    lines.append(f"    -- {run_note}")
            else:
                lines.append(comment)
                if run_note:
                    lines.append(f"    -- {run_note}")
                lines.append(f"    {{")
                lines.append(f"        dev={dev}, cmd={cmd_str}, label=\"{label}\",")
                lines.append(f"        run=function(device)")
                if lua_body:
                    # Her satırı olduğu gibi yaz (girinti lua_body içinde saklı)
                    for body_line in lua_body.splitlines():
                        lines.append(body_line)
                else:
                    lines.append(f"            -- [lua_body tanımsız — bu kontrol için run() gövdesi eksik]")
                lines.append(f"        end")
                lines.append(f"    }},")
            lines.append('')

        elif t == "continuous":
            if not enabled:
                lines.append(
                    f"    -- [DISABLED] {{ dev={dev}, cmd={cmd}, "
                    f"vals={CONTINUOUS_VALS}, label=\"{label}\" }},")
            else:
                lines.append(comment)
                lines.append(
                    f"    {{ dev={dev}, cmd={cmd}, "
                    f"vals={CONTINUOUS_VALS}, label=\"{label}\" }},")
            lines.append('')

        elif t == "discrete":
            positions = ctrl.get("positions", [])
            vals = weights_to_vals(positions)
            vals_str = "{" + ", ".join(format_delta(v) for v in vals) + "}"
            # Pozisyon açıklaması
            pos_comment = " / ".join(
                f"{p['label']}={p['weight']}%{'(default)' if p.get('is_default') else ''}"
                for p in positions
            )
            if not enabled:
                lines.append(
                    f"    -- [DISABLED] {{ dev={dev}, cmd={cmd}, "
                    f"vals=..., label=\"{label}\" }},")
                lines.append(f"    -- {pos_comment}")
            else:
                lines.append(comment)
                lines.append(f"    -- {pos_comment}")
                lines.append(
                    f"    {{ dev={dev}, cmd={cmd}, "
                    f"vals={vals_str}, label=\"{label}\" }},")
            lines.append('')

    lines.append(f'}}, {metadata.get("delay", 3.0)})')
    lines.append('')
    return "\n".join(lines)


# ── Basılı tutma + ivme destekli buton ───────────────────────────────────────

class RepeatButton(QPushButton):
    """
    Tek tıkta bir adım uygular.
    Basılı tutulduğunda INITIAL_DELAY ms sonra tekrar modu başlar;
    her adımda interval MIN_INTERVAL'a doğru kısalır (ivmelenme).
    """
    INITIAL_DELAY = 400   # ms — ilk tekrar başlamadan önceki bekleme
    START_INTERVAL = 80   # ms — tekrar modunun başlangıç aralığı
    MIN_INTERVAL   = 25   # ms — en hızlı tekrar aralığı
    ACCEL_STEP     = 4    # ms — her adımda interval ne kadar azalsın

    def __init__(self, text: str, callback, **kwargs):
        super().__init__(text, **kwargs)
        self._callback   = callback
        self._locked     = False   # setEnabled yerine bu flag kullanılır
        self._timer      = QTimer(self)
        self._timer.setSingleShot(False)
        self._timer.timeout.connect(self._on_tick)
        self._interval   = self.START_INTERVAL
        self._hold_steps = 0

    def set_locked(self, locked: bool, style_locked: str, style_normal: str):
        """
        Qt event mekanizmasını bozmadan görsel kilitleme.
        setEnabled() yerine bu metod kullanılır.
        """
        self._locked = locked
        self.setStyleSheet(style_locked if locked else style_normal)
        if locked:
            self._timer.stop()   # basılı tutarken kilitlenirse timer'ı durdur

    def mousePressEvent(self, e):
        if e.button() == Qt.LeftButton and not self._locked:
            self._callback()                        # ilk anında adım
            self._interval   = self.START_INTERVAL
            self._hold_steps = 0
            self._timer.start(self.INITIAL_DELAY)   # ilk gecikme
        super().mousePressEvent(e)

    def mouseReleaseEvent(self, e):
        self._timer.stop()
        super().mouseReleaseEvent(e)

    def _on_tick(self):
        if self._locked:
            self._timer.stop()
            return
        # İlk tick'ten sonra normal aralığa geç
        if self._timer.interval() == self.INITIAL_DELAY:
            self._timer.setInterval(self._interval)
        self._callback()
        self._hold_steps += 1
        # İvmelenme: her adımda interval kısalt
        new_interval = max(self.MIN_INTERVAL,
                           self._interval - self.ACCEL_STEP)
        if new_interval != self._interval:
            self._interval = new_interval
            self._timer.setInterval(self._interval)


# ── Widget: tek pozisyon satırı ───────────────────────────────────────────────

class PositionRow(QWidget):
    """
    Tek bir switch pozisyonu: [LABEL]  [SpinBox %]

    Davranış kuralları:
      - is_default=True olan satır read-only'dir; değeri diğer satırların
        toplamına göre otomatik olarak hesaplanır (100 - diğerleri).
      - is_default=False olan satırlar düzenlenebilir.
      - Herhangi bir satır değiştiğinde, default satır anında güncellenir.
    """
    def __init__(self, pos_data: dict, all_rows_ref: list, is_default: bool):
        super().__init__()
        self._pos        = pos_data
        self._rows       = all_rows_ref  # kardeş satırlar (dışarıdan set edilir)
        self._is_default = is_default
        self._updating   = False

        lay = QHBoxLayout(self)
        lay.setContentsMargins(0, 2, 0, 2)
        lay.setSpacing(8)

        # Default işareti
        def_lbl = QLabel("★" if is_default else "  ")
        def_lbl.setFixedWidth(18)
        def_lbl.setStyleSheet(f"color: #f9a825; font-size: 11pt; background: transparent;")
        lay.addWidget(def_lbl)

        # Pozisyon adı
        name_lbl = QLabel(pos_data["label"])
        name_lbl.setMinimumWidth(60)
        name_lbl.setStyleSheet(f"color: {FG}; font-size: 12pt; "
                                f"font-family: Consolas; background: transparent;")
        lay.addWidget(name_lbl)

        lay.addStretch()

        # % spinbox + ▲▼ butonları
        self.spin = QSpinBox()
        self.spin.setRange(0, 100)
        self.spin.setValue(int(pos_data["weight"]))
        self.spin.setFixedWidth(56)
        self.spin.setFixedHeight(32)
        self.spin.setAlignment(Qt.AlignRight)

        # Her iki tip de read-only — giriş sadece ▲▼ butonlarıyla
        self.spin.setReadOnly(True)
        self.spin.setButtonSymbols(QSpinBox.NoButtons)
        if is_default:
            spin_border_color = MUTED
        else:
            spin_border_color = ACC

        self.spin.setStyleSheet(f"""
            QSpinBox {{
                background: {DARK};
                color: {FG};
                border: 1px solid {spin_border_color};
                border-radius: 4px;
                font-family: Consolas;
                font-size: 12pt;
                padding: 2px 6px;
            }}
            QSpinBox::up-button   {{ width: 0px; }}
            QSpinBox::down-button {{ width: 0px; }}
        """)

        btn_style = f"""
            QPushButton {{
                background: {ACC};
                color: {FG};
                border: none;
                border-radius: 3px;
                font-size: 10pt;
                padding: 0px;
            }}
            QPushButton:hover   {{ background: #1e5799; }}
            QPushButton:pressed {{ background: #1a4a80; }}
        """

        spin_grp = QHBoxLayout()
        spin_grp.setContentsMargins(0, 0, 0, 0)
        spin_grp.setSpacing(3)
        spin_grp.addWidget(self.spin)

        # Default satıra ▲▼ buton ekleme
        self._btn_up = None  # non-default satırlarda set edilir
        if not is_default:
            self._btn_up = RepeatButton("▲", lambda: self.spin.setValue(min(100, self.spin.value() + 1)))
            self._btn_up.setFixedSize(22, 15)
            self._btn_up.setStyleSheet(btn_style)
            self._btn_up.setCursor(Qt.PointingHandCursor)

            btn_dn = RepeatButton("▼", lambda: self.spin.setValue(max(0, self.spin.value() - 1)))
            btn_dn.setFixedSize(22, 15)
            btn_dn.setStyleSheet(btn_style)
            btn_dn.setCursor(Qt.PointingHandCursor)

            btn_col = QVBoxLayout()
            btn_col.setContentsMargins(0, 0, 0, 0)
            btn_col.setSpacing(2)
            btn_col.addWidget(self._btn_up)
            btn_col.addWidget(btn_dn)
            spin_grp.addLayout(btn_col)
        else:
            # Default satır için boş alan — hizalamayı koru
            spacer = QWidget()
            spacer.setFixedSize(22 + 3, 32)  # btn_col genişliği kadar
            spin_grp.addWidget(spacer)

        lay.addLayout(spin_grp)

        self.spin.valueChanged.connect(self._on_change)

        # İlk açılışta default rengi uygula
        if is_default:
            self._update_color()

    def _on_change(self, val):
        if self._updating:
            return
        if self._is_default:
            # Default satırın değeri programatik olarak set edildi; sadece veriyi güncelle
            self._pos["weight"] = val
            return

        # Non-default satır değişti: default kardeşi güncelle
        self._pos["weight"] = val
        default_row = next((r for r in self._rows if r._is_default), None)
        if default_row is not None:
            others_sum = sum(r.spin.value() for r in self._rows if r is not default_row)
            new_default = max(0, 100 - others_sum)
            default_row._updating = True
            default_row.spin.setValue(new_default)
            default_row._pos["weight"] = new_default
            default_row._updating = False
            # Default rengi güncelle: 100 ise yeşil (etkisiz switch uyarısı), değilse normal
            default_row._update_color()
            # Default 0'a düştüyse tüm ▲ butonlarını kilitle, yükseldiyse aç
            self._sync_up_buttons(locked=(new_default == 0))

    def _update_color(self):
        """Default spin rengini değerine göre güncelle: 100 → yeşil, diğer → normal."""
        color = GREEN if self.spin.value() == 100 else FG
        self.spin.setStyleSheet(f"""
            QSpinBox {{
                background: {DARK};
                color: {color};
                border: 1px solid {MUTED};
                border-radius: 4px;
                font-family: Consolas;
                font-size: 12pt;
                padding: 2px 6px;
            }}
            QSpinBox::up-button   {{ width: 0px; }}
            QSpinBox::down-button {{ width: 0px; }}
        """)

    def _sync_up_buttons(self, locked: bool):
        """Tüm non-default kardeşlerin ▲ butonunu görsel olarak kilitle veya aç."""
        btn_style_disabled = f"""
            QPushButton {{
                background: {MUTED};
                color: #3a3a5a;
                border: none;
                border-radius: 3px;
                font-size: 10pt;
                padding: 0px;
            }}
        """
        btn_style_normal = f"""
            QPushButton {{
                background: {ACC};
                color: {FG};
                border: none;
                border-radius: 3px;
                font-size: 10pt;
                padding: 0px;
            }}
            QPushButton:hover   {{ background: #1e5799; }}
            QPushButton:pressed {{ background: #1a4a80; }}
        """
        for row in self._rows:
            if row._btn_up is not None:
                row._btn_up.set_locked(locked, btn_style_disabled, btn_style_normal)

    def get_weight(self) -> float:
        return self.spin.value()


# ── Widget: tek kontrol kartı ─────────────────────────────────────────────────

class ControlCard(QFrame):
    """
    Bir switch/knob/run kontrolünü temsil eden kart.
    ┌──────────────────────────────────────────────┐
    │ ☑  Master Arm Switch          [SWITCH]        │
    │    SAFE ★  [90 %]  (read-only, auto)         │
    │    ARM     [10 %]                            │
    │    toplam: 100 %  ✓                          │
    └──────────────────────────────────────────────┘
    """
    def __init__(self, ctrl: dict):
        super().__init__()
        self._ctrl = ctrl
        self._pos_rows: list[PositionRow] = []

        self.setObjectName("panel")
        self.setStyleSheet(f"QFrame#panel {{ background: {PANEL}; border-radius: 6px; }}")

        outer = QVBoxLayout(self)
        outer.setContentsMargins(10, 8, 6, 8)
        outer.setSpacing(4)

        # ── Başlık satırı ──────────────────────────────────────────────────
        top = QHBoxLayout()
        top.setSpacing(8)

        # Enable checkbox
        self.chk = QCheckBox()
        self.chk.setChecked(ctrl.get("enabled", True))
        self.chk.setStyleSheet(f"""
            QCheckBox::indicator {{
                width: 18px; height: 18px;
                border: 2px solid {MUTED};
                border-radius: 3px;
                background: {DARK};
            }}
            QCheckBox::indicator:checked {{
                background: #1b5e20;
                border: 2px solid #43a047;
                image: none;
            }}
            QCheckBox::indicator:unchecked {{
                background: #3a0a0a;
                border: 2px solid #c0392b;
                image: none;
            }}
        """)
        self.chk.stateChanged.connect(self._on_toggle)
        top.addWidget(self.chk)

        # Label
        lbl = QLabel(ctrl["label"])
        lbl.setStyleSheet(f"color: {FG}; font-size: 12pt; "
                           f"font-family: Consolas; font-weight: bold; background: transparent;")
        top.addWidget(lbl)
        top.addStretch()

        # Tip badge
        t = ctrl["type"]
        badge = QLabel(TYPE_LABEL.get(t, t.upper()))
        badge.setStyleSheet(
            f"background: {TYPE_COLOR.get(t, ACC)}; color: white; "
            f"font-size: 9pt; font-family: Consolas; font-weight: bold; "
            f"border-radius: 3px; padding: 2px 6px;")
        top.addWidget(badge)

        outer.addLayout(top)

        # ── Alt içerik ─────────────────────────────────────────────────────
        self._body = QVBoxLayout()
        self._body.setContentsMargins(26, 0, 0, 0)
        self._body.setSpacing(2)
        outer.addLayout(self._body)

        if t == "discrete":
            self._build_discrete()
        # continuous ve run: badge yeterli, ek içerik gerekmez

        self._set_body_enabled(ctrl.get("enabled", True))

    def _build_discrete(self):
        positions = self._ctrl.get("positions", [])
        # non-default pozisyonlar üste, default alta
        non_defaults = [p for p in positions if not p.get("is_default", False)]
        defaults     = [p for p in positions if p.get("is_default", False)]
        for pos in non_defaults + defaults:
            is_def = pos.get("is_default", False)
            row = PositionRow(pos, self._pos_rows, is_def)
            self._pos_rows.append(row)
            self._body.addWidget(row)

        # Her non-default spinbox değişince _sync_up_buttons tetiklenir (total label yok)

    def _on_toggle(self, state):
        enabled = bool(state)
        self._ctrl["enabled"] = enabled
        self._set_body_enabled(enabled)

    def _set_body_enabled(self, enabled: bool):
        for i in range(self._body.count()):
            item = self._body.itemAt(i)
            if item and item.widget():
                item.widget().setEnabled(enabled)
                item.widget().setStyleSheet(item.widget().styleSheet())  # repaint

    def is_valid(self) -> tuple[bool, str]:
        """Discrete kontrolün weight toplamı 100 mü?"""
        if self._ctrl["type"] != "discrete" or not self._ctrl.get("enabled", True):
            return True, ""
        total = sum(r.get_weight() for r in self._pos_rows)
        if abs(total - 100) > 1:
            return False, self._ctrl["label"]
        return True, ""

    def flush_to_data(self):
        """UI değerlerini ctrl dict'e yaz."""
        if self._ctrl["type"] == "discrete":
            for i, row in enumerate(self._pos_rows):
                self._ctrl["positions"][i]["weight"] = row.get_weight()


# ── Ana dialog ────────────────────────────────────────────────────────────────

class AircraftSettingsDialog(QDialog):
    """
    Bir aircraft için settings ekranı.
    Kullanım: AircraftSettingsDialog("fa18c", scripts_dir, parent).exec_()
    """
    def __init__(self, aircraft_key: str, scripts_dir: str | None = None,
                 parent=None):
        super().__init__(parent)
        self._key        = aircraft_key
        self._scripts_dir = scripts_dir
        self._cards: list[ControlCard] = []

        self.setWindowTitle(f"CockpitRandomizer — Settings")
        self.setFixedWidth(800)
        # Mantıksal piksel cinsinden ekran yüksekliği (DPI scaling dahil)
        _screen = QApplication.desktop().availableGeometry()
        _dpr    = QApplication.instance().devicePixelRatio()
        screen_h = int(_screen.height() / _dpr)
        print(f"[DEBUG dialog] screen_h(logical)={screen_h}, dpr={_dpr}")
        target_h = min(920, screen_h - 60)
        self.setMinimumHeight(400)
        self.setMaximumHeight(screen_h - 60)
        self.resize(620, target_h)
        self.resize(620, min(960, screen_h - 80))
        self.setStyleSheet(f"QDialog {{ background: {BG}; }}")
        self.setWindowFlags(Qt.Dialog | Qt.FramelessWindowHint)

        # Metadata yükle
        self._meta = load_metadata(aircraft_key)
        if self._meta is None:
            self._show_no_metadata()
            return

        self._build_ui()

    # ── No metadata ───────────────────────────────────────────────────────────

    def _show_no_metadata(self):
        lay = QVBoxLayout(self)
        lbl = QLabel(f"No metadata found for '{self._key}'.\n\n"
                     f"Expected: {self._key}.json next to this script.")
        lbl.setStyleSheet(f"color: {HL}; font-family: Consolas; font-size: 12pt;")
        lbl.setAlignment(Qt.AlignCenter)
        lay.addWidget(lbl)
        btn = QPushButton("Close")
        btn.clicked.connect(self.reject)
        lay.addWidget(btn)

    # ── UI build ──────────────────────────────────────────────────────────────

    def _build_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)

        # ── Başlık çubuğu ──────────────────────────────────────────────────
        tb = QWidget()
        tb.setFixedHeight(40)
        tb.setStyleSheet(f"background: {TB};")
        tb_lay = QHBoxLayout(tb)
        tb_lay.setContentsMargins(16, 0, 8, 0)

        title_lbl = QLabel(
            f"{self._meta.get('display_name', self._key)}  —  Switch Settings")
        title_lbl.setStyleSheet(
            f"color: {FG}; font-family: Consolas; font-size: 11pt; background: transparent;")
        tb_lay.addWidget(title_lbl)
        tb_lay.addStretch()

        cls_btn = QPushButton("✕")
        cls_btn.setFixedSize(32, 32)
        cls_btn.setStyleSheet(f"""
            QPushButton {{ background: transparent; color: {MUTED};
                          font-size: 13pt; border: none; }}
            QPushButton:hover {{ background: #3a0a0a; color: #e74c3c; }}
        """)
        cls_btn.setCursor(Qt.PointingHandCursor)
        cls_btn.clicked.connect(self.reject)
        tb_lay.addWidget(cls_btn)

        # Drag
        self._drag_pos = None
        tb.mousePressEvent  = lambda e: setattr(self, "_drag_pos",
            e.globalPos() - self.frameGeometry().topLeft()) \
            if e.button() == Qt.LeftButton else None
        tb.mouseMoveEvent   = lambda e: self.move(
            e.globalPos() - self._drag_pos) \
            if e.buttons() == Qt.LeftButton and self._drag_pos else None

        root.addWidget(tb)

        # Divider
        div = QFrame(); div.setFixedHeight(1)
        div.setStyleSheet(f"background: #2e3250;")
        root.addWidget(div)

        # ── Scroll area ────────────────────────────────────────────────────
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll.setStyleSheet(f"""
            QScrollArea {{ border: none; background: {BG}; }}
            QScrollBar:vertical {{
                background: {TB}; width: 8px; border-radius: 4px;
            }}
            QScrollBar::handle:vertical {{
                background: {MUTED}; border-radius: 4px; min-height: 20px;
            }}
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
                height: 0px;
            }}
        """)

        inner = QWidget()
        inner.setMinimumWidth(740)
        inner.setStyleSheet(f"background: {BG};")
        inner_lay = QVBoxLayout(inner)
        inner_lay.setContentsMargins(8, 12, 8, 12)
        inner_lay.setSpacing(6)

        # Kontrol kartları — discrete (switch) önce, continuous (knob) sonra, run en alta
        TYPE_ORDER = {"discrete": 0, "continuous": 1, "run": 2}
        sorted_controls = sorted(
            self._meta["controls"],
            key=lambda c: TYPE_ORDER.get(c.get("type", "run"), 2)
        )
        for ctrl in sorted_controls:
            card = ControlCard(ctrl)
            self._cards.append(card)
            inner_lay.addWidget(card)

        inner_lay.addStretch()
        scroll.setWidget(inner)
        root.addWidget(scroll)

        # Divider
        div2 = QFrame(); div2.setFixedHeight(1)
        div2.setStyleSheet(f"background: #2e3250;")
        root.addWidget(div2)

        # ── Alt butonlar ───────────────────────────────────────────────────
        bottom = QWidget()
        bottom.setStyleSheet(f"background: {TB};")
        bot_lay = QHBoxLayout(bottom)
        bot_lay.setContentsMargins(16, 10, 16, 10)
        bot_lay.setSpacing(8)

        self._status_lbl = QLabel("")
        self._status_lbl.setStyleSheet(
            f"color: {MUTED}; font-family: Consolas; font-size: 10pt; background: transparent;")
        bot_lay.addWidget(self._status_lbl)
        bot_lay.addStretch()

        for text, style, slot in [
            ("Cancel",         "secbtn", self.reject),
            ("Save and Apply", "apply",  self._save),
        ]:
            btn = QPushButton(text)
            btn.setFixedHeight(40)
            btn.setMinimumWidth(150)
            btn.setCursor(Qt.PointingHandCursor)
            if style == "apply":
                btn.setStyleSheet(f"""
                    QPushButton {{ background: {GREEN}; color: white;
                        font-family: Consolas; font-size: 12pt; font-weight: bold;
                        border: none; border-radius: 6px; padding: 0 16px; }}
                    QPushButton:hover {{ background: #43a047; }}
                    QPushButton:pressed {{ background: #1b5e20; }}
                """)
            else:
                btn.setStyleSheet(f"""
                    QPushButton {{ background: #1e2a3a; color: {FG};
                        font-family: Consolas; font-size: 12pt;
                        border: none; border-radius: 6px; padding: 0 16px; }}
                    QPushButton:hover {{ background: #243040; }}
                """)
            btn.clicked.connect(slot)
            bot_lay.addWidget(btn)

        root.addWidget(bottom)

    # ── Save ──────────────────────────────────────────────────────────────────

    def _save(self):
        try:
            self._save_impl()
        except Exception as e:
            import traceback
            tb = traceback.format_exc()
            print(f"[SAVE ERROR]\n{tb}")
            try:
                self._status(f"Error: {e}", HL)
            except Exception:
                pass

    def _save_impl(self):
        # ── Validation: tüm kartları flush et, hatalıları topla ──────────
        errors = []
        for card in self._cards:
            card.flush_to_data()
            ok, label = card.is_valid()
            if not ok:
                errors.append(label)

        if errors:
            # Hard block: hatalı switch'leri listeleyen QMessageBox
            msg = QMessageBox(self)
            msg.setWindowTitle("Cannot Save — Weight Errors")
            msg.setIcon(QMessageBox.Warning)
            style_msgbox(msg)

            detail_lines = "\n".join(f"  • {name}" for name in errors)
            msg.setText(
                "The weights for the following switches do not add up to 100 %.\n"
                "Correct them before saving.\n\n"
                + detail_lines
            )
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
            # Status bar'da da kısa özet göster
            self._status(
                f"⚠  {len(errors)} switch{'es' if len(errors) > 1 else ''} with invalid weights — not saved.",
                HL)
            return

        # ── Lua üret ─────────────────────────────────────────────────────
        print("[DEBUG _save] generate_lua baslıyor")
        lua_content = generate_lua(self._meta)
        print(f"[DEBUG _save] lua_content: {len(lua_content)} karakter")

        if self._scripts_dir:
            cr_dir    = os.path.join(self._scripts_dir, "CockpitRandomizer")
            lua_path  = os.path.join(cr_dir, f"{self._key}.lua")
            _here = os.path.dirname(os.path.abspath(__file__))
            json_path = next(
                (p for p in [
                    os.path.join(_here, f"{self._key}.json"),
                    os.path.join(_here, "CockpitRandomizer", f"{self._key}.json"),
                    os.path.join(_here, "metadata", f"{self._key}.json"),
                ] if os.path.isfile(p)),
                os.path.join(cr_dir, f"{self._key}.json")
            )
            print(f"[DEBUG _save] lua_path: {lua_path}")
            print(f"[DEBUG _save] json_path: {json_path}")
            with open(lua_path, "w", encoding="utf-8") as f:
                f.write(lua_content)
            print("[DEBUG _save] lua yazıldı")
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(self._meta, f, indent=2, ensure_ascii=False)
            print("[DEBUG _save] json yazıldı")
            self._status("Saved.", GREEN)
            QTimer.singleShot(1200, self.accept)
        else:
            print("\n" + "="*60)
            print(lua_content)
            print("="*60)
            self._status("Generated (test mode)", MUTED)

    def _status(self, msg: str, color: str = MUTED):
        self._status_lbl.setStyleSheet(
            f"color: {color}; font-family: Consolas; font-size: 10pt; background: transparent;")
        self._status_lbl.setText(msg)


# ── Standalone test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyle("Fusion")

    # Test: fa18c.json bu dosyayla aynı dizinde olmalı
    dlg = AircraftSettingsDialog("fa18c", scripts_dir=None)
    dlg.resize(620, 800)
    dlg.show()
    sys.exit(app.exec_())
