# aircraft_settings.py — CockpitRandomizer Aircraft Settings Dialog
# Prototype: JSON metadata → PyQt5 UI → .lua generator
#
# Entegrasyon notu: Bu dosya mevcut dcs-cockpit-randomizer-qt.py ile
# birlikte çalışır. AircraftRow'daki çark ikonuna tıklanınca
# AircraftSettingsDialog(key, scripts_dir, parent) çağrılır.

import sys, os, json, copy
from math import gcd
from functools import reduce
from fractions import Fraction

from PyQt5.QtWidgets import (
    QApplication, QDialog, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton, QFrame, QScrollArea, QSpinBox,
    QCheckBox, QSizePolicy, QMessageBox
)
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QFont, QColor

# ── Palette (mevcut uygulamayla aynı) ────────────────────────────────────────
BG    = "#1a1d2e"
PANEL = "#16213e"
TB    = "#0d0f1e"
HL    = "#e05c7a"
ACC   = "#2d5fa0"
FG    = "#c0c8f0"
MUTED = "#5a6080"
GREEN = "#2e7d32"
DARK  = "#0d1020"

# ── Tip renkleri ──────────────────────────────────────────────────────────────
TYPE_COLOR = {
    "discrete":   "#2d5fa0",
    "continuous": "#4a6a3a",
    "run":        "#6a4a2a",
}
TYPE_LABEL = {
    "discrete":   "SWITCH",
    "continuous": "KNOB",
    "run":        "SPECIAL",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def load_metadata(key: str) -> dict | None:
    """
    JSON metadata'yı yükler.
    Arama sırası:
      1. Bu .py dosyasıyla aynı dizinde <key>.json
      2. CockpitRandomizer/<key>.json  (Lua dosyalarıyla aynı yer)
      3. metadata/<key>.json
    """
    here = os.path.dirname(os.path.abspath(__file__))
    print(f"[DEBUG load_metadata] key={key!r}")
    print(f"[DEBUG load_metadata] here={here!r}")
    for path in [
        os.path.join(here, f"{key}.json"),
        os.path.join(here, "CockpitRandomizer", f"{key}.json"),
        os.path.join(here, "metadata", f"{key}.json"),
    ]:
        print(f"[DEBUG load_metadata] araniyor: {path!r}")
        if os.path.isfile(path):
            print(f"[DEBUG load_metadata] BULUNDU: {path!r}")
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
    print("[DEBUG load_metadata] BULUNAMADI")
    return None


def weights_to_vals(positions: list) -> list:
    """
    [{"delta": 0, "weight": 90}, {"delta": -1, "weight": 10}]
    → [0, 0, 0, 0, 0, 0, 0, 0, 0, -1]
    Fraction ile tam sayı GCD — 0.5 gibi weight'leri de destekler.
    """
    fracs = [Fraction(p["weight"]).limit_denominator(10000) for p in positions]
    denoms = [fr.denominator for fr in fracs]
    lcm_d = reduce(lambda a, b: a * b // gcd(a, b), denoms)
    ints = [int(fr * lcm_d) for fr in fracs]
    g = reduce(gcd, ints)
    result = []
    for i, p in enumerate(positions):
        result += [p["delta"]] * (ints[i] // g)
    return result


def format_delta(v) -> str:
    """Lua'da yazılacak delta değerini formatla."""
    if isinstance(v, float) and v == int(v):
        return str(int(v))
    return str(v)


def generate_lua(metadata: dict) -> str:
    """
    JSON metadata → fa18c.lua içeriği.
    run ve continuous tipler template'ten olduğu gibi gelir;
    disabled olanlar yorum satırına alınır.
    """
    lines = []
    lines.append(f'-- Generated by CockpitRandomizer GUI')
    lines.append(f'-- Aircraft: {metadata["display_name"]}')
    lines.append(f'-- DO NOT EDIT MANUALLY — use the Settings dialog\n')
    lines.append(f'CR.register("{metadata["aircraft"]}", {{')
    lines.append('')

    # Continuous kontroller için sabit vals
    CONTINUOUS_VALS = "{0, 0.25, 0.5, 0.75, 1.0}"

    for ctrl in metadata["controls"]:
        enabled = ctrl.get("enabled", True)
        t       = ctrl["type"]
        label   = ctrl["label"]
        dev     = ctrl["dev"]
        cmd     = ctrl["cmd"]
        comment = f"    -- {label}"

        if t == "run":
            run_note = ctrl.get("run_note", "")
            lua_body = ctrl.get("lua_body", "")
            cmd_str  = str(cmd) if cmd is not None else "nil"
            if not enabled:
                lines.append(f"    -- [DISABLED] {label} (dev={dev}, cmd={cmd_str})")
                if run_note:
                    lines.append(f"    -- {run_note}")
            else:
                lines.append(comment)
                if run_note:
                    lines.append(f"    -- {run_note}")
                lines.append(f"    {{")
                lines.append(f"        dev={dev}, cmd={cmd_str}, label=\"{label}\",")
                lines.append(f"        run=function(device)")
                if lua_body:
                    # Her satırı olduğu gibi yaz (girinti lua_body içinde saklı)
                    for body_line in lua_body.splitlines():
                        lines.append(body_line)
                else:
                    lines.append(f"            -- [lua_body tanımsız — bu kontrol için run() gövdesi eksik]")
                lines.append(f"        end")
                lines.append(f"    }},")
            lines.append('')

        elif t == "continuous":
            if not enabled:
                lines.append(
                    f"    -- [DISABLED] {{ dev={dev}, cmd={cmd}, "
                    f"vals={CONTINUOUS_VALS}, label=\"{label}\" }},")
            else:
                lines.append(comment)
                lines.append(
                    f"    {{ dev={dev}, cmd={cmd}, "
                    f"vals={CONTINUOUS_VALS}, label=\"{label}\" }},")
            lines.append('')

        elif t == "discrete":
            positions = ctrl.get("positions", [])
            vals = weights_to_vals(positions)
            vals_str = "{" + ", ".join(format_delta(v) for v in vals) + "}"
            # Pozisyon açıklaması
            pos_comment = " / ".join(
                f"{p['label']}={p['weight']}%{'(default)' if p.get('is_default') else ''}"
                for p in positions
            )
            if not enabled:
                lines.append(
                    f"    -- [DISABLED] {{ dev={dev}, cmd={cmd}, "
                    f"vals=..., label=\"{label}\" }},")
                lines.append(f"    -- {pos_comment}")
            else:
                lines.append(comment)
                lines.append(f"    -- {pos_comment}")
                lines.append(
                    f"    {{ dev={dev}, cmd={cmd}, "
                    f"vals={vals_str}, label=\"{label}\" }},")
            lines.append('')

    lines.append(f'}}, {metadata.get("delay", 3.0)})')
    lines.append('')
    return "\n".join(lines)


# ── Widget: tek pozisyon satırı ───────────────────────────────────────────────

class PositionRow(QWidget):
    """
    Tek bir switch pozisyonu: [LABEL]  [SpinBox %]
    Tüm pozisyonların toplamı 100 olacak şekilde otomatik güncellenir.
    """
    def __init__(self, pos_data: dict, all_rows_ref: list, is_default: bool):
        super().__init__()
        self._pos    = pos_data
        self._rows   = all_rows_ref  # kardeş satırlar (dışarıdan set edilir)
        self._updating = False

        lay = QHBoxLayout(self)
        lay.setContentsMargins(0, 2, 0, 2)
        lay.setSpacing(8)

        # Default işareti
        def_lbl = QLabel("★" if is_default else "  ")
        def_lbl.setFixedWidth(18)
        def_lbl.setStyleSheet(f"color: #f9a825; font-size: 11pt; background: transparent;")
        lay.addWidget(def_lbl)

        # Pozisyon adı
        name_lbl = QLabel(pos_data["label"])
        name_lbl.setMinimumWidth(60)
        name_lbl.setStyleSheet(f"color: {FG}; font-size: 12pt; "
                                f"font-family: Consolas; background: transparent;")
        lay.addWidget(name_lbl)

        # % spinbox + ▲▼ butonları
        self.spin = QSpinBox()
        self.spin.setRange(0, 100)
        self.spin.setValue(int(pos_data["weight"]))
        self.spin.setFixedWidth(56)
        self.spin.setFixedHeight(32)
        self.spin.setAlignment(Qt.AlignRight)
        self.spin.setStyleSheet(f"""
            QSpinBox {{
                background: {DARK};
                color: {FG};
                border: 1px solid {ACC};
                border-radius: 4px;
                font-family: Consolas;
                font-size: 12pt;
                padding: 2px 6px;
            }}
            QSpinBox::up-button   {{ width: 0px; }}
            QSpinBox::down-button {{ width: 0px; }}
        """)

        btn_style = f"""
            QPushButton {{
                background: {ACC};
                color: {FG};
                border: none;
                border-radius: 3px;
                font-size: 10pt;
                padding: 0px;
            }}
            QPushButton:hover   {{ background: #1e5799; }}
            QPushButton:pressed {{ background: #1a4a80; }}
        """
        btn_up = QPushButton("▲")
        btn_up.setFixedSize(22, 15)
        btn_up.setStyleSheet(btn_style)
        btn_up.setCursor(Qt.PointingHandCursor)
        btn_up.clicked.connect(lambda: self.spin.setValue(min(100, self.spin.value() + 1)))

        btn_dn = QPushButton("▼")
        btn_dn.setFixedSize(22, 15)
        btn_dn.setStyleSheet(btn_style)
        btn_dn.setCursor(Qt.PointingHandCursor)
        btn_dn.clicked.connect(lambda: self.spin.setValue(max(0, self.spin.value() - 1)))

        btn_col = QVBoxLayout()
        btn_col.setContentsMargins(0, 0, 0, 0)
        btn_col.setSpacing(2)
        btn_col.addWidget(btn_up)
        btn_col.addWidget(btn_dn)

        spin_grp = QHBoxLayout()
        spin_grp.setContentsMargins(0, 0, 0, 0)
        spin_grp.setSpacing(3)
        spin_grp.addWidget(self.spin)
        spin_grp.addLayout(btn_col)
        lay.addLayout(spin_grp)

        self.spin.valueChanged.connect(self._on_change)

    def _on_change(self, val):
        if self._updating:
            return
        # Sadece bu spin değiştiyse diğerlerine dokunma —
        # toplam kontrolünü parent ControlCard yapar
        self._pos["weight"] = val
        # Kardeşleri bul ve toplamı hesapla
        total = sum(r.spin.value() for r in self._rows)
        # Renk feedback
        ok = abs(total - 100) < 1
        for r in self._rows:
            r.spin.setStyleSheet(r.spin.styleSheet().replace(
                f"border: 1px solid {HL};", f"border: 1px solid {ACC};"))
        if not ok:
            self.spin.setStyleSheet(self.spin.styleSheet().replace(
                f"border: 1px solid {ACC};", f"border: 1px solid {HL};"))

    def get_weight(self) -> float:
        return self.spin.value()


# ── Widget: tek kontrol kartı ─────────────────────────────────────────────────

class ControlCard(QFrame):
    """
    Bir switch/knob/run kontrolünü temsil eden kart.
    ┌──────────────────────────────────────────────┐
    │ ☑  Master Arm Switch          [SWITCH]        │
    │    SAFE ★  [90 %]                            │
    │    ARM     [10 %]                            │
    │    toplam: 100 %                             │
    └──────────────────────────────────────────────┘
    """
    def __init__(self, ctrl: dict):
        super().__init__()
        self._ctrl = ctrl
        self._pos_rows: list[PositionRow] = []

        self.setObjectName("panel")
        self.setStyleSheet(f"QFrame#panel {{ background: {PANEL}; border-radius: 6px; }}")

        outer = QVBoxLayout(self)
        outer.setContentsMargins(10, 8, 6, 8)
        outer.setSpacing(4)

        # ── Başlık satırı ──────────────────────────────────────────────────
        top = QHBoxLayout()
        top.setSpacing(8)

        # Enable checkbox
        self.chk = QCheckBox()
        self.chk.setChecked(ctrl.get("enabled", True))
        self.chk.setStyleSheet(f"""
            QCheckBox::indicator {{
                width: 18px; height: 18px;
                border: 2px solid {MUTED};
                border-radius: 3px;
                background: {DARK};
            }}
            QCheckBox::indicator:checked {{
                background: #1b5e20;
                border: 2px solid #43a047;
                image: none;
            }}
            QCheckBox::indicator:unchecked {{
                background: #3a0a0a;
                border: 2px solid #c0392b;
                image: none;
            }}
        """)
        self.chk.stateChanged.connect(self._on_toggle)
        top.addWidget(self.chk)

        # Label
        lbl = QLabel(ctrl["label"])
        lbl.setStyleSheet(f"color: {FG}; font-size: 12pt; "
                           f"font-family: Consolas; font-weight: bold; background: transparent;")
        top.addWidget(lbl)
        top.addStretch()

        # Tip badge
        t = ctrl["type"]
        badge = QLabel(TYPE_LABEL.get(t, t.upper()))
        badge.setStyleSheet(
            f"background: {TYPE_COLOR.get(t, ACC)}; color: white; "
            f"font-size: 9pt; font-family: Consolas; font-weight: bold; "
            f"border-radius: 3px; padding: 2px 6px;")
        top.addWidget(badge)

        outer.addLayout(top)

        # ── Alt içerik ─────────────────────────────────────────────────────
        self._body = QVBoxLayout()
        self._body.setContentsMargins(26, 0, 0, 0)
        self._body.setSpacing(2)
        outer.addLayout(self._body)

        if t == "discrete":
            self._build_discrete()
        # continuous ve run: badge yeterli, ek icerik gerekmez


        self._set_body_enabled(ctrl.get("enabled", True))

    def _build_discrete(self):
        positions = self._ctrl.get("positions", [])
        # default (delta=0, "yerinde kal") sona koy — kullanici degistirmek
        # istedigi pozisyonlari uste gorur, mevcut durumu alta
        non_defaults = [p for p in positions if not p.get("is_default", False)]
        defaults     = [p for p in positions if p.get("is_default", False)]
        for pos in non_defaults + defaults:
            is_def = pos.get("is_default", False)
            row = PositionRow(pos, self._pos_rows, is_def)
            self._pos_rows.append(row)
            self._body.addWidget(row)

        # Toplam satırı
        self._total_lbl = QLabel(self._total_text())
        self._total_lbl.setStyleSheet(
            f"color: {MUTED}; font-size: 10pt; font-family: Consolas; background: transparent;")
        self._body.addWidget(self._total_lbl)

        # Her spinbox değişince toplamı güncelle
        for row in self._pos_rows:
            row.spin.valueChanged.connect(self._update_total)

    def _total_text(self) -> str:
        if not self._pos_rows:
            return ""
        total = sum(r.get_weight() for r in self._pos_rows)
        ok    = abs(total - 100) < 1
        return f"total: {int(total)} %  {'✓' if ok else '⚠ must be 100'}"

    def _update_total(self):
        if hasattr(self, "_total_lbl"):
            total = sum(r.get_weight() for r in self._pos_rows)
            ok    = abs(total - 100) < 1
            self._total_lbl.setText(self._total_text())
            self._total_lbl.setStyleSheet(
                f"color: {GREEN if ok else HL}; font-size: 10pt; "
                f"font-family: Consolas; background: transparent;")

    def _on_toggle(self, state):
        enabled = bool(state)
        self._ctrl["enabled"] = enabled
        self._set_body_enabled(enabled)

    def _set_body_enabled(self, enabled: bool):
        opacity = "1.0" if enabled else "0.4"
        for i in range(self._body.count()):
            item = self._body.itemAt(i)
            if item and item.widget():
                item.widget().setEnabled(enabled)
                item.widget().setStyleSheet(
                    item.widget().styleSheet())  # repaint

    def is_valid(self) -> tuple[bool, str]:
        """Discrete kontrolün weight toplamı 100 mü?"""
        if self._ctrl["type"] != "discrete" or not self._ctrl.get("enabled", True):
            return True, ""
        total = sum(r.get_weight() for r in self._pos_rows)
        if abs(total - 100) > 1:
            return False, f"{self._ctrl['label']}: weights sum to {int(total)}, must be 100"
        return True, ""

    def flush_to_data(self):
        """UI değerlerini ctrl dict'e yaz."""
        if self._ctrl["type"] == "discrete":
            for i, row in enumerate(self._pos_rows):
                self._ctrl["positions"][i]["weight"] = row.get_weight()


# ── Ana dialog ────────────────────────────────────────────────────────────────

class AircraftSettingsDialog(QDialog):
    """
    Bir aircraft için settings ekranı.
    Kullanım: AircraftSettingsDialog("fa18c", scripts_dir, parent).exec_()
    """
    def __init__(self, aircraft_key: str, scripts_dir: str | None = None,
                 parent=None):
        super().__init__(parent)
        self._key        = aircraft_key
        self._scripts_dir = scripts_dir
        self._cards: list[ControlCard] = []

        self.setWindowTitle(f"CockpitRandomizer — Settings")
        self.setFixedWidth(800)
        # Mantıksal piksel cinsinden ekran yüksekliği (DPI scaling dahil)
        _screen = QApplication.desktop().availableGeometry()
        _dpr    = QApplication.instance().devicePixelRatio()
        screen_h = int(_screen.height() / _dpr)
        print(f"[DEBUG dialog] screen_h(logical)={screen_h}, dpr={_dpr}")
        target_h = min(920, screen_h - 60)
        self.setMinimumHeight(400)
        self.setMaximumHeight(screen_h - 60)
        self.resize(620, target_h)
        self.resize(620, min(820, screen_h - 80))
        self.setStyleSheet(f"QDialog {{ background: {BG}; }}")
        self.setWindowFlags(Qt.Dialog | Qt.FramelessWindowHint)

        # Metadata yükle
        self._meta = load_metadata(aircraft_key)
        if self._meta is None:
            self._show_no_metadata()
            return

        self._build_ui()

    # ── No metadata ───────────────────────────────────────────────────────────

    def _show_no_metadata(self):
        lay = QVBoxLayout(self)
        lbl = QLabel(f"No metadata found for '{self._key}'.\n\n"
                     f"Expected: {self._key}.json next to this script.")
        lbl.setStyleSheet(f"color: {HL}; font-family: Consolas; font-size: 12pt;")
        lbl.setAlignment(Qt.AlignCenter)
        lay.addWidget(lbl)
        btn = QPushButton("Close")
        btn.clicked.connect(self.reject)
        lay.addWidget(btn)

    # ── UI build ──────────────────────────────────────────────────────────────

    def _build_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)

        # ── Başlık çubuğu ──────────────────────────────────────────────────
        tb = QWidget()
        tb.setFixedHeight(40)
        tb.setStyleSheet(f"background: {TB};")
        tb_lay = QHBoxLayout(tb)
        tb_lay.setContentsMargins(16, 0, 8, 0)

        title_lbl = QLabel(
            f"{self._meta.get('display_name', self._key)}  —  Switch Settings")
        title_lbl.setStyleSheet(
            f"color: {FG}; font-family: Consolas; font-size: 11pt; background: transparent;")
        tb_lay.addWidget(title_lbl)
        tb_lay.addStretch()

        cls_btn = QPushButton("✕")
        cls_btn.setFixedSize(32, 32)
        cls_btn.setStyleSheet(f"""
            QPushButton {{ background: transparent; color: {MUTED};
                          font-size: 13pt; border: none; }}
            QPushButton:hover {{ background: #3a0a0a; color: #e74c3c; }}
        """)
        cls_btn.setCursor(Qt.PointingHandCursor)
        cls_btn.clicked.connect(self.reject)
        tb_lay.addWidget(cls_btn)

        # Drag
        self._drag_pos = None
        tb.mousePressEvent  = lambda e: setattr(self, "_drag_pos",
            e.globalPos() - self.frameGeometry().topLeft()) \
            if e.button() == Qt.LeftButton else None
        tb.mouseMoveEvent   = lambda e: self.move(
            e.globalPos() - self._drag_pos) \
            if e.buttons() == Qt.LeftButton and self._drag_pos else None

        root.addWidget(tb)

        # Divider
        div = QFrame(); div.setFixedHeight(1)
        div.setStyleSheet(f"background: #2e3250;")
        root.addWidget(div)

        # ── Scroll area ────────────────────────────────────────────────────
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll.setStyleSheet(f"""
            QScrollArea {{ border: none; background: {BG}; }}
            QScrollBar:vertical {{
                background: {TB}; width: 8px; border-radius: 4px;
            }}
            QScrollBar::handle:vertical {{
                background: {MUTED}; border-radius: 4px; min-height: 20px;
            }}
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
                height: 0px;
            }}
        """)

        inner = QWidget()
        inner.setMinimumWidth(740)
        inner.setStyleSheet(f"background: {BG};")
        inner_lay = QVBoxLayout(inner)
        inner_lay.setContentsMargins(8, 12, 8, 12)
        inner_lay.setSpacing(6)

        # Kontrol kartları
        for ctrl in self._meta["controls"]:
            card = ControlCard(ctrl)
            self._cards.append(card)
            inner_lay.addWidget(card)

        inner_lay.addStretch()
        scroll.setWidget(inner)
        root.addWidget(scroll)

        # Divider
        div2 = QFrame(); div2.setFixedHeight(1)
        div2.setStyleSheet(f"background: #2e3250;")
        root.addWidget(div2)

        # ── Alt butonlar ───────────────────────────────────────────────────
        bottom = QWidget()
        bottom.setStyleSheet(f"background: {TB};")
        bot_lay = QHBoxLayout(bottom)
        bot_lay.setContentsMargins(16, 10, 16, 10)
        bot_lay.setSpacing(8)

        self._status_lbl = QLabel("")
        self._status_lbl.setStyleSheet(
            f"color: {MUTED}; font-family: Consolas; font-size: 10pt; background: transparent;")
        bot_lay.addWidget(self._status_lbl)
        bot_lay.addStretch()

        for text, style, slot in [
            ("Cancel",       "secbtn", self.reject),
            ("Save and Apply", "apply",  self._save),
        ]:
            btn = QPushButton(text)
            btn.setFixedHeight(40)
            btn.setMinimumWidth(150)
            btn.setCursor(Qt.PointingHandCursor)
            if style == "apply":
                btn.setStyleSheet(f"""
                    QPushButton {{ background: {GREEN}; color: white;
                        font-family: Consolas; font-size: 12pt; font-weight: bold;
                        border: none; border-radius: 6px; padding: 0 16px; }}
                    QPushButton:hover {{ background: #43a047; }}
                    QPushButton:pressed {{ background: #1b5e20; }}
                """)
            else:
                btn.setStyleSheet(f"""
                    QPushButton {{ background: #1e2a3a; color: {FG};
                        font-family: Consolas; font-size: 12pt;
                        border: none; border-radius: 6px; padding: 0 16px; }}
                    QPushButton:hover {{ background: #243040; }}
                """)
            btn.clicked.connect(slot)
            bot_lay.addWidget(btn)

        root.addWidget(bottom)

    # ── Save ──────────────────────────────────────────────────────────────────

    def _save(self):
        try:
            self._save_impl()
        except Exception as e:
            import traceback
            tb = traceback.format_exc()
            print(f"[SAVE ERROR]\n{tb}")
            try:
                self._status(f"Error: {e}", HL)
            except Exception:
                pass

    def _save_impl(self):
        # Validation
        errors = []
        for card in self._cards:
            card.flush_to_data()
            ok, msg = card.is_valid()
            if not ok:
                errors.append(msg)

        if errors:
            self._status(
                f"⚠  {errors[0]}" + (f" (+{len(errors)-1} more)" if len(errors) > 1 else ""),
                HL)
            return

        # Lua üret
        print("[DEBUG _save] generate_lua baslıyor")
        lua_content = generate_lua(self._meta)
        print(f"[DEBUG _save] lua_content: {len(lua_content)} karakter")

        if self._scripts_dir:
            cr_dir    = os.path.join(self._scripts_dir, "CockpitRandomizer")
            lua_path  = os.path.join(cr_dir, f"{self._key}.lua")
            _here = os.path.dirname(os.path.abspath(__file__))
            json_path = next(
                (p for p in [
                    os.path.join(_here, f"{self._key}.json"),
                    os.path.join(_here, "CockpitRandomizer", f"{self._key}.json"),
                    os.path.join(_here, "metadata", f"{self._key}.json"),
                ] if os.path.isfile(p)),
                os.path.join(cr_dir, f"{self._key}.json")
            )
            print(f"[DEBUG _save] lua_path: {lua_path}")
            print(f"[DEBUG _save] json_path: {json_path}")
            with open(lua_path, "w", encoding="utf-8") as f:
                f.write(lua_content)
            print("[DEBUG _save] lua yazıldı")
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(self._meta, f, indent=2, ensure_ascii=False)
            print("[DEBUG _save] json yazıldı")
            self._status("Saved.", GREEN)
            QTimer.singleShot(1200, self.accept)
        else:
            print("\n" + "="*60)
            print(lua_content)
            print("="*60)
            self._status("Generated (test mode)", MUTED)

    def _status(self, msg: str, color: str = MUTED):
        self._status_lbl.setStyleSheet(
            f"color: {color}; font-family: Consolas; font-size: 10pt; background: transparent;")
        self._status_lbl.setText(msg)


# ── Standalone test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyle("Fusion")

    # Test: fa18c.json bu dosyayla aynı dizinde olmalı
    dlg = AircraftSettingsDialog("fa18c", scripts_dir=None)
    dlg.resize(620, 800)
    dlg.show()
    sys.exit(app.exec_())
