-- Generated by CockpitRandomizer GUI
-- Aircraft: F/A-18C Hornet
-- DO NOT EDIT MANUALLY — use the Settings dialog

CR.register("FA-18C_hornet", {

    -- [DISABLED] { dev=10, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="OXY Flow Knob" },

    -- OBOGS Control Switch
    -- ON=4%(default) / OFF=96%
    { dev=10, cmd=3001, vals={0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="OBOGS Control Switch" },

    -- POSITION Lights Dimmer
    { dev=8, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="POSITION Lights Dimmer" },

    -- [DISABLED] { dev=8, cmd=3008, vals={0, 0.25, 0.5, 0.75, 1.0}, label="FORMATION Lights Dimmer" },

    -- LDG/TAXI LIGHT Switch
    -- OFF=69%(default) / ON=31%
    { dev=8, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, label="LDG/TAXI LIGHT Switch" },

    -- HOOK BYPASS Switch
    -- FIELD=93%(default) / CARRIER=7%
    { dev=9, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1}, label="HOOK BYPASS Switch" },

    -- CONSOLES Dimmer
    { dev=9, cmd=3011, vals={0, 0.25, 0.5, 0.75, 1.0}, label="CONSOLES Dimmer" },

    -- INST PNL Dimmer
    { dev=9, cmd=3013, vals={0, 0.25, 0.5, 0.75, 1.0}, label="INST PNL Dimmer" },

    -- FLOOD Dimmer
    { dev=9, cmd=3015, vals={0, 0.25, 0.5, 0.75, 1.0}, label="FLOOD Dimmer" },

    -- MODE Switch
    -- DAY=99%(default) / NITE=1%
    { dev=9, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="MODE Switch" },

    -- WARN/CAUTION Dimmer
    { dev=9, cmd=3023, vals={0, 0.25, 0.5, 0.75, 1.0}, label="WARN/CAUTION Dimmer" },

    -- CHART Dimmer
    { dev=9, cmd=3018, vals={0, 0.25, 0.5, 0.75, 1.0}, label="CHART Dimmer" },

    -- Anti Skid Switch
    -- ON=99%(default) / OFF=1%
    { dev=5, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Anti Skid Switch" },

    -- Altitude Switch
    -- BARO=98%(default) / RDR=2%
    { dev=34, cmd=3008, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Altitude Switch" },

    -- HUD Symbology Brightness Selector
    -- DAY=99%(default) / NIGHT=1%
    { dev=34, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.1}, label="HUD Symbology Brightness Selector" },

    -- UFC COMM 1 Volume
    { dev=25, cmd=3037, vals={0, 0.25, 0.5, 0.75, 1.0}, label="UFC COMM 1 Volume" },

    -- UFC COMM 2 Volume
    { dev=25, cmd=3039, vals={0, 0.25, 0.5, 0.75, 1.0}, label="UFC COMM 2 Volume" },

    -- Left MDI Brightness Selector
    -- DAY=99%(default) / NIGHT=1%
    { dev=35, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.1}, label="Left MDI Brightness Selector" },

    -- Right MDI Brightness Selector
    -- DAY=90%(default) / NIGHT=10%
    { dev=36, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, -0.1}, label="Right MDI Brightness Selector" },

    -- AMPCD Off/Brightness Knob
    { dev=37, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="AMPCD Off/Brightness Knob" },

    -- Master Arm Switch
    -- SAFE=99%(default) / ARM=1%
    { dev=23, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="Master Arm Switch" },

    -- Left Generator Switch
    -- NORM=90%(default) / OFF=10%
    { dev=3, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Left Generator Switch" },

    -- Right Generator Switch
    -- NORM=90%(default) / OFF=10%
    { dev=3, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Right Generator Switch" },

    -- [DISABLED] { dev=3, cmd=3020, vals=..., label="CB LAUNCH BAR" },
    -- IN=0%(default) / OPEN=100%

    -- CB SPD BRK
    -- IN=90%(default) / OPEN=10%
    { dev=3, cmd=3019, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="CB SPD BRK" },

    -- CB FCS CHAN 1
    -- IN=95%(default) / OPEN=5%
    { dev=3, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="CB FCS CHAN 1" },

    -- CB FCS CHAN 2
    -- IN=95%(default) / OPEN=5%
    { dev=3, cmd=3018, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="CB FCS CHAN 2" },

    -- CB FCS CHAN 3
    -- _EXT trigger-based. IN=no call (95%) / OUT=call (5%)
    {
        dev=3, cmd=3046, label="CB FCS CHAN 3",
        run=function(device)
            if math.random(1, 20) == 1 then
                device:performClickableAction(3046, 1)
            end
        end
    },

    -- CB FCS CHAN 4
    -- _EXT trigger-based. IN=no call (95%) / OUT=call (5%)
    {
        dev=3, cmd=3047, label="CB FCS CHAN 4",
        run=function(device)
            if math.random(1, 20) == 1 then
                device:performClickableAction(3047, 1)
            end
        end
    },

    -- CB HOOK
    -- _EXT trigger-based. IN=no call (95%) / OUT=call (5%)
    {
        dev=3, cmd=3048, label="CB HOOK",
        run=function(device)
            if math.random(1, 20) == 1 then
                device:performClickableAction(3048, 1)
            end
        end
    },

    -- CB LG
    -- _EXT trigger-based. IN=no call (95%) / OUT=call (5%)
    {
        dev=3, cmd=3049, label="CB LG",
        run=function(device)
            if math.random(1, 20) == 1 then
                device:performClickableAction(3049, 1)
            end
        end
    },

    -- External Power Switch
    -- NORM=20%(default) / OFF=80%
    { dev=3, cmd=3004, vals={0, -1, -1, -1, -1}, label="External Power Switch" },

    -- DISPENSER Switch
    -- OFF=0%(default) / ON=0% / BYPASS=100%
    { dev=54, cmd=3001, vals={-0.2}, label="DISPENSER Switch" },

    -- ECM Mode Switch
    -- OFF=6%(default) / STBY=61% / BIT=5% / REC=14% / XMIT=14%
    { dev=66, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4}, label="ECM Mode Switch" },

    -- RADAR Switch
    -- STBY=1%(default) / OFF=1% / OPR=91% / EMERG=7%
    { dev=42, cmd=3001, vals={0, -0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2}, label="RADAR Switch" },

    -- INS Switch
    -- NAV=4%(default) / GND=2% / CV=2% / OFF=1% / IFA=0% / GYRO=0% / GB=88% / TEST=3%
    { dev=44, cmd=3001, vals={0, 0, 0, 0, -0.1, -0.1, -0.2, -0.2, -0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.4, 0.4}, label="INS Switch" },

    -- FLAP Switch
    -- AUTO=87%(default) / FULL=7% / HALF=6%
    { dev=2, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1}, label="FLAP Switch" },

    -- Throttles Friction Adjusting Lever
    { dev=2, cmd=3012, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Throttles Friction Adjusting Lever" },

    -- Selective Jettison Knob
    -- SAFE=1%(default) / L FUS MSL=1% / R FUS MSL=95% / RACK/LCHR=1% / STORES=1%
    { dev=23, cmd=3011, vals={0, -0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.3}, label="Selective Jettison Knob" },

    -- Defog Handle
    { dev=11, cmd=3016, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Defog Handle" },

    -- Suit Temperature Knob
    { dev=11, cmd=3007, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Suit Temperature Knob" },

    -- Cabin Temperature Knob
    { dev=11, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Cabin Temperature Knob" },

    -- Hydraulic Isolate Override Switch
    -- NORM=90%(default) / ORIDE=10%
    { dev=4, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Hydraulic Isolate Override Switch" },

    -- External Wing Tanks Fuel Control Switch
    -- NORM=90%(default) / STOP=5% / ORIDE=5%
    { dev=6, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1}, label="External Wing Tanks Fuel Control Switch" },

    -- External Centerline Tank Fuel Control Switch
    -- NORM=90%(default) / STOP=5% / ORIDE=5%
    { dev=6, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1}, label="External Centerline Tank Fuel Control Switch" },

    -- ILS Channel Selector Switch
    -- 20-position selector. Two-call clamp+delta method required due to slow animation speed.
    {
        dev=40, cmd=3017, label="ILS Channel Selector Switch",
        run=function(device)
            local step = math.random(0, 19)
            device:performClickableAction(3017, -1.0)
            device:performClickableAction(3017, step * 0.05)
        end
    },

    -- ILS UFC/MAN Switch
    -- UFC=90%(default) / MAN=10%
    { dev=40, cmd=3016, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="ILS UFC/MAN Switch" },

    -- IFF Master Switch
    -- NORM=90%(default) / EMER=10%
    { dev=40, cmd=3012, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="IFF Master Switch" },

    -- IFF Mode 4 Switch
    -- AUD+DIS=84%(default) / DIS=7% / OFF=9%
    { dev=40, cmd=3013, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="IFF Mode 4 Switch" },

    -- TACAN Volume Knob
    { dev=40, cmd=3008, vals={0, 0.25, 0.5, 0.75, 1.0}, label="TACAN Volume Knob" },

    -- RWR Volume Control Knob
    { dev=40, cmd=3004, vals={0, 0.25, 0.5, 0.75, 1.0}, label="RWR Volume Control Knob" },

    -- MIDS A Volume Control Knob
    { dev=40, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="MIDS A Volume Control Knob" },

    -- MIDS B Volume Control Knob
    { dev=40, cmd=3007, vals={0, 0.25, 0.5, 0.75, 1.0}, label="MIDS B Volume Control Knob" },

    -- ICS Volume Control Knob
    { dev=40, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ICS Volume Control Knob" },

    -- VOX Volume Control Knob
    { dev=40, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="VOX Volume Control Knob" },

    -- AUX Volume Control Knob
    { dev=40, cmd=3009, vals={0, 0.25, 0.5, 0.75, 1.0}, label="AUX Volume Control Knob" },

    -- Shoulder Harness Control Handle
    -- LOCKED=26% / NEUTRAL=8%(default) / UNLOCKED=66%
    { dev=7, cmd=3009, vals={-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="Shoulder Harness Control Handle" },

}, 3.1)
