-- Generated by CockpitRandomizer GUI
-- Aircraft: F/A-18C Hornet
-- DO NOT EDIT MANUALLY — use the Settings dialog

CR.register("FA-18C_hornet", {

    -- Left Generator Switch
    -- NORM=100%(default) / OFF=0%
    { dev=3, cmd=3002, vals={0}, label="Left Generator Switch" },

    -- Right Generator Switch
    -- NORM=100%(default) / OFF=0%
    { dev=3, cmd=3003, vals={2}, label="Right Generator Switch" },
	
	-- CB FCS CHAN 3
    -- IN=100%(default) / OUT=0%
    { dev=3, cmd=3021, vals={1}, label="CB FCS CHAN 3" },
	
	-- CB FCS CHAN 4
    -- IN=100%(default) / OUT=0%
    { dev=3, cmd=3022, vals={1}, label="CB FCS CHAN 4" },
	
	-- CB HOOK
    -- IN=100%(default) / OUT=0%
    { dev=3, cmd=3023, vals={1}, label="CB HOOK" },
	
	-- CB LG
    -- IN=100%(default) / OUT=0%
    { dev=4, cmd=3023, vals={1}, label="CB LG" },

    -- CB FCS CHAN 1
    -- IN=100%(default) / OUT=0%
    { dev=3, cmd=3017, vals={1}, label="CB FCS CHAN 1" },

    -- CB FCS CHAN 2
    -- IN=100%(default) / OUT=0%
    { dev=3, cmd=3018, vals={1}, label="CB FCS CHAN 2" },

    -- CB SPD BRK
    -- IN=100%(default) / OUT=0%
    { dev=3, cmd=3019, vals={1}, label="CB SPD BRK" },

    -- CB LAUNCH BAR
    -- IN=100%(default) / OUT=0%
    { dev=3, cmd=3020, vals={1}, label="CB LAUNCH BAR" },
	
	-- GAIN Switch Cover
    -- OPEN=100% / CLOSE=0%(default)
    { dev=2, cmd=3005, vals={1}, label="GAIN Switch Cover" },
	
	-- Generator TIE Control Switch Cover
    -- OPEN=100% / CLOSE=0%(default)
    { dev=3, cmd=3007, vals={1}, label="Generator TIE Control Switch Cover" },

    -- Spin Recovery Switch Cover
    -- OPEN=100% / CLOSE=0%(default)
    { dev=2, cmd=3008, vals={1}, label="Spin Recovery Switch Cover" },
	
	-- COMM Relay Switch
	-- CIPHER=0% / OFF=100%(default) / PLAIN=0%
	{ dev=40, cmd=3010, vals={1}, label="COMM Relay Switch" },

	-- COMM G XMT Switch
	-- COMM 1=0% / OFF=100%(default) / COMM 2=0%
	{ dev=40, cmd=3011, vals={1}, label="COMM G XMT Switch" },

    -- FLAP Switch
    -- FULL=0%(default) / HALF=0%/ AUTO=100%
    { dev=2, cmd=3007, vals={-1}, label="FLAP Switch" },

    -- Anti Skid Switch
    -- ON=0%(default) / OFF=100%
    { dev=5, cmd=3004, vals={0}, label="Anti Skid Switch" },

    -- OBOGS Control Switch
    -- ON=100% / OFF=0%(default)
    { dev=10, cmd=3001, vals={1}, label="OBOGS Control Switch" },

    -- OXY Flow Knob
    { dev=10, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="OXY Flow Knob" },

    -- HOOK BYPASS Switch
    -- FIELD=100%(default) / CARRIER=0%
    { dev=9, cmd=3009, vals={1}, label="HOOK BYPASS Switch" },

    -- MODE Switch
    -- NVG=0% / NITE=100%(default) / DAY=0%
    { dev=9, cmd=3004, vals={1}, label="MODE Switch" },

    -- Master Arm Switch
    -- SAFE=100%(default) / ARM=0%
    { dev=23, cmd=3003, vals={0}, label="Master Arm Switch" },

    -- LDG/TAXI LIGHT Switch
    -- OFF=100%(default) / ON=0%
    { dev=8, cmd=3004, vals={0}, label="LDG/TAXI LIGHT Switch" },

    -- HUD Altitude Switch
    -- BARO=100%(default) / RDR=0%
    { dev=34, cmd=3008, vals={1}, label="HUD Altitude Switch" },

    -- HUD Symbology Brightness Selector
    -- DAY=100%(default) / NIGHT=0%
    { dev=34, cmd=3003, vals={1}, label="HUD Symbology Brightness Selector" },

    -- Left MDI Brightness Selector
    -- OFF=100%(default) / NIGHT=0% / DAY=0%
    { dev=35, cmd=3001, vals={0}, label="Left MDI Brightness Selector" },

    -- Right MDI Brightness Selector
    -- OFF=0%(default) / NIGHT=0% / DAY=100%
    { dev=36, cmd=3001, vals={0.2}, label="Right MDI Brightness Selector" },
	
	-- Shoulder Harness Control Handle
    -- LOCK=100%(default) / UNLOCK=0%
    { dev=7, cmd=3009, vals={1}, label="Shoulder Harness Control Handle" },

    -- Throttles Friction Adjusting Lever
    { dev=2, cmd=3012, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Throttles Friction Adjusting Lever" },

    -- ECM Mode Switch
    -- OFF=0%(default) / STBY=0% / BIT=0% / REC=100% / XMIT=0%
    { dev=66, cmd=3001, vals={0.3}, label="ECM Mode Switch" },

    -- DISPENSER Switch
    -- BYPASS=100%(default) / ON=0% / OFF=0%
    { dev=54, cmd=3001, vals={0.0}, label="DISPENSER Switch" },

    -- RADAR Switch
    -- OFF=0%(default) / STBY=100% / OPR=0%
    { dev=42, cmd=3001, vals={0.1}, label="RADAR Switch" },
	
	-- ENGINE ANTI-ICE Switch Switch
    -- TEST=0% / OFF=100%(default) / ON=0%
    { dev=12, cmd=3014, vals={-1}, label="ENGINE ANTI-ICE Switch" },

    -- INS Switch
    -- OFF=0%(default) / CV=0% / GND=100% / NAV=0% / IFA=0% / GYRO=0% / GB=0% / TEST=0%
    { dev=44, cmd=3001, vals={0.2}, label="INS Switch" },

    -- FLIR Switch
    -- OFF=0%(default) / STBY=100% / ON=100%
    { dev=62, cmd=3001, vals={-1}, label="FLIR Switch" },

    -- [DISABLED] { dev=62, cmd=3002, vals=..., label="LTD/R Switch" },
    -- SAFE=100%(default)
	
	-- KY-58 Mode Select
	-- P=25% / C=25% / LD=25% / RV=25%
	{ dev=41, cmd=3001, vals={0.0, 0.1, 0.2, 0.3}, label="KY-58 Mode Select" },

	-- KY-58 Fill Select
	-- Z1-5=25% / 1=25% / 2=25% / 3=25%
	{ dev=41, cmd=3002, vals={0.0, 0.1, 0.2, 0.3}, label="KY-58 Fill Select" },

	-- KY-58 Power Select
	-- OFF=100%(default) / ON=0% / TD=0%
	{ dev=41, cmd=3004, {0.1, 0.1, 0.2}, label="KY-58 Power Select" },

	-- KY-58 Volume Control
	{ dev=41, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="KY-58 Volume Control" },

    -- Defog Handle
    { dev=11, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Defog Handle" },

    -- AMPCD Off/Brightness Knob
    { dev=37, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="AMPCD Off/Brightness Knob" },

    -- TACAN Volume Knob
    { dev=40, cmd=3008, vals={0, 0.25, 0.5, 0.75, 1.0}, label="TACAN Volume Knob" },

    -- POSITION Lights Dimmer
    { dev=8, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="POSITION Lights Dimmer" },

    -- FORMATION Lights Dimmer
    { dev=8, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="FORMATION Lights Dimmer" },

    -- CONSOLES Dimmer
    { dev=9, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="CONSOLES Dimmer" },

    -- INST PNL Dimmer
    { dev=9, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="INST PNL Dimmer" },

    -- FLOOD Dimmer
    { dev=9, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="FLOOD Dimmer" },

    -- WARN/CAUTION Dimmer
    { dev=9, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="WARN/CAUTION Dimmer" },

    -- CHART Dimmer
    { dev=9, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="CHART Dimmer" },
	
	-- UFC ADF Function Select Switch
	-- 1=0% / OFF=100%(default) / 2=0%
	{ dev=25, cmd=3016, vals={1}, label="UFC ADF Function Select Switch" },

	-- HUD Symbology Reject Switch
	-- NORM=100%(default) / REJ1=0% / REJ2=0%
	{ dev=34, cmd=3001, vals={1}, label="HUD Symbology Reject Switch" },

	-- ATTITUDE Selector Switch
	-- INS=0% / AUTO=100%(default) / STBY=0%
	{ dev=34, cmd=3009, vals={1}, label="ATTITUDE Selector Switch" },

	-- HUD Video Control Switch
	-- W/B=0% / VID=0% / OFF=100%(default)
	{ dev=34, cmd=3005, vals={1}, label="HUD Video Control Switch" },

	-- UFC Brightness Control Knob
	{ dev=25, cmd=3032, vals={0, 0.25, 0.5, 0.75, 1.0}, label="UFC Brightness Control Knob" },
	
	-- IFEI Brightness Control Knob
    { dev=33, cmd=3007, vals={0, 0.25, 0.5, 0.75, 1.0}, label="IFEI Brightness Control Knob" },
	
	-- Balance Control Knob
    { dev=34, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Balance Control Knob" },

    -- COMM 1 Volume
    { dev=25, cmd=3030, vals={0, 0.25, 0.5, 0.75, 1.0}, label="COMM 1 Volume" },

    -- COMM 2 Volume
    { dev=25, cmd=3031, vals={0, 0.25, 0.5, 0.75, 1.0}, label="COMM 2 Volume" },

}, 3.0)
