-- Generated by CockpitRandomizer GUI
-- Aircraft: MiG-21bis
-- DO NOT EDIT MANUALLY — use the Settings dialog

CR.register("MiG-21Bis", {

    -- ABS Off/On
    -- ON=85%(default) / OFF=15%
    { dev=13, cmd=3117, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="ABS Off/On" },

    -- AC Generator On/Off
    -- ON=90%(default) / OFF=10%
    { dev=2, cmd=3004, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="AC Generator On/Off" },

    -- Afterburner Maximum Off/On
    -- ON=15% / OFF=85%(default)
    { dev=6, cmd=3023, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Afterburner Maximum Off/On" },

    -- Aileron Booster Off/On
    -- ON=90%(default) / OFF=10%
    { dev=44, cmd=3138, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="Aileron Booster Off/On" },

    -- Airbrake Out/In
    -- OUT=15% / IN=85%(default)
    { dev=12, cmd=3116, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Airbrake Out/In" },

    -- Anti Surge Doors Auto/Manual
    -- AUTO=90%(default) / MANUAL=10%
    { dev=6, cmd=3022, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="Anti Surge Doors Auto/Manual" },

    -- APU On/Off
    -- ON=5% / OFF=95%(default)
    { dev=3, cmd=3014, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="APU On/Off" },

    -- ARK Mode Antenna/Compass
    -- ANTENNA=70%(default) / COMPASS=30%
    { dev=24, cmd=3052, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="ARK Mode Antenna/Compass" },

    -- ARK On/Off
    -- ON=90%(default) / OFF=10%
    { dev=24, cmd=3047, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="ARK On/Off" },

    -- ARU System Manual/Auto
    -- AUTO=80%(default) / MANUAL=20%
    { dev=11, cmd=3113, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="ARU System Manual/Auto" },

    -- ASP Main Mode Manual/Auto
    -- AUTO=70%(default) / MANUAL=30%
    { dev=41, cmd=3156, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="ASP Main Mode Manual/Auto" },

    -- ASP Mode Bombardment/Shooting
    -- SHOOTING=70%(default) / BOMB=30%
    { dev=41, cmd=3157, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="ASP Mode Bombardment/Shooting" },

    -- ASP Mode Giro/Missile
    -- GIRO=70%(default) / MISSILE=30%
    { dev=41, cmd=3159, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="ASP Mode Giro/Missile" },

    -- ASP Mode Missiles-Rockets/Gun
    -- GUN=70%(default) / MISSILES=30%
    { dev=41, cmd=3158, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="ASP Mode Missiles-Rockets/Gun" },

    -- ASP Optical Sight On/Off
    -- ON=80%(default) / OFF=20%
    { dev=41, cmd=3155, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="ASP Optical Sight On/Off" },

    -- Battery Heat On/Off
    -- ON=90%(default) / OFF=10%
    { dev=1, cmd=3002, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="Battery Heat On/Off" },

    -- Battery On/Off
    -- ON=90%(default) / OFF=10%
    { dev=1, cmd=3001, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="Battery On/Off" },

    -- Brake Chute (IAB)
    -- ON=20% / OFF=80%(default)
    { dev=56, cmd=3201, vals={1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, label="Brake Chute (IAB)" },

    -- Cockpit Air Condition Off/Cold/Auto/Warm
    -- OFF=20% / COLD=20% / AUTO=40%(default) / WARM=20%
    { dev=45, cmd=3208, vals={0, 0, 0.33, 0.33, 0.66, 0.66, 0.66, 0.66, 1.0, 1.0}, label="Cockpit Air Condition Off/Cold/Auto/Warm" },

    -- DA-200 Signal Giro NPP SAU Power On/Off
    -- ON=90%(default) / OFF=10%
    { dev=21, cmd=3009, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="DA-200 Signal Giro NPP SAU Power On/Off" },

    -- DC Generator On/Off
    -- ON=90%(default) / OFF=10%
    { dev=1, cmd=3003, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="DC Generator On/Off" },

    -- Detonation Air/Ground
    -- AIR=70%(default) / GROUND=30%
    { dev=56, cmd=3202, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Detonation Air/Ground" },

    -- Drain Fuel Tank Fuel Pump
    -- ON=80%(default) / OFF=20%
    { dev=4, cmd=3012, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Drain Fuel Tank Fuel Pump" },

    -- Emergency Afterburner Off/On
    -- ON=5% / OFF=95%(default)
    { dev=6, cmd=3024, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Emergency Afterburner Off/On" },

    -- Emergency Hydraulic Pump On/Off
    -- ON=10% / OFF=90%(default)
    { dev=44, cmd=3137, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Emergency Hydraulic Pump On/Off" },

    -- Emergency Inverter
    -- ON=10% / OFF=90%(default)
    { dev=2, cmd=3007, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Emergency Inverter" },

    -- Emergency Oxygen Off/On
    -- ON=5% / OFF=95%(default)
    { dev=19, cmd=3148, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Emergency Oxygen Off/On" },

    -- Emergency Transmitter Cover
    -- OPEN=5% / CLOSED=95%(default)
    { dev=38, cmd=3210, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Emergency Transmitter Cover" },

    -- Emergency Transmitter On/Off
    -- ON=5% / OFF=95%(default)
    { dev=38, cmd=3211, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Emergency Transmitter On/Off" },

    -- Engine Cold/Normal Start
    -- NORMAL=80%(default) / COLD=20%
    { dev=3, cmd=3015, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Engine Cold/Normal Start" },

    -- Engine Emergency Air Start
    -- ON=5% / OFF=95%(default)
    { dev=3, cmd=3017, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Engine Emergency Air Start" },

    -- Engine Nozzle 2 Position Emergency Control
    -- ON=5% / OFF=95%(default)
    { dev=18, cmd=3136, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Engine Nozzle 2 Position Emergency Control" },

    -- Fire Extinguisher Off/On
    -- ON=10% / OFF=90%(default)
    { dev=53, cmd=3025, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Fire Extinguisher Off/On" },

    -- Fix Net On/Off
    -- ON=80%(default) / OFF=20%
    { dev=41, cmd=3161, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Fix Net On/Off" },

    -- Flaps Landing
    -- ON=15% / OFF=85%(default)
    { dev=15, cmd=3126, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Flaps Landing" },

    -- Flaps Neutral
    -- ON=60%(default) / OFF=40%
    { dev=15, cmd=3124, vals={1, 1, 1, 1, 1, 1, 0, 0, 0, 0}, label="Flaps Neutral" },

    -- Flaps Take-Off
    -- ON=30% / OFF=70%(default)
    { dev=15, cmd=3125, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, label="Flaps Take-Off" },

    -- Fuel Tanks 1st Group Fuel Pump
    -- ON=80%(default) / OFF=20%
    { dev=4, cmd=3011, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Fuel Tanks 1st Group Fuel Pump" },

    -- Fuel Tanks 3rd Group Fuel Pump
    -- ON=80%(default) / OFF=20%
    { dev=4, cmd=3010, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Fuel Tanks 3rd Group Fuel Pump" },

    -- Gear Up/Neutral/Down
    -- UP=10% / NEUTRAL=80%(default) / DOWN=10%
    { dev=14, cmd=3121, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Gear Up/Neutral/Down" },

    -- Giro NPP SAU RLS KPP Power On/Off
    -- ON=90%(default) / OFF=10%
    { dev=21, cmd=3008, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="Giro NPP SAU RLS KPP Power On/Off" },

    -- GS-23 Gun On/Off
    -- ON=30% / OFF=70%(default)
    { dev=42, cmd=3171, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, label="GS-23 Gun On/Off" },

    -- Guncam On/Off
    -- ON=30% / OFF=70%(default)
    { dev=42, cmd=3172, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, label="Guncam On/Off" },

    -- Harness Separation
    -- ON=5% / OFF=95%(default)
    { dev=51, cmd=3270, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Harness Separation" },

    -- Helmet Air Condition Off/On
    -- ON=85%(default) / OFF=15%
    { dev=19, cmd=3147, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Helmet Air Condition Off/On" },

    -- Helmet Heat Manual/Auto
    -- AUTO=80%(default) / MANUAL=20%
    { dev=45, cmd=3205, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Helmet Heat Manual/Auto" },

    -- Helmet Visor Off/On
    -- ON=80%(default) / OFF=20%
    { dev=45, cmd=3207, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Helmet Visor Off/On" },

    -- Hermetize Canopy
    -- ON=80%(default) / OFF=20%
    { dev=43, cmd=3150, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Hermetize Canopy" },

    -- IFF System Type 81 On/Off
    -- ON=80%(default) / OFF=20%
    { dev=38, cmd=3089, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="IFF System Type 81 On/Off" },

    -- KPP Main/Emergency
    -- MAIN=90%(default) / EMERG=10%
    { dev=28, cmd=3139, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="KPP Main/Emergency" },

    -- Landing Lights Off/Taxi/Land
    -- OFF=80%(default) / TAXI=10% / LAND=10%
    { dev=46, cmd=3333, vals={0, 0, 0, 0, 0, 0, 0, 0, 0.5, 1.0}, label="Landing Lights Off/Taxi/Land" },

    -- Locked Beam On/Off
    -- ON=20% / OFF=80%(default)
    { dev=40, cmd=3096, vals={1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, label="Locked Beam On/Off" },

    -- Low Altitude Off/Comp/On
    -- OFF=70%(default) / COMP=20% / ON=10%
    { dev=40, cmd=3095, vals={0, 0, 0, 0, 0, 0, 0, 0.5, 0.5, 1.0}, label="Low Altitude Off/Comp/On" },

    -- Marker Far/Near
    -- FAR=70%(default) / NEAR=30%
    { dev=24, cmd=3053, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Marker Far/Near" },

    -- Missiles Rockets Heat On/Off
    -- ON=30% / OFF=70%(default)
    { dev=42, cmd=3167, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, label="Missiles Rockets Heat On/Off" },

    -- Missiles Rockets Launch On/Off
    -- ON=20% / OFF=80%(default)
    { dev=42, cmd=3168, vals={1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, label="Missiles Rockets Launch On/Off" },

    -- Mixture/Oxygen
    -- OXYGEN=70%(default) / MIXTURE=30%
    { dev=19, cmd=3149, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Mixture/Oxygen" },

    -- Navigation Lights Off/Min/Med/Max
    -- OFF=60%(default) / MIN=15% / MED=15% / MAX=10%
    { dev=46, cmd=3032, vals={0, 0, 0, 0, 0, 0, 0.33, 0.33, 0.66, 1.0}, label="Navigation Lights Off/Min/Med/Max" },

    -- Nosecone Control Manual/Auto
    -- AUTO=80%(default) / MANUAL=20%
    { dev=17, cmd=3134, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Nosecone Control Manual/Auto" },

    -- Nosecone On/Off
    -- ON=85%(default) / OFF=15%
    { dev=17, cmd=3133, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Nosecone On/Off" },

    -- Nosegear Brake Off/On
    -- ON=15% / OFF=85%(default)
    { dev=13, cmd=3118, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Nosegear Brake Off/On" },

    -- NPP On/Off
    -- ON=85%(default) / OFF=15%
    { dev=23, cmd=3142, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="NPP On/Off" },

    -- Pipper On/Off
    -- ON=80%(default) / OFF=20%
    { dev=41, cmd=3160, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Pipper On/Off" },

    -- Pitot Tube Selector Main/Emergency
    -- MAIN=90%(default) / EMERG=10%
    { dev=27, cmd=3019, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="Pitot Tube Selector Main/Emergency" },

    -- Pitot Tube/Periscope/Clock Heat
    -- ON=85%(default) / OFF=15%
    { dev=27, cmd=3020, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Pitot Tube/Periscope/Clock Heat" },

    -- PO-750 Inverter #1 On/Off
    -- ON=90%(default) / OFF=10%
    { dev=2, cmd=3005, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="PO-750 Inverter #1 On/Off" },

    -- PO-750 Inverter #2 On/Off
    -- ON=90%(default) / OFF=10%
    { dev=2, cmd=3006, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="PO-750 Inverter #2 On/Off" },

    -- Pylon 1-2 Power On/Off
    -- ON=30% / OFF=70%(default)
    { dev=42, cmd=3169, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, label="Pylon 1-2 Power On/Off" },

    -- Pylon 3-4 Power On/Off
    -- ON=30% / OFF=70%(default)
    { dev=42, cmd=3170, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, label="Pylon 3-4 Power On/Off" },

    -- Radar Off/Prep/On
    -- OFF=80%(default) / PREP=15% / ON=5%
    { dev=40, cmd=3094, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1.0}, label="Radar Off/Prep/On" },

    -- Radio Altimeter/Marker On/Off
    -- ON=85%(default) / OFF=15%
    { dev=33, cmd=3145, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Radio Altimeter/Marker On/Off" },

    -- Radio System On/Off
    -- ON=90%(default) / OFF=10%
    { dev=22, cmd=3041, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="Radio System On/Off" },

    -- Radio/Compass
    -- RADIO=70%(default) / COMPASS=30%
    { dev=22, cmd=3042, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Radio/Compass" },

    -- RSBN Bearing
    -- ON=20% / OFF=80%(default)
    { dev=25, cmd=3062, vals={1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, label="RSBN Bearing" },

    -- RSBN Distance
    -- ON=20% / OFF=80%(default)
    { dev=25, cmd=3063, vals={1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, label="RSBN Distance" },

    -- RSBN Mode Land/Navigation/Descend
    -- LAND=60%(default) / NAV=30% / DESCEND=10%
    { dev=25, cmd=3055, vals={0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1.0}, label="RSBN Mode Land/Navigation/Descend" },

    -- RSBN On/Off
    -- ON=30% / OFF=70%(default)
    { dev=25, cmd=3054, vals={1, 1, 1, 0, 0, 0, 0, 0, 0, 0}, label="RSBN On/Off" },

    -- RSBN/ARK
    -- RSBN=70%(default) / ARK=30%
    { dev=25, cmd=3056, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="RSBN/ARK" },

    -- SARPP-12 Flight Data Recorder On/Off
    -- ON=90%(default) / OFF=10%
    { dev=49, cmd=3209, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="SARPP-12 Flight Data Recorder On/Off" },

    -- SAU On/Off
    -- ON=70%(default) / OFF=30%
    { dev=8, cmd=3064, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="SAU On/Off" },

    -- SAU Pitch On/Off
    -- ON=70%(default) / OFF=30%
    { dev=8, cmd=3065, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="SAU Pitch On/Off" },

    -- SAU Preset Limit Altitude
    -- ON=20% / OFF=80%(default)
    { dev=8, cmd=3069, vals={1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, label="SAU Preset Limit Altitude" },

    -- Secondary Pitot Tube Heat
    -- ON=85%(default) / OFF=15%
    { dev=27, cmd=3021, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Secondary Pitot Tube Heat" },

    -- Secure Canopy
    -- ON=80%(default) / OFF=20%
    { dev=43, cmd=3151, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Secure Canopy" },

    -- SOD IFF On/Off
    -- ON=80%(default) / OFF=20%
    { dev=39, cmd=3090, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="SOD IFF On/Off" },

    -- SOD Modes
    -- 1=40%(default) / 2=15% / 3=15% / 4=15% / 5=15%
    { dev=39, cmd=3093, vals={0, 0, 0, 0, 0.25, 0.25, 0.5, 0.5, 0.75, 1.0}, label="SOD Modes" },

    -- SOD Wave Selector 3/1/2
    -- 3=50%(default) / 1=30% / 2=20%
    { dev=39, cmd=3092, vals={0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1.0, 1.0}, label="SOD Wave Selector 3/1/2" },

    -- Special AB/Missile-Rocket-Bombs-Cannon
    -- SPECIAL=10% / NORMAL=90%(default)
    { dev=56, cmd=3200, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="Special AB/Missile-Rocket-Bombs-Cannon" },

    -- SPO-10 Night/Day
    -- DAY=70%(default) / NIGHT=30%
    { dev=37, cmd=3085, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="SPO-10 Night/Day" },

    -- SPO-10 RWR On/Off
    -- ON=90%(default) / OFF=10%
    { dev=37, cmd=3083, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 0}, label="SPO-10 RWR On/Off" },

    -- SPRD RATO Drop Cover
    -- OPEN=5% / CLOSED=95%(default)
    { dev=48, cmd=3109, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="SPRD RATO Drop Cover" },

    -- SPRD RATO Drop System On/Off
    -- ON=5% / OFF=95%(default)
    { dev=48, cmd=3107, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="SPRD RATO Drop System On/Off" },

    -- SPRD RATO Start Cover
    -- OPEN=5% / CLOSED=95%(default)
    { dev=48, cmd=3108, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="SPRD RATO Start Cover" },

    -- SPRD RATO System On/Off
    -- ON=5% / OFF=95%(default)
    { dev=48, cmd=3106, vals={1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, label="SPRD RATO System On/Off" },

    -- SPS System Off/On
    -- ON=85%(default) / OFF=15%
    { dev=10, cmd=3112, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="SPS System Off/On" },

    -- SPS-141 Continuous/Impulse
    -- CONTINUOUS=60%(default) / IMPULSE=40%
    { dev=57, cmd=3217, vals={1, 1, 1, 1, 1, 1, 0, 0, 0, 0}, label="SPS-141 Continuous/Impulse" },

    -- SPS-141 Dispenser Auto/Manual
    -- AUTO=70%(default) / MANUAL=30%
    { dev=57, cmd=3219, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="SPS-141 Dispenser Auto/Manual" },

    -- SPS-141 Off/Parallel/Full
    -- OFF=60%(default) / PARALLEL=25% / FULL=15%
    { dev=57, cmd=3220, vals={0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1.0}, label="SPS-141 Off/Parallel/Full" },

    -- SPS-141 On/Off
    -- ON=20% / OFF=80%(default)
    { dev=57, cmd=3214, vals={1, 1, 0, 0, 0, 0, 0, 0, 0, 0}, label="SPS-141 On/Off" },

    -- SPS-141 Program I/II
    -- I=60%(default) / II=40%
    { dev=57, cmd=3216, vals={1, 1, 1, 1, 1, 1, 0, 0, 0, 0}, label="SPS-141 Program I/II" },

    -- SPS-141 Transmit/Receive
    -- TRANSMIT=70%(default) / RECEIVE=30%
    { dev=57, cmd=3215, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="SPS-141 Transmit/Receive" },

    -- Squelch On/Off
    -- ON=80%(default) / OFF=20%
    { dev=22, cmd=3043, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Squelch On/Off" },

    -- SRZO IFF Coder/Decoder On/Off
    -- ON=80%(default) / OFF=20%
    { dev=38, cmd=3087, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="SRZO IFF Coder/Decoder On/Off" },

    -- Trimmer On/Off
    -- ON=85%(default) / OFF=15%
    { dev=9, cmd=3131, vals={1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="Trimmer On/Off" },

    -- UK-2M Mic Amplifier GS/KM
    -- GS=70%(default) / KM=30%
    { dev=51, cmd=3268, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="UK-2M Mic Amplifier GS/KM" },

    -- UK-2M Mic Amplifier M/L
    -- M=70%(default) / L=30%
    { dev=51, cmd=3267, vals={1, 1, 1, 1, 1, 1, 1, 0, 0, 0}, label="UK-2M Mic Amplifier M/L" },

    -- Weapon Mode Air/Ground
    -- AIR=80%(default) / GROUND=20%
    { dev=42, cmd=3183, vals={1, 1, 1, 1, 1, 1, 1, 1, 0, 0}, label="Weapon Mode Air/Ground" },

    -- Weapon Mode IR Missile/Neutral/SAR Missile
    -- NEUTRAL=60%(default) / IR MISSILE=25% / SAR MISSILE=15%
    { dev=42, cmd=3184, vals={0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1.0}, label="Weapon Mode IR Missile/Neutral/SAR Missile" },

    -- Altimeter Pressure Knob
    { dev=32, cmd=3073, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Altimeter Pressure Knob" },

    -- ARK Channel
    { dev=24, cmd=3050, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ARK Channel" },

    -- ARK Sound
    { dev=24, cmd=3048, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ARK Sound" },

    -- ARK Zone
    { dev=24, cmd=3051, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ARK Zone" },

    -- Canopy Ventilation System
    { dev=43, cmd=3272, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Canopy Ventilation System" },

    -- Cockpit Texts Back-light
    { dev=46, cmd=3231, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Cockpit Texts Back-light" },

    -- Dangerous Altitude Warning Set
    { dev=33, cmd=3146, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Dangerous Altitude Warning Set" },

    -- Fix Net Light Control
    { dev=41, cmd=3666, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Fix Net Light Control" },

    -- Fuel Quantity Set
    { dev=5, cmd=3013, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Fuel Quantity Set" },

    -- G-Suit Max/Min Valve
    { dev=51, cmd=3256, vals={0, 0.25, 0.5, 0.75, 1.0}, label="G-Suit Max/Min Valve" },

    -- Harness Loose/Tight
    { dev=51, cmd=3273, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Harness Loose/Tight" },

    -- Instruments Back-light
    { dev=46, cmd=3232, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Instruments Back-light" },

    -- Intercept Angle
    { dev=41, cmd=3663, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercept Angle" },

    -- Main Red Lights
    { dev=46, cmd=3428, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Main Red Lights" },

    -- Main White Lights
    { dev=46, cmd=3427, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Main White Lights" },

    -- Missile Seeker Sound
    { dev=42, cmd=3189, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Missile Seeker Sound" },

    -- Nosecone Manual Position Controller
    { dev=17, cmd=3135, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Nosecone Manual Position Controller" },

    -- Pipper Light Control
    { dev=41, cmd=3665, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Pipper Light Control" },

    -- PRMG Landing
    { dev=25, cmd=3060, vals={0, 0.25, 0.5, 0.75, 1.0}, label="PRMG Landing" },

    -- Radar Polar Filter
    { dev=40, cmd=3239, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Radar Polar Filter" },

    -- Radio Channel
    { dev=22, cmd=3045, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Radio Channel" },

    -- Radio Volume
    { dev=22, cmd=3044, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Radio Volume" },

    -- RSBN Navigation
    { dev=25, cmd=3059, vals={0, 0.25, 0.5, 0.75, 1.0}, label="RSBN Navigation" },

    -- RSBN Sound
    { dev=25, cmd=3058, vals={0, 0.25, 0.5, 0.75, 1.0}, label="RSBN Sound" },

    -- Scale Backlights Control
    { dev=41, cmd=3664, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Scale Backlights Control" },

    -- SPO-10 Volume
    { dev=37, cmd=3086, vals={0, 0.25, 0.5, 0.75, 1.0}, label="SPO-10 Volume" },

    -- Suit Ventilation
    { dev=51, cmd=3269, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Suit Ventilation" },

    -- Target Size
    { dev=41, cmd=3662, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Target Size" },

    -- TDC Range/Pipper Span Control
    { dev=41, cmd=3713, vals={0, 0.25, 0.5, 0.75, 1.0}, label="TDC Range/Pipper Span Control" },

    -- Throttle Fixation
    { dev=51, cmd=3274, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Throttle Fixation" },

}, 3.0)
