-- Generated by DCS Switch Randomizer (DSR)
-- Aircraft: A-10C II Tank Killer
-- DO NOT EDIT MANUALLY — use the Settings dialog

CR.register("A-10C_2", {

    -- 0.025 MHz Selector
    -- POS0=90%(default) / POS1=4% / POS2=3% / POS3=3%
    { dev=54, cmd=3006, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3}, label="0.025 MHz Selector" },

    -- 0.1 MHz Selector
    -- 0=90%(default) / 1=2% / 2=1% / 3=1% / 4=1% / 5=1% / 6=1% / 7=1% / 8=1% / 9=1%
    { dev=54, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9}, label="0.1 MHz Selector" },

    -- 1 MHz Selector
    -- 0=90%(default) / 1=2% / 2=1% / 3=1% / 4=1% / 5=1% / 6=1% / 7=1% / 8=1% / 9=1%
    { dev=54, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9}, label="1 MHz Selector" },

    -- 10 MHz Selector
    -- 0=90%(default) / 1=2% / 2=1% / 3=1% / 4=1% / 5=1% / 6=1% / 7=1% / 8=1% / 9=1%
    { dev=54, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9}, label="10 MHz Selector" },

    -- 100 MHz Selector
    -- POS0=90%(default) / POS1=5% / POS2=5%
    { dev=54, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="100 MHz Selector" },

    -- ABLE-STOW ADI Localizer Bar
    -- OFF=90%(default) / ON=10%
    { dev=46, cmd=3008, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="ABLE-STOW ADI Localizer Bar" },

    -- Accelerometer & Compass Lights
    -- OFF=90%(default) / ON=10%
    { dev=49, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Accelerometer & Compass Lights" },

    -- ADI Pitch Trim Knob
    { dev=47, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ADI Pitch Trim Knob" },

    -- Adjust Display Brightness
    { dev=5, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Adjust Display Brightness" },

    -- Adjust Display Brightness
    { dev=4, cmd=3009, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Adjust Display Brightness" },

    -- Adjust Display Brightness
    { dev=29, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Adjust Display Brightness" },

    -- Adjust RWR Volume
    { dev=5, cmd=3007, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Adjust RWR Volume" },

    -- Aerial Refueling Slipway Control Lever
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3016, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Aerial Refueling Slipway Control Lever" },

    -- Aileron Emergency Disengage
    -- LEFT=5% / OFF=90%(default) / RIGHT=5%
    { dev=38, cmd=3021, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Aileron Emergency Disengage" },

    -- AIM Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="AIM Switch" },

    -- AIM Volume
    { dev=58, cmd=3010, vals={0, 0.25, 0.5, 0.75, 1.0}, label="AIM Volume" },

    -- Air Conditioner
    -- MAN=90%(default) / AUTO=4% / COLD=3% / HOT=3%
    { dev=41, cmd=3010, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3}, label="Air Conditioner" },

    -- Altimeter Source
    -- RADAR=5% / DELTA=90%(default) / BARO=5%
    { dev=7, cmd=3005, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Altimeter Source" },

    -- [DISABLED] { dev=57, cmd=3004, vals=..., label="Altitude Above Target, 1000 ft (A-10C)" },
    -- 0=100%(default) / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100%

    -- [DISABLED] { dev=57, cmd=3003, vals=..., label="Altitude Above Target, 10000 ft" },
    -- 0=100%(default) / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100%

    -- Anti Skid
    -- OFF=90%(default) / ON=10%
    { dev=38, cmd=3028, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Anti Skid" },

    -- Anticollision Lights
    -- OFF=90%(default) / ON=10%
    { dev=49, cmd=3010, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Anticollision Lights" },

    -- APU Fire T-Handle
    -- OFF=90%(default) / ON=10%
    { dev=50, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="APU Fire T-Handle" },

    -- APU Generator On/Off
    -- OFF=90%(default) / ON=10%
    { dev=1, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="APU Generator On/Off" },

    -- APU On/Off
    -- OFF=90%(default) / ON=10%
    { dev=37, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="APU On/Off" },

    -- ARC-210, 1 MHz Selector
    -- 0=90%(default) / 1=2% / 2=1% / 3=1% / 4=1% / 5=1% / 6=1% / 7=1% / 8=1% / 9=1%
    { dev=55, cmd=3021, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9}, label="ARC-210, 1 MHz Selector" },

    -- ARC-210, 10 MHz Selector
    -- 0=90%(default) / 1=2% / 2=1% / 3=1% / 4=1% / 5=1% / 6=1% / 7=1% / 8=1% / 9=1%
    { dev=55, cmd=3023, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9}, label="ARC-210, 10 MHz Selector" },

    -- ARC-210, 100 KHz Selector
    -- 0=90%(default) / 1=2% / 2=1% / 3=1% / 4=1% / 5=1% / 6=1% / 7=1% / 8=1% / 9=1%
    { dev=55, cmd=3019, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9}, label="ARC-210, 100 KHz Selector" },

    -- ARC-210, 100 MHz Selector
    -- POS0=90%(default) / POS1=4% / POS2=3% / POS3=3%
    { dev=55, cmd=3025, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3}, label="ARC-210, 100 MHz Selector" },

    -- ARC-210, 25  KHz Selector
    -- POS0=90%(default) / POS1=4% / POS2=3% / POS3=3%
    { dev=55, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3}, label="ARC-210, 25  KHz Selector" },

    -- ARC-210, channel select knob
    { dev=55, cmd=3027, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ARC-210, channel select knob" },

    -- ARC-210, Global positioning system, NF
    -- OFF=90%(default) / TR=5% / DF=5%
    { dev=55, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="ARC-210, Global positioning system, NF" },

    -- ARC-210, lower FSK
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=55, cmd=3007, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="ARC-210, lower FSK" },

    -- [DISABLED] { dev=55, cmd=3043, vals=..., label="ARC-210, master switch" },
    -- POS0=90%(default) / POS1=5% / POS2=1% / POS3=1% / POS4=1% / POS5=1% / POS6=1%

    -- ARC-210, secondary switch
    -- ECCM MASTER=0%(default) / ECCM=100% / PRST=0% / MAN=0% / MAR=0% / 243=0% / 121 (PULL)=0%
    { dev=55, cmd=3044, vals={0.1}, label="ARC-210, secondary switch" },

    -- ARC-210, Select receiv. - transmit., NF
    -- FM=90%(default) / AM=4% / MAN=3% / PRE=3%
    { dev=55, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3}, label="ARC-210, Select receiv. - transmit., NF" },

    -- ARC-210, upper FSK
    { dev=55, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ARC-210, upper FSK" },

    -- Arm Ground Safety Override Cover
    -- OFF=90%(default) / ON=10%
    { dev=12, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Arm Ground Safety Override Cover" },

    -- Arm Ground Safety Override Switch
    -- OFF=90%(default) / ON=10%
    { dev=12, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Arm Ground Safety Override Switch" },

    -- Audio/light
    -- LIGHT=5% / OFF=90%(default) / AUDIO=5%
    { dev=43, cmd=3009, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Audio/light" },

    -- Autopilot Mode Select Switch
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=38, cmd=3001, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Autopilot Mode Select Switch" },

    -- Auxiliary Instruments Lights
    { dev=49, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Auxiliary Instruments Lights" },

    -- [DISABLED] { dev=39, cmd=3008, vals=..., label="Auxiliary Landing Gear Handle" },
    -- OFF=90%(default) / ON=10%

    -- Auxiliary Landing Gear Handle Lock button
    -- OFF=90%(default) / ON=10%
    { dev=39, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Auxiliary Landing Gear Handle Lock button" },

    -- Battery Power
    -- OFF=90%(default) / ON=10%
    { dev=1, cmd=3006, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Battery Power" },

    -- Bleed Air
    -- OFF=90%(default) / ON=10%
    { dev=41, cmd=3006, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Bleed Air" },

    -- Boost Pumps Left Wing
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Boost Pumps Left Wing" },

    -- Boost Pumps Main Fuselage Left
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Boost Pumps Main Fuselage Left" },

    -- Boost Pumps Main Fuselage Right
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3008, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Boost Pumps Main Fuselage Right" },

    -- Boost Pumps Right Wing
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3006, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Boost Pumps Right Wing" },

    -- C/RAD switch
    -- POS0=0%(default) / POS1=0% / POS2=100%
    { dev=69, cmd=3004, vals={0.2}, label="C/RAD switch" },

    -- Canopy Defog
    { dev=41, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Canopy Defog" },

    -- [DISABLED] { dev=39, cmd=3014, vals=..., label="Canopy Jettison" },
    -- OFF=90%(default) / ON=10%

    -- Canopy Jettison Lever Unlock Button
    -- OFF=90%(default) / ON=10%
    { dev=39, cmd=3015, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Canopy Jettison Lever Unlock Button" },

    -- CDU Page Select
    -- OTHER=0%(default) / POSITION=0% / STEER=100% / WAYPT=0%
    { dev=22, cmd=3004, vals={0.2}, label="CDU Page Select" },

    -- CDU Power On/Off
    -- OFF=90%(default) / ON=10%
    { dev=22, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="CDU Power On/Off" },

    -- [DISABLED] { dev=57, cmd=3005, vals=..., label="Code Wheel 1 (A-10C)" },
    -- 0=100%(default) / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100% / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100%

    -- [DISABLED] { dev=57, cmd=3006, vals=..., label="Code Wheel 2 (A-10C)" },
    -- 0=100%(default) / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100% / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100%

    -- [DISABLED] { dev=57, cmd=3007, vals=..., label="Code Wheel 3 (A-10C)" },
    -- 0=100%(default) / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100% / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100%

    -- [DISABLED] { dev=57, cmd=3008, vals=..., label="Code Wheel 4 (A-10C)" },
    -- 0=100%(default) / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100% / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100%

    -- Console Light
    { dev=49, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Console Light" },

    -- Countermeasure Dispenser (DISP)
    -- OFF=90%(default) / ON=5% / (MENU)=5%
    { dev=4, cmd=3016, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2}, label="Countermeasure Dispenser (DISP)" },

    -- Cross Feed
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Cross Feed" },

    -- Day/Night HUD Mode
    -- NIGHT=90%(default) / DAY=10%
    { dev=7, cmd=3006, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Day/Night HUD Mode" },

    -- DAY/NIGHT/OFF
    -- OFF=90%(default) / NT=5% / DAY=5%
    { dev=2, cmd=3036, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="DAY/NIGHT/OFF" },

    -- DAY/NIGHT/OFF
    -- OFF=90%(default) / NT=5% / DAY=5%
    { dev=3, cmd=3036, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="DAY/NIGHT/OFF" },

    -- Delay Switch
    -- OFF=90%(default) / ON=10%
    { dev=69, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Delay Switch" },

    -- EAC On/Off
    -- OFF=90%(default) / ON=10%
    { dev=38, cmd=3026, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="EAC On/Off" },

    -- EGI HQ TOD
    -- OFF=90%(default) / ON=10%
    { dev=54, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="EGI HQ TOD" },

    -- EGI Power On/Off
    -- OFF=90%(default) / ON=10%
    { dev=22, cmd=3006, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="EGI Power On/Off" },

    -- [DISABLED] { dev=62, cmd=3002, vals=..., label="ELECT/PNEU" },
    -- POS0=5% / POS1=90%(default) / POS2=5%

    -- Electronic Countermeasure Jammer (JMR) NF
    -- OFF=90%(default) / ON=5% / (MENU)=5%
    { dev=4, cmd=3012, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2}, label="Electronic Countermeasure Jammer (JMR) NF" },

    -- Elevator Emergency Disengage
    -- LEFT=5% / OFF=90%(default) / RIGHT=5%
    { dev=38, cmd=3022, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Elevator Emergency Disengage" },

    -- Emergency Brake
    -- OFF=90%(default) / ON=10%
    { dev=38, cmd=3030, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Emergency Brake" },

    -- Emergency Flood Light
    -- OFF=90%(default) / ON=10%
    { dev=49, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Emergency Flood Light" },

    -- Engine Instruments Lights
    { dev=49, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Engine Instruments Lights" },

    -- Engine Operate Left
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=37, cmd=3003, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Engine Operate Left" },

    -- Engine Operate Right
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=37, cmd=3004, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Engine Operate Right" },

    -- Extend boarding ladder cover
    -- OFF=90%(default) / ON=10%
    { dev=39, cmd=3011, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Extend boarding ladder cover" },

    -- External Fuselage Tank Boost Pump
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="External Fuselage Tank Boost Pump" },

    -- External Wing Tanks Boost Pumps
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="External Wing Tanks Boost Pumps" },

    -- Fire Extinguishing Agent Discharge
    -- Left=5% / Off=90%(default) / Right=5%
    { dev=50, cmd=3004, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Fire Extinguishing Agent Discharge" },

    -- Flap Setting
    -- DN=90%(default) / MVR=5% / UP=5%
    { dev=39, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 1}, label="Flap Setting" },

    -- Flaps Emergency Retract
    -- OFF=90%(default) / ON=10%
    { dev=38, cmd=3023, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Flaps Emergency Retract" },

    -- Flight Instruments Lights
    { dev=49, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Flight Instruments Lights" },

    -- Flood Light
    { dev=49, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Flood Light" },

    -- Flow Level Control
    { dev=41, cmd=3009, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Flow Level Control" },

    -- FM Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="FM Switch" },

    -- FM Volume
    { dev=58, cmd=3004, vals={0, 0.25, 0.5, 0.75, 1.0}, label="FM Volume" },

    -- Formation Lights
    { dev=49, cmd=3009, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Formation Lights" },

    -- Frequency Mode Dial
    -- MNL=5% / PRESET=90%(default) / GRD=5%
    { dev=54, cmd=3007, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Frequency Mode Dial" },

    -- Frequency Mode Dial
    -- OFF=90%(default) / TR=5% / DF=5%
    { dev=56, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="Frequency Mode Dial" },

    -- Frequency Selection Dial
    -- FM=90%(default) / AM=4% / MAN=3% / PRE=3%
    { dev=56, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3}, label="Frequency Selection Dial" },

    -- Fuel display selector
    -- POS0=90%(default) / POS1=4% / POS2=2% / POS3=2% / POS4=2%
    { dev=36, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4}, label="Fuel display selector" },

    -- Full switch
    -- POS0=90%(default) / POS1=2% / POS2=2% / POS3=2% / POS4=2% / POS5=2%
    { dev=69, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2, 0.3, 0.4, 0.5}, label="Full switch" },

    -- Function control toggle switch
    -- POS0=90%(default) / POS1=5% / POS2=5%
    { dev=73, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="Function control toggle switch" },

    -- Function Dial
    -- OFF=90%(default) / MAIN=4% / BOTH=3% / ADF=3%
    { dev=54, cmd=3008, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3}, label="Function Dial" },

    -- Gun Arm Mode
    -- GUNARM=5% / SAFE=90%(default) / ARM=5%
    { dev=7, cmd=3002, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Gun Arm Mode" },

    -- HARS Heading
    { dev=44, cmd=3007, vals={0, 0.25, 0.5, 0.75, 1.0}, label="HARS Heading" },

    -- HARS Latitude Dial
    { dev=44, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="HARS Latitude Dial" },

    -- HARS MAG VAR
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=44, cmd=3004, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="HARS MAG VAR" },

    -- HARS N/S toggle switch
    -- OFF=90%(default) / ON=10%
    { dev=44, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="HARS N/S toggle switch" },

    -- HARS SLAVE-DG mode
    -- OFF=90%(default) / ON=10%
    { dev=44, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="HARS SLAVE-DG mode" },

    -- HARS-SAS Override/NORM
    -- OFF=90%(default) / NORM=10%
    { dev=38, cmd=3031, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="HARS-SAS Override/NORM" },

    -- Hide Stick toggle
    -- OFF=90%(default) / ON=10%
    { dev=39, cmd=3016, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Hide Stick toggle" },

    -- HM Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="HM Switch" },

    -- IFF antenna switch
    -- ZERO=0%(default) / B=100% / A=0%
    { dev=43, cmd=3019, vals={0.5}, label="IFF antenna switch" },

    -- IFF On/Out
    -- OFF=90%(default) / ON=10%
    { dev=43, cmd=3016, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="IFF On/Out" },

    -- IFF Reply Dim
    { dev=43, cmd=3020, vals={0, 0.25, 0.5, 0.75, 1.0}, label="IFF Reply Dim" },

    -- IFF Switch
    -- OFF=100%(default) / ON=0%
    { dev=58, cmd=3011, vals={0}, label="IFF Switch" },

    -- IFF Volume
    { dev=58, cmd=3012, vals={0, 0.25, 0.5, 0.75, 1.0}, label="IFF Volume" },

    -- ILS Power
    -- OFF=90%(default) / ON=10%
    { dev=53, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="ILS Power" },

    -- ILS Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3013, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="ILS Switch" },

    -- ILS Volume
    { dev=53, cmd=3004, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ILS Volume" },

    -- ILS Volume
    { dev=58, cmd=3014, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ILS Volume" },

    -- INT Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="INT Switch" },

    -- INT Volume
    { dev=58, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="INT Volume" },

    -- Intercom volume
    { dev=58, cmd=3018, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom volume" },

    -- Internal canopy actuator disengage lever
    -- OFF=90%(default) / ON=10%
    { dev=39, cmd=3013, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Internal canopy actuator disengage lever" },

    -- Inverter Switch
    -- TEST=5% / OFF=90%(default) / STBY=5%
    { dev=1, cmd=3055, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Inverter Switch" },

    -- Jettison Countermeasures
    -- JTSN=10% / OFF=90%(default)
    { dev=4, cmd=3008, vals={0, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="Jettison Countermeasures" },

    -- JTRS Datalink On/Off)
    -- OFF=90%(default) / ON=10%
    { dev=7, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="JTRS Datalink On/Off)" },

    -- Land Taxi Lights
    -- TAXI=5% / OFF=90%(default) / LAND=5%
    { dev=49, cmd=3014, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Land Taxi Lights" },

    -- Landing Gear Lever
    -- DOWN=90%(default) / UP=10%
    { dev=39, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Landing Gear Lever" },

    -- Laser Arm
    -- TRAIN=5% / SAFE=90%(default) / ARM=5%
    { dev=7, cmd=3003, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Laser Arm" },

    -- Left AC Generator Power
    -- OFF=0%(default) / ON=100%
    { dev=1, cmd=3004, vals={1}, label="Left AC Generator Power" },

    -- Left Engine Fire T-Handle
    -- OFF=90%(default) / ON=10%
    { dev=50, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Left Engine Fire T-Handle" },

    -- Left Engine Fuel Flow Control
    -- OFF=90%(default) / ON=10%
    { dev=37, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Left Engine Fuel Flow Control" },

    -- Load Button Cover
    -- OFF=90%(default) / ON=10%
    { dev=54, cmd=3014, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Load Button Cover" },

    -- Main Air Supply
    -- OFF=90%(default) / ON=10%
    { dev=41, cmd=3008, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Main Air Supply" },

    -- Manual Reversion Flight Control System (MRFCS)
    -- REVERSION=100% / NORM=0%(default)
    { dev=38, cmd=3024, vals={0}, label="Manual Reversion Flight Control System (MRFCS)" },

    -- Master
    -- OFF=90%(default) / STBY=4% / LOW=2% / NORM=2% / EMER=2%
    { dev=43, cmd=3008, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4}, label="Master" },

    -- Master Arm
    -- TRAIN=5% / SAFE=90%(default) / ARM=5%
    { dev=7, cmd=3001, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Master Arm" },

    -- Master CMS Mode Select
    -- POS0=90%(default) / POS1=4% / POS2=2% / POS3=2% / POS4=2%
    { dev=4, cmd=3018, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4}, label="Master CMS Mode Select" },

    -- Missile Warning System (MWS) NF
    -- OFF=90%(default) / ON=5% / (MENU)=5%
    { dev=4, cmd=3010, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2}, label="Missile Warning System (MWS) NF" },

    -- Mode Dial
    -- POS0=0%(default) / POS1=0% / POS2=100% / POS3=0% / POS4=0%
    { dev=74, cmd=3006, vals={0.2}, label="Mode Dial" },

    -- Mode switch
    -- POS0=90%(default) / POS1=5% / POS2=5%
    { dev=69, cmd=3006, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="Mode switch" },

    -- [DISABLED] { dev=43, cmd=3001, vals=..., label="MODE1-WHEEL1" },
    -- POS0=90%(default) / POS1=4% / POS2=1% / POS3=1% / POS4=1% / POS5=1% / POS6=1% / POS7=1%

    -- [DISABLED] { dev=43, cmd=3002, vals=..., label="MODE1-WHEEL2" },
    -- POS0=90%(default) / POS1=4% / POS2=3% / POS3=3%

    -- [DISABLED] { dev=43, cmd=3003, vals=..., label="MODE3A-WHEEL1" },
    -- POS0=90%(default) / POS1=4% / POS2=1% / POS3=1% / POS4=1% / POS5=1% / POS6=1% / POS7=1%

    -- [DISABLED] { dev=43, cmd=3004, vals=..., label="MODE3A-WHEEL2" },
    -- POS0=90%(default) / POS1=4% / POS2=1% / POS3=1% / POS4=1% / POS5=1% / POS6=1% / POS7=1%

    -- [DISABLED] { dev=43, cmd=3005, vals=..., label="MODE3A-WHEEL3" },
    -- POS0=90%(default) / POS1=4% / POS2=1% / POS3=1% / POS4=1% / POS5=1% / POS6=1% / POS7=1%

    -- [DISABLED] { dev=43, cmd=3006, vals=..., label="MODE3A-WHEEL4" },
    -- POS0=90%(default) / POS1=4% / POS2=1% / POS3=1% / POS4=1% / POS5=1% / POS6=1% / POS7=1%

    -- Monitor Test Left/Right
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=38, cmd=3011, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Monitor Test Left/Right" },

    -- Nightvision Lights
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=49, cmd=3017, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Nightvision Lights" },

    -- NORM/Standby HUD Mode
    -- STBY=90%(default) / NORM=10%
    { dev=7, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="NORM/Standby HUD Mode" },

    -- Nose Illumination
    -- OFF=90%(default) / ON=10%
    { dev=49, cmd=3012, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Nose Illumination" },

    -- Oxygen Flow Emergency/Normal/Test Mask
    -- Emergency=5% / Normal=90%(default) / Test=5%
    { dev=40, cmd=3004, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Oxygen Flow Emergency/Normal/Test Mask" },

    -- Oxygen Normal/100%
    -- OFF=90%(default) / ON=10%
    { dev=40, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Oxygen Normal/100%" },

    -- Oxygen Supply On/Off
    -- OFF=90%(default) / ON=10%
    { dev=40, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Oxygen Supply On/Off" },

    -- Peak Volume
    { dev=52, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Peak Volume" },

    -- Pitch SAS Engage left
    -- OFF=90%(default) / ENGAGE=10%
    { dev=38, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Pitch SAS Engage left" },

    -- Pitch SAS Engage right
    -- OFF=90%(default) / ENGAGE=10%
    { dev=38, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Pitch SAS Engage right" },

    -- Pitch/Roll Trim Norm/Emergency Override
    -- EMER=10% / NORM=90%(default)
    { dev=38, cmd=3016, vals={0, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="Pitch/Roll Trim Norm/Emergency Override" },

    -- Pitot Heater
    -- OFF=90%(default) / ON=10%
    { dev=41, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Pitot Heater" },

    -- Position Lights, FLASH/OFF/STEADY
    -- STEADY=0% / OFF=0%(default) / FLASH=100%
    { dev=49, cmd=3008, vals={1}, label="Position Lights, FLASH/OFF/STEADY" },

    -- Power switch
    -- OFF=90%(default) / ON=10%
    { dev=69, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Power switch" },

    -- [DISABLED] { dev=54, cmd=3001, vals=..., label="Preset Channel Selector" },
    -- 0=100%(default) / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100% / 1=0% / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 0=100%

    -- Radar Altimeter Normal/Disabled
    -- OFF=90%(default) / ON=10%
    { dev=67, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Radar Altimeter Normal/Disabled" },

    -- Radar Warning Receiver (RWR)
    -- OFF=90%(default) / ON=5% / (MENU)=5%
    { dev=4, cmd=3014, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2}, label="Radar Warning Receiver (RWR)" },

    -- Refuel Status Indexer Lights
    { dev=49, cmd=3015, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Refuel Status Indexer Lights" },

    -- Refueling Lighting Dial
    { dev=49, cmd=3018, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Refueling Lighting Dial" },

    -- Right AC generator Power
    -- OFF=90%(default) / ON=10%
    { dev=1, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Right AC generator Power" },

    -- Right Engine Fire T-Handle
    -- OFF=90%(default) / ON=10%
    { dev=50, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Right Engine Fire T-Handle" },

    -- Right Engine Fuel Flow Control
    -- OFF=90%(default) / ON=10%
    { dev=37, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Right Engine Fuel Flow Control" },

    -- SAI Pitch Trim
    { dev=48, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="SAI Pitch Trim" },

    -- Scorpion HMCS Power
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=75, cmd=3001, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Scorpion HMCS Power" },

    -- Seat Adjust
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=39, cmd=3004, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Seat Adjust" },

    -- Seat Arm Handle
    -- OFF=90%(default) / ON=10%
    { dev=39, cmd=3010, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Seat Arm Handle" },

    -- Selector switch
    -- INT=0%(default) / FM=0% / VHF=0% / HF=100% / Blank=0%
    { dev=58, cmd=3019, vals={0.3}, label="Selector switch" },

    -- Set Pressure
    { dev=35, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Set Pressure" },

    -- Signal Amplifier Norm/Override
    -- NORM=90%(default) / OVERRIDE=10%
    { dev=36, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Signal Amplifier Norm/Override" },

    -- Signal Lights
    -- OFF=90%(default) / ON=10%
    { dev=49, cmd=3013, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Signal Lights" },

    -- Signal Volume
    { dev=74, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Signal Volume" },

    -- [DISABLED] { dev=57, cmd=3002, vals=..., label="Slant Range UNDER 5 - 5 - 10 (A-10C)" },
    -- 5=100% / 5=100%(default) / 10 (A-10C)=0%

    -- Speed Brake Emergency Retract
    -- OFF=90%(default) / ON=10%
    { dev=38, cmd=3015, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Speed Brake Emergency Retract" },

    -- Squelch
    -- OFF=90%(default) / ON=10%
    { dev=54, cmd=3010, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Squelch" },

    -- Squelch / TONE
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=56, cmd=3007, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Squelch / TONE" },

    -- Stall Volume
    { dev=52, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Stall Volume" },

    -- T-Tone Button
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=54, cmd=3009, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="T-Tone Button" },

    -- TACAN Channel X/Y Toggle
    -- OFF=90%(default) / ON=10%
    { dev=74, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="TACAN Channel X/Y Toggle" },

    -- Tank Gate
    -- OFF=90%(default) / ON=10%
    { dev=36, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Tank Gate" },

    -- Targeting Pod Power On/Off
    -- OFF=90%(default) / ON=10%
    { dev=7, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Targeting Pod Power On/Off" },

    -- TCN Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3015, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="TCN Switch" },

    -- TCN Volume
    { dev=58, cmd=3016, vals={0, 0.25, 0.5, 0.75, 1.0}, label="TCN Volume" },

    -- Temp Level Control
    { dev=41, cmd=3013, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Temp Level Control" },

    -- Temperature/Pressure Control
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=41, cmd=3007, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Temperature/Pressure Control" },

    -- TEST Reply Dim
    { dev=43, cmd=3021, vals={0, 0.25, 0.5, 0.75, 1.0}, label="TEST Reply Dim" },

    -- Throttle Friction Control
    { dev=37, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Throttle Friction Control" },

    -- TISL AUX Switch (A-10C)
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=57, cmd=3009, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="TISL AUX Switch (A-10C)" },

    -- TISL Mode (A-10C)
    -- POS0=90%(default) / POS1=4% / POS2=2% / POS3=2% / POS4=2%
    { dev=57, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0.2, 0.3, 0.4}, label="TISL Mode (A-10C)" },

    -- [DISABLED] { dev=0, cmd=3001, vals=..., label="Toggle Mirrors" },
    -- OFF=90%(default) / ON=10%

    -- [DISABLED] { dev=22, cmd=3003, vals=..., label="Toggle Steerpoint" },
    -- POS0=5% / POS1=90%(default) / POS2=5%

    -- Turn On/Off CICU
    -- OFF=90%(default) / ON=10%
    { dev=7, cmd=3008, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Turn On/Off CICU" },

    -- Turn On/Off/Test IFFCC
    -- OFF=90%(default) / TEST=5% / ON=5%
    { dev=7, cmd=3010, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="Turn On/Off/Test IFFCC" },

    -- UHF antenna switch
    -- POS0=90%(default) / POS1=5% / POS2=5%
    { dev=54, cmd=3016, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 1}, label="UHF antenna switch" },

    -- UHF Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="UHF Switch" },

    -- UHF Volume
    { dev=58, cmd=3008, vals={0, 0.25, 0.5, 0.75, 1.0}, label="UHF Volume" },

    -- Use Steerpoint From Active Flight Plan
    -- FLTPLAN=5% / MARK=90%(default) / MISSION=5%
    { dev=22, cmd=3001, vals={0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2}, label="Use Steerpoint From Active Flight Plan" },

    -- VHF Switch
    -- OFF=90%(default) / ON=10%
    { dev=58, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="VHF Switch" },

    -- VHF Volume
    { dev=58, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="VHF Volume" },

    -- Video selector toggle switch (N/A)
    -- POS0=90%(default) / POS1=5% / POS2=5%
    { dev=73, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2}, label="Video selector toggle switch (N/A)" },

    -- Volume
    { dev=54, cmd=3011, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Volume" },

    -- Volume
    { dev=56, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Volume" },

    -- Weapon Station Lights. No function
    { dev=49, cmd=3016, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Weapon Station Lights. No function" },

    -- Windshield Defog/Deice
    -- OFF=90%(default) / ON=10%
    { dev=41, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Windshield Defog/Deice" },

    -- Windshield Rain Removal/Wash
    -- POS0=5% / POS1=90%(default) / POS2=5%
    { dev=41, cmd=3004, vals={-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Windshield Rain Removal/Wash" },

    -- Yaw SAS Engage left
    -- OFF=90%(default) / ENGAGE=10%
    { dev=38, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Yaw SAS Engage left" },

    -- Yaw SAS Engage right
    -- OFF=90%(default) / ENGAGE=10%
    { dev=38, cmd=3005, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Yaw SAS Engage right" },

    -- Yaw Trim
    { dev=38, cmd=3013, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Yaw Trim" },

    -- Zeroise Cover
    -- OFF=90%(default) / ON=10%
    { dev=69, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Zeroise Cover" },

    -- Zeroise Switch
    -- OFF=90%(default) / ON=10%
    { dev=69, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Zeroise Switch" },

}, 3.0)
