-- Generated by DCS Switch Randomizer (DSR)
-- Aircraft: A-10C II Thunderbolt
-- DO NOT EDIT MANUALLY — use the Settings dialog

CR.register("A-10C_2", {

    -- [DISABLED] { dev=46, cmd=3008, vals=..., label="ABLE-STOW ADI Localizer Bar" },
    -- ABLE=70%(default) / STOW=30%

    -- [DISABLED] { dev=49, cmd=3004, vals=..., label="Accelerometer & Compass Lights" },
    -- ON=50% / OFF=50%(default)

    -- [DISABLED] { dev=36, cmd=3016, vals=..., label="Aerial Refueling Slipway Control" },
    -- OPEN=10% / CLOSE=90%(default)

    -- [DISABLED] { dev=7, cmd=3005, vals=..., label="Altimeter Source" },
    -- RADAR=5% / BARO=90%(default) / GPS=5%

    -- [DISABLED] { dev=38, cmd=3028, vals=..., label="Anti Skid" },
    -- ON=90%(default) / OFF=10%

    -- [DISABLED] { dev=1, cmd=3001, vals=..., label="APU Generator On/Off" },
    -- ON=10% / OFF=90%(default)

    -- [DISABLED] { dev=37, cmd=3005, vals=..., label="APU On/Off" },
    -- ON=20% / OFF=80%(default)

    -- [DISABLED] { dev=55, cmd=3043, vals=..., label="ARC-210 Master Switch" },
    -- OFF=30%(default) / TR=40% / DF=10% / RCV=10% / MAN=5% / STBY=3% / SQL=2%

    -- [DISABLED] { dev=12, cmd=3002, vals=..., label="Arm Ground Safety Override Switch Cover" },
    -- OPEN=2% / SAFE=98%(default)

    -- [DISABLED] { dev=38, cmd=3001, vals=..., label="Autopilot Mode Select" },
    -- PATH=20% / ALT/HDG=60%(default) / ALT=20%

    -- [DISABLED] { dev=1, cmd=3006, vals=..., label="Battery Power" },
    -- ON=90%(default) / OFF=10%

    -- [DISABLED] { dev=41, cmd=3006, vals=..., label="Bleed Air" },
    -- ON=85%(default) / OFF=15%

    -- [DISABLED] { dev=36, cmd=3005, vals=..., label="Boost Pumps Left Wing" },
    -- WING=85%(default) / OFF=15%

    -- [DISABLED] { dev=36, cmd=3007, vals=..., label="Boost Pumps Main Fuselage Left" },
    -- MAIN=85%(default) / OFF=15%

    -- [DISABLED] { dev=36, cmd=3008, vals=..., label="Boost Pumps Main Fuselage Right" },
    -- MAIN=85%(default) / OFF=15%

    -- [DISABLED] { dev=36, cmd=3006, vals=..., label="Boost Pumps Right Wing" },
    -- WING=85%(default) / OFF=15%

    -- [DISABLED] { dev=22, cmd=3004, vals=..., label="CDU Page Select" },
    -- OTHER=25%(default) / POSITION=25% / STEER=25% / WAYPT=25%

    -- [DISABLED] { dev=22, cmd=3005, vals=..., label="CDU Power On/Off" },
    -- ON=50% / OFF=50%(default)

    -- [DISABLED] { dev=7, cmd=3008, vals=..., label="CICU On/Off" },
    -- ON=50% / OFF=50%(default)

    -- [DISABLED] { dev=36, cmd=3004, vals=..., label="Cross Feed" },
    -- OPEN=15% / CLOSED=85%(default)

    -- [DISABLED] { dev=7, cmd=3006, vals=..., label="Day/Night HUD Mode" },
    -- DAY=60%(default) / NIGHT=40%

    -- [DISABLED] { dev=73, cmd=3001, vals=..., label="DVADR Function Control" },
    -- RECORD=20% / OFF=60%(default) / XMIT=20%

    -- [DISABLED] { dev=38, cmd=3026, vals=..., label="EAC On/Off" },
    -- ON=85%(default) / OFF=15%

    -- [DISABLED] { dev=22, cmd=3006, vals=..., label="EGI Power On/Off" },
    -- ON=50% / OFF=50%(default)

    -- [DISABLED] { dev=36, cmd=3002, vals=..., label="External Fuselage Tank Boost Pump" },
    -- BOOST=30% / OFF=70%(default)

    -- [DISABLED] { dev=36, cmd=3001, vals=..., label="External Wing Tanks Boost Pumps" },
    -- BOOST=30% / OFF=70%(default)

    -- [DISABLED] { dev=39, cmd=3002, vals=..., label="Flap Setting" },
    -- UP=50%(default) / MVR=30% / LDG=20%

    -- [DISABLED] { dev=38, cmd=3023, vals=..., label="Flaps Emergency Retract" },
    -- UP=5% / NORM=95%(default)

    -- [DISABLED] { dev=7, cmd=3002, vals=..., label="Gun Arm Mode" },
    -- ARM=5% / SAFE=90%(default) / GUNPAC=5%

    -- [DISABLED] { dev=44, cmd=3003, vals=..., label="HARS N/S Toggle" },
    -- N=80%(default) / S=20%

    -- [DISABLED] { dev=44, cmd=3002, vals=..., label="HARS SLAVE/DG Mode" },
    -- SLAVE=80%(default) / DG=20%

    -- [DISABLED] { dev=38, cmd=3031, vals=..., label="HARS-SAS Override/NORM" },
    -- NORM=90%(default) / OVERRIDE=10%

    -- [DISABLED] { dev=43, cmd=3019, vals=..., label="IFF Antenna Switch" },
    -- UPPER=0% / AUTO=0% / LOWER=100%(default)

    -- [DISABLED] { dev=53, cmd=3001, vals=..., label="ILS Frequency/Power" },
    -- ON=100% / OFF=0%(default)

    -- [DISABLED] { dev=58, cmd=3009, vals=..., label="Intercom AIM Switch" },
    -- IN=50% / OUT=50%(default)

    -- [DISABLED] { dev=58, cmd=3017, vals=..., label="Intercom HM Switch" },
    -- IN=50% / OUT=50%(default)

    -- [DISABLED] { dev=58, cmd=3011, vals=..., label="Intercom IFF Switch" },
    -- IN=50% / OUT=50%(default)

    -- [DISABLED] { dev=58, cmd=3013, vals=..., label="Intercom ILS Switch" },
    -- IN=50% / OUT=50%(default)

    -- [DISABLED] { dev=58, cmd=3001, vals=..., label="Intercom INT Switch" },
    -- IN=50% / OUT=50%(default)

    -- [DISABLED] { dev=58, cmd=3019, vals=..., label="Intercom Selector Switch" },
    -- INT=20% / FM=20% / VHF=20%(default) / HF=20% / POS 5=20%

    -- [DISABLED] { dev=58, cmd=3015, vals=..., label="Intercom TCN Switch" },
    -- IN=50% / OUT=50%(default)

    -- [DISABLED] { dev=58, cmd=3007, vals=..., label="Intercom UHF Switch" },
    -- IN=50% / OUT=50%(default)

    -- [DISABLED] { dev=4, cmd=3008, vals=..., label="Jettison Countermeasures" },
    -- JTSN=3% / OFF=97%(default)

    -- [DISABLED] { dev=7, cmd=3009, vals=..., label="JTRS Datalink On/Off" },
    -- ON=20% / OFF=80%(default)

    -- [DISABLED] { dev=69, cmd=3004, vals=..., label="KY-58 C/RAD Switch" },
    -- C/RAD 1=31% / PLAIN=46%(default) / C/RAD 2=23%

    -- [DISABLED] { dev=69, cmd=3005, vals=..., label="KY-58 Full Switch" },
    -- 1=40%(default) / 2=12% / 3=12% / 4=12% / 5=12% / 6=12%

    -- [DISABLED] { dev=69, cmd=3006, vals=..., label="KY-58 Mode Switch" },
    -- OP=80%(default) / LD=10% / RV=10%

    -- [DISABLED] { dev=69, cmd=3007, vals=..., label="KY-58 Power Switch" },
    -- ON=14% / OFF=86%(default)

    -- [DISABLED] { dev=49, cmd=3014, vals=..., label="Land Taxi Lights" },
    -- TAXI=5% / OFF=90%(default) / LDG=5%

    -- [DISABLED] { dev=39, cmd=3001, vals=..., label="Landing Gear Lever" },
    -- UP=40% / DOWN=60%(default)

    -- [DISABLED] { dev=7, cmd=3003, vals=..., label="Laser Arm" },
    -- ARM=5% / SAFE=90%(default) / OFF=5%

    -- [DISABLED] { dev=1, cmd=3004, vals=..., label="Left AC Generator Power" },
    -- ON=90%(default) / OFF=10%

    -- [DISABLED] { dev=37, cmd=3001, vals=..., label="Left Engine Fuel Flow Control" },
    -- NORM=90%(default) / OVERRIDE=10%

    -- [DISABLED] { dev=2, cmd=3036, vals=..., label="Left MFCD DAY/NIGHT/OFF" },
    -- DAY=60%(default) / NIGHT=30% / OFF=10%

    -- [DISABLED] { dev=41, cmd=3008, vals=..., label="Main Air Supply" },
    -- ON=90%(default) / OFF=10%

    -- [DISABLED] { dev=38, cmd=3024, vals=..., label="Manual Reversion Flight Control System" },
    -- MRFCS=5% / NORM=95%(default)

    -- [DISABLED] { dev=7, cmd=3001, vals=..., label="Master Arm" },
    -- ARM=2% / SAFE=96%(default) / TRAIN=2%

    -- [DISABLED] { dev=49, cmd=3017, vals=..., label="Nightvision Lights" },
    -- NORM=70%(default) / NVG=20% / OFF=10%

    -- [DISABLED] { dev=7, cmd=3007, vals=..., label="NORM/Standby HUD Mode" },
    -- NORM=90%(default) / STBY=10%

    -- [DISABLED] { dev=49, cmd=3012, vals=..., label="Nose Illumination" },
    -- ON=20% / OFF=80%(default)

    -- [DISABLED] { dev=40, cmd=3002, vals=..., label="Oxygen Normal/100%" },
    -- NORM=80%(default) / 100%=20%

    -- [DISABLED] { dev=40, cmd=3001, vals=..., label="Oxygen Supply On/Off" },
    -- ON=90%(default) / OFF=10%

    -- [DISABLED] { dev=38, cmd=3007, vals=..., label="Pitch SAS Engage Left" },
    -- ENGAGE=90%(default) / OFF=10%

    -- [DISABLED] { dev=38, cmd=3009, vals=..., label="Pitch SAS Engage Right" },
    -- ENGAGE=90%(default) / OFF=10%

    -- [DISABLED] { dev=38, cmd=3016, vals=..., label="Pitch/Roll Trim Norm/Emergency Override" },
    -- EMER=5% / NORM=95%(default)

    -- [DISABLED] { dev=41, cmd=3005, vals=..., label="Pitot Heater" },
    -- ON=85%(default) / OFF=15%

    -- [DISABLED] { dev=49, cmd=3008, vals=..., label="Position Lights FLASH/OFF/STEADY" },
    -- FLASH=20% / OFF=60%(default) / STEADY=20%

    -- [DISABLED] { dev=67, cmd=3001, vals=..., label="Radar Altimeter Normal/Disabled" },
    -- NORM=85%(default) / DISABLED=15%

    -- [DISABLED] { dev=1, cmd=3005, vals=..., label="Right AC Generator Power" },
    -- ON=90%(default) / OFF=10%

    -- [DISABLED] { dev=37, cmd=3002, vals=..., label="Right Engine Fuel Flow Control" },
    -- NORM=90%(default) / OVERRIDE=10%

    -- [DISABLED] { dev=3, cmd=3036, vals=..., label="Right MFCD DAY/NIGHT/OFF" },
    -- DAY=60%(default) / NIGHT=30% / OFF=10%

    -- [DISABLED] { dev=75, cmd=3001, vals=..., label="Scorpion HMCS Power" },
    -- ON=40% / STBY=40%(default) / OFF=20%

    -- [DISABLED] { dev=36, cmd=3009, vals=..., label="Signal Amplifier Norm/Override" },
    -- NORM=90%(default) / OVERRIDE=10%

    -- [DISABLED] { dev=49, cmd=3013, vals=..., label="Signal Lights" },
    -- ON=20% / OFF=80%(default)

    -- [DISABLED] { dev=38, cmd=3015, vals=..., label="Speed Brake Emergency Retract" },
    -- RETR=5% / NORM=95%(default)

    -- [DISABLED] { dev=22, cmd=3001, vals=..., label="Steerpoint Selector" },
    -- FLT PLAN=34%(default) / MARK=33% / MISSION=33%

    -- TACAN Mode Dial
    -- OFF=0%(default) / REC=0% / T/R=96% / A/A REC=0% / A/A T/R=4%
    { dev=74, cmd=3006, vals={0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.4}, label="TACAN Mode Dial" },

    -- [DISABLED] { dev=36, cmd=3003, vals=..., label="Tank Gate" },
    -- OPEN=20% / CLOSED=80%(default)

    -- [DISABLED] { dev=7, cmd=3004, vals=..., label="Targeting Pod Power" },
    -- ON=30% / OFF=70%(default)

    -- [DISABLED] { dev=7, cmd=3010, vals=..., label="Turn On/Off/Test IFFCC" },
    -- TEST=5% / OFF=90%(default) / ON=5%

    -- [DISABLED] { dev=54, cmd=3016, vals=..., label="UHF Antenna Switch" },
    -- UPPER=8% / AUTO=15% / LOWER=77%(default)

    -- [DISABLED] { dev=54, cmd=3007, vals=..., label="UHF Frequency Mode Dial" },
    -- MNL=34%(default) / PRESET=33% / GUARD=33%

    -- [DISABLED] { dev=54, cmd=3008, vals=..., label="UHF Function Dial" },
    -- OFF=58%(default) / MAIN=22% / BOTH=14% / ADF=6%

    -- [DISABLED] { dev=54, cmd=3010, vals=..., label="UHF Squelch" },
    -- SQUELCH=70%(default) / UNSQUELCH=30%

    -- [DISABLED] { dev=56, cmd=3003, vals=..., label="VHF FM Frequency Mode Dial" },
    -- OFF=66%(default) / TR=19% / DF=15%

    -- [DISABLED] { dev=41, cmd=3002, vals=..., label="Windshield Defog/Deice" },
    -- ON=20% / OFF=80%(default)

    -- [DISABLED] { dev=41, cmd=3004, vals=..., label="Windshield Rain Removal/Wash" },
    -- RAIN REM=15% / OFF=75%(default) / WASH=10%

    -- [DISABLED] { dev=38, cmd=3003, vals=..., label="Yaw SAS Engage Left" },
    -- ENGAGE=90%(default) / OFF=10%

    -- [DISABLED] { dev=38, cmd=3005, vals=..., label="Yaw SAS Engage Right" },
    -- ENGAGE=90%(default) / OFF=10%

    -- [DISABLED] { dev=69, cmd=3001, vals=..., label="Zeroize Cover" },
    -- OPEN=5% / CLOSE=95%(default)

    -- Auxiliary Instruments Lights
    { dev=49, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Auxiliary Instruments Lights" },

    -- Canopy Defog
    { dev=41, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Canopy Defog" },

    -- CMSC RWR Display Brightness
    { dev=5, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="CMSC RWR Display Brightness" },

    -- CMSC RWR Volume
    { dev=5, cmd=3007, vals={0, 0.25, 0.5, 0.75, 1.0}, label="CMSC RWR Volume" },

    -- CMSP Display Brightness
    { dev=4, cmd=3009, vals={0, 0.25, 0.5, 0.75, 1.0}, label="CMSP Display Brightness" },

    -- Console Light
    { dev=49, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Console Light" },

    -- Engine Instruments Lights
    { dev=49, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Engine Instruments Lights" },

    -- Flight Instruments Lights
    { dev=49, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Flight Instruments Lights" },

    -- Flood Light
    { dev=49, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Flood Light" },

    -- Flow Level Control
    { dev=41, cmd=3009, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Flow Level Control" },

    -- Formation Lights
    { dev=49, cmd=3009, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Formation Lights" },

    -- HSI Course Set Knob
    { dev=45, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="HSI Course Set Knob" },

    -- HSI Heading Set Knob
    { dev=45, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="HSI Heading Set Knob" },

    -- Intercom AIM Volume
    { dev=58, cmd=3010, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom AIM Volume" },

    -- Intercom IFF Volume
    { dev=58, cmd=3012, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom IFF Volume" },

    -- Intercom ILS Volume
    { dev=58, cmd=3014, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom ILS Volume" },

    -- Intercom INT Volume
    { dev=58, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom INT Volume" },

    -- Intercom TCN Volume
    { dev=58, cmd=3016, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom TCN Volume" },

    -- Intercom UHF Volume
    { dev=58, cmd=3008, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom UHF Volume" },

    -- Intercom Volume
    { dev=58, cmd=3018, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Intercom Volume" },

    -- Refuel Status Indexer Lights
    { dev=49, cmd=3015, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Refuel Status Indexer Lights" },

    -- Refueling Lighting Dial
    { dev=49, cmd=3018, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Refueling Lighting Dial" },

    -- RWR Display Brightness
    { dev=29, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="RWR Display Brightness" },

    -- Stall Peak Volume
    { dev=52, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Stall Peak Volume" },

    -- Stall Volume
    { dev=52, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Stall Volume" },

    -- TACAN Signal Volume
    { dev=74, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="TACAN Signal Volume" },

    -- Temp Level Control
    { dev=41, cmd=3013, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Temp Level Control" },

    -- Throttle Friction Control
    { dev=37, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Throttle Friction Control" },

    -- UHF Volume
    { dev=54, cmd=3011, vals={0, 0.25, 0.5, 0.75, 1.0}, label="UHF Volume" },

    -- VHF FM Volume
    { dev=56, cmd=3005, vals={0, 0.25, 0.5, 0.75, 1.0}, label="VHF FM Volume" },

}, 3.0)
