-- Generated by DCS Switch Randomizer (DSR)
-- Aircraft: F-14B Tomcat
-- DO NOT EDIT MANUALLY — use the Settings dialog

CR.register("F-14B", {

    -- ACM Cover
    -- CLOSED=92%(default) / OPEN=8%
    { dev=55, cmd=3133, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1}, label="ACM Cover" },

    -- AFCS Stability Augmentation - Pitch
    -- OFF=95%(default) / ON=5%
    { dev=22, cmd=3034, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="AFCS Stability Augmentation - Pitch" },

    -- AFCS Stability Augmentation - Roll
    -- OFF=95%(default) / ON=5%
    { dev=22, cmd=3035, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="AFCS Stability Augmentation - Roll" },

    -- AFCS Stability Augmentation - Yaw
    -- OFF=95%(default) / ON=5%
    { dev=22, cmd=3036, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="AFCS Stability Augmentation - Yaw" },

    -- ALR-67 Volume
    { dev=2, cmd=3398, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ALR-67 Volume" },

    -- Anti-Collision Lights
    -- OFF=90%(default) / ON=10%
    { dev=12, cmd=3177, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Anti-Collision Lights" },

    -- Anti-Skid Spoiler BK Switch
    -- BOTH=85%(default) / OFF=10% / SPOILER BK=5%
    { dev=18, cmd=3014, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2}, label="Anti-Skid Spoiler BK Switch" },

    -- Asymmetric Thrust Limiter Cover
    -- CLOSED=93%(default) / OPEN=7%
    { dev=20, cmd=3055, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1}, label="Asymmetric Thrust Limiter Cover" },

    -- Autopilot - Altitude Hold
    -- OFF=90%(default) / ON=10%
    { dev=22, cmd=3038, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Autopilot - Altitude Hold" },

    -- Autopilot - Engage
    -- OFF=90%(default) / ON=10%
    { dev=22, cmd=3041, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Autopilot - Engage" },

    -- Autopilot - Heading / Ground Track
    -- OFF=90%(default) / HDG=5% / GT=5%
    { dev=22, cmd=3039, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1}, label="Autopilot - Heading / Ground Track" },

    -- Autopilot - Vector / Automatic Carrier Landing
    -- OFF=87%(default) / VECTOR=7% / ACL=6%
    { dev=22, cmd=3037, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1}, label="Autopilot - Vector / Automatic Carrier Landing" },

    -- Console Light Intensity
    { dev=12, cmd=3180, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Console Light Intensity" },

    -- Emergency Generator Switch Cover
    -- CLOSED=90%(default) / OPEN=10%
    { dev=15, cmd=3011, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Emergency Generator Switch Cover" },

    -- Formation Light Intensity
    { dev=12, cmd=3181, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Formation Light Intensity" },

    -- Hook Bypass
    -- OFF=90%(default) / ON=10%
    { dev=12, cmd=3211, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Hook Bypass" },

    -- HSD Display Mode
    -- CENTER=87%(default) / LEFT=7% / RIGHT=6%
    { dev=41, cmd=3235, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1}, label="HSD Display Mode" },

    -- HSD/ECM Power On/Off
    -- ON=90%(default) / OFF=10%
    { dev=41, cmd=3215, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="HSD/ECM Power On/Off" },

    -- HUD AWL Mode
    -- OFF=87%(default) / ON=13%
    { dev=40, cmd=3227, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="HUD AWL Mode" },

    -- HUD Mode
    -- Take-off=12% / Cruise=12% / Air-to-Air=12% / Air-to-Ground=10% / Landing=54%(default)
    {
        dev=40, cmd=nil, label="HUD Mode",
        run=function(device)
            local cmds = {3216, 3216, 3216, 3216, 3216, 3216, 3217, 3217, 3217, 3217, 3217, 3217, 3218, 3218, 3218, 3218, 3218, 3218, 3219, 3219, 3219, 3219, 3219, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220, 3220}
            device:performClickableAction(cmds[math.random(#cmds)], 1)
        end
    },

    -- HUD Power On/Off
    -- ON=90%(default) / OFF=10%
    { dev=40, cmd=3213, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="HUD Power On/Off" },

    -- Hydraulic Emergency Flight Control Switch Cover
    -- CLOSED=90%(default) / OPEN=10%
    { dev=13, cmd=3004, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Hydraulic Emergency Flight Control Switch Cover" },

    -- Hydraulic Transfer Pump Switch Cover
    -- CLOSED=90%(default) / OPEN=10%
    { dev=13, cmd=3002, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Hydraulic Transfer Pump Switch Cover" },

    -- Instrument Light Intensity
    { dev=12, cmd=3179, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Instrument Light Intensity" },

    -- Left Engine Mode
    -- NORM=90%(default) / OFF-IDLE=10%
    { dev=20, cmd=3052, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="Left Engine Mode" },

    -- Master Arm Cover
    -- CLOSED=90%(default) / OPEN=10%
    { dev=55, cmd=3135, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Master Arm Cover" },

    -- Navigation Steer Commands
    -- TACAN=54%(default) / Destination=12% / AWL PCD=10% / Vector=12% / Manual=12%
    {
        dev=46, cmd=nil, label="Navigation Steer Commands",
        run=function(device)
            local cmds = {3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3317, 3318, 3318, 3318, 3318, 3318, 3318, 3321, 3321, 3321, 3321, 3321, 3319, 3319, 3319, 3319, 3319, 3319, 3320, 3320, 3320, 3320, 3320, 3320}
            device:performClickableAction(cmds[math.random(#cmds)], 1)
        end
    },

    -- Pilot Oxygen On
    -- ON=90%(default) / OFF=10%
    { dev=12, cmd=3190, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="Pilot Oxygen On" },

    -- Position Lights Flash
    -- OFF=87%(default) / ON=13%
    { dev=12, cmd=3176, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="Position Lights Flash" },

    -- Position Lights Tail
    -- OFF=87%(default) / DIM=9% / BRT=4%
    { dev=12, cmd=3175, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2}, label="Position Lights Tail" },

    -- Position Lights Wing
    -- OFF=87%(default) / DIM=9% / BRT=4%
    { dev=12, cmd=3174, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2}, label="Position Lights Wing" },

    -- Red Flood Light
    -- DIM=34%(default) / OFF=33% / BRT=33%
    { dev=12, cmd=3172, vals={-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="Red Flood Light" },

    -- Right Engine Mode
    -- NORM=90%(default) / OFF-IDLE=10%
    { dev=20, cmd=3053, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="Right Engine Mode" },

    -- Sidewinder Volume
    { dev=2, cmd=3400, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Sidewinder Volume" },

    -- Taxi Light
    -- OFF=87%(default) / ON=13%
    { dev=12, cmd=3171, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="Taxi Light" },

    -- UHF ARC-159 Volume Pilot
    { dev=3, cmd=3362, vals={0, 0.25, 0.5, 0.75, 1.0}, label="UHF ARC-159 Volume Pilot" },

    -- VDI Landing Mode
    -- OFF=87%(default) / ON=13%
    { dev=42, cmd=3226, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="VDI Landing Mode" },

    -- VDI Power On/Off
    -- ON=90%(default) / OFF=10%
    { dev=42, cmd=3214, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, -1}, label="VDI Power On/Off" },

    -- VHF/UHF ARC-182 Volume Pilot
    { dev=4, cmd=3406, vals={0, 0.25, 0.5, 0.75, 1.0}, label="VHF/UHF ARC-182 Volume Pilot" },

    -- White Flood Light
    -- DIM=34%(default) / OFF=33% / BRT=33%
    { dev=12, cmd=3173, vals={-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, label="White Flood Light" },

    -- Wing/Ext Trans
    -- NORM=87%(default) / WING=7% / EXT=6%
    { dev=21, cmd=3066, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1}, label="Wing/Ext Trans" },

}, 3.1)
