-- Generated by DCS Switch Randomizer (DSR)
-- Aircraft: MiG-21Bis
CR.register("MiG-21Bis", {
    -- ABS
    -- ON=0% / OFF=100%(default)
    { dev=13, cmd=3117, vals={0}, label="ABS" },

    -- AC Generator
    -- ON=0% / OFF=100%(default)
    { dev=2, cmd=3004, vals={0}, label="AC Generator" },

    -- Adjust Fuel Quantity
    { dev=5, cmd=3013, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Adjust Fuel Quantity" },

    -- Adjust Variometer
    { dev=34, cmd=3203, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Adjust Variometer" },

    -- Afterburner
    -- ON=0% / OFF=100%(default)
    { dev=6, cmd=3023, vals={0}, label="Afterburner" },

    -- Aileron Boosters
    -- ON=0% / OFF=100%(default)
    { dev=44, cmd=3138, vals={0}, label="Aileron Boosters" },

    -- Air Conditioning Select
    -- OFF=100%(default) / COLD=0% / AUTO=0% / WARM=0%
    { dev=50, cmd=3208, vals={0}, label="Air Conditioning Select" },

    -- Airbrakes
    -- ON=0% / OFF=100%(default)
    { dev=12, cmd=3116, vals={0}, label="Airbrakes" },

    -- Altimeter Pressure Knob/Gauge
    { dev=32, cmd=3073, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Altimeter Pressure Knob/Gauge" },

    -- Altitude Warning Alarm Adjust
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0%
    { dev=33, cmd=3146, vals={0}, label="Altitude Warning Alarm Adjust" },

    -- APU
    -- ON=0% / OFF=100%(default)
    { dev=3, cmd=3014, vals={0}, label="APU" },

    -- ARC
    -- ON=0% / OFF=100%(default)
    { dev=24, cmd=3047, vals={0}, label="ARC" },

    -- ARC Antenna/Compass
    -- ANTENNA=100%(default) / COMPASS=0%
    { dev=24, cmd=3052, vals={1}, label="ARC Antenna/Compass" },

    -- ARC Channel
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0%
    { dev=24, cmd=3050, vals={0.1}, label="ARC Channel" },

    -- ARC Marker Far/Near
    -- FAR=100%(default) / NEAR=0%
    { dev=24, cmd=3053, vals={1}, label="ARC Marker Far/Near" },

    -- ARC Volume
    { dev=24, cmd=3048, vals={0, 0.25, 0.5, 0.75, 1.0}, label="ARC Volume" },

    -- ARC Zones
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0%
    { dev=24, cmd=3051, vals={0}, label="ARC Zones" },

    -- ARU Auto/Manual
    -- AUTO=100%(default) / MANUAL=0%
    { dev=11, cmd=3113, vals={1}, label="ARU Auto/Manual" },

    -- Battery
    -- ON=0% / OFF=100%(default)
    { dev=1, cmd=3001, vals={0}, label="Battery" },

    -- Battery Heat
    -- ON=0% / OFF=100%(default)
    { dev=1, cmd=3002, vals={0}, label="Battery Heat" },

    -- Canopy Emergency Jettison
    -- ON=0% / OFF=100%(default)
    { dev=43, cmd=3154, vals={0}, label="Canopy Emergency Jettison" },

    -- Canopy Ventilation
    { dev=43, cmd=3272, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Canopy Ventilation" },

    -- Center Warn Lights Brightness
    { dev=47, cmd=3076, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Center Warn Lights Brightness" },

    -- Clock Left Lever Rotate
    { dev=26, cmd=3251, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Clock Left Lever Rotate" },

    -- Clock Right Lever Rotate
    { dev=26, cmd=3253, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Clock Right Lever Rotate" },

    -- DA-200 Signal, Gyro, NPP, RLS, SAU Power
    -- ON=0% / OFF=100%(default)
    { dev=21, cmd=3009, vals={0}, label="DA-200 Signal, Gyro, NPP, RLS, SAU Power" },

    -- DC Generator
    -- ON=0% / OFF=100%(default)
    { dev=1, cmd=3003, vals={0}, label="DC Generator" },

    -- Drain Fuel Pump
    -- ON=0% / OFF=100%(default)
    { dev=4, cmd=3012, vals={0}, label="Drain Fuel Pump" },

    -- Drogue Chute Drop Cover
    -- ON=0% / OFF=100%(default)
    { dev=16, cmd=3129, vals={0}, label="Drogue Chute Drop Cover" },

    -- Ejection Seat Emergency Oxygen
    -- ON=0% / OFF=100%(default)
    { dev=51, cmd=3266, vals={0}, label="Ejection Seat Emergency Oxygen" },

    -- Electrical Bus Nr. 1
    -- ON=0% / OFF=100%(default)
    { dev=51, cmd=3258, vals={0}, label="Electrical Bus Nr. 1" },

    -- Electrical Bus Nr. 1 Cover
    -- ON=0% / OFF=100%(default)
    { dev=51, cmd=3257, vals={0}, label="Electrical Bus Nr. 1 Cover" },

    -- Electrical Bus Nr. 2
    -- ON=0% / OFF=100%(default)
    { dev=51, cmd=3259, vals={0}, label="Electrical Bus Nr. 2" },

    -- Emergency Afterburner
    -- ON=0% / OFF=100%(default)
    { dev=6, cmd=3024, vals={0}, label="Emergency Afterburner" },

    -- Emergency Brake
    -- ON=0% / OFF=100%(default)
    { dev=13, cmd=3119, vals={0}, label="Emergency Brake" },

    -- Emergency Gear Release
    { dev=14, cmd=3122, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Emergency Gear Release" },

    -- Emergency Inverter
    -- ON=0% / OFF=100%(default)
    { dev=2, cmd=3007, vals={0}, label="Emergency Inverter" },

    -- Emergency Main Hydraulic Pump
    -- ON=0% / OFF=100%(default)
    { dev=44, cmd=3137, vals={0}, label="Emergency Main Hydraulic Pump" },

    -- Emergency Missile/Rocket Launch Cover
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3175, vals={0}, label="Emergency Missile/Rocket Launch Cover" },

    -- Emergency Nose Gear Release
    -- ON=0% / OFF=100%(default)
    { dev=14, cmd=3123, vals={0}, label="Emergency Nose Gear Release" },

    -- Emergency Nozzle Position Control
    -- ON=0% / OFF=100%(default)
    { dev=18, cmd=3136, vals={0}, label="Emergency Nozzle Position Control" },

    -- Emergency Oxygen
    -- ON=0% / OFF=100%(default)
    { dev=19, cmd=3148, vals={0}, label="Emergency Oxygen" },

    -- Engine Air Start
    -- ON=0% / OFF=100%(default)
    { dev=3, cmd=3017, vals={0}, label="Engine Air Start" },

    -- Engine Normal/Cold Start Select
    -- NORMAL=100%(default) / COLD=0%
    { dev=3, cmd=3015, vals={1}, label="Engine Normal/Cold Start Select" },

    -- Engine Stop/Throttle Lock
    -- ON=0% / OFF=100%(default)
    { dev=3, cmd=3238, vals={0}, label="Engine Stop/Throttle Lock" },

    -- Fire Extinguisher
    -- ON=0% / OFF=100%(default)
    { dev=53, cmd=3025, vals={0}, label="Fire Extinguisher" },

    -- Fire Extinguisher Cover
    -- ON=0% / OFF=100%(default)
    { dev=53, cmd=3026, vals={0}, label="Fire Extinguisher Cover" },

    -- Flaps Landing
    -- ON=0% / OFF=100%(default)
    { dev=15, cmd=3126, vals={0}, label="Flaps Landing" },

    -- Flaps Neutral
    -- ON=0% / OFF=100%(default)
    { dev=15, cmd=3124, vals={0}, label="Flaps Neutral" },

    -- Flaps Take-off
    -- ON=0% / OFF=100%(default)
    { dev=15, cmd=3125, vals={0}, label="Flaps Take-off" },

    -- Flight Recorder
    -- ON=0% / OFF=100%(default)
    { dev=49, cmd=3209, vals={0}, label="Flight Recorder" },

    -- Fuel Pump Group 1
    -- ON=0% / OFF=100%(default)
    { dev=4, cmd=3011, vals={0}, label="Fuel Pump Group 1" },

    -- Fuel Pump Group 3
    -- ON=0% / OFF=100%(default)
    { dev=4, cmd=3010, vals={0}, label="Fuel Pump Group 3" },

    -- Fuel Warn Lights Brightness
    { dev=47, cmd=3074, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Fuel Warn Lights Brightness" },

    -- G Suit Min/Max Valve
    { dev=51, cmd=3256, vals={0, 0.25, 0.5, 0.75, 1.0}, label="G Suit Min/Max Valve" },

    -- Gauge Backlights
    { dev=46, cmd=3232, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gauge Backlights" },

    -- Gear
    -- DOWN=100%(default) / NEUTRAL=0% / UP=0%
    { dev=14, cmd=3121, vals={-1}, label="Gear" },

    -- Gear Handle Lock
    -- ON=0% / OFF=100%(default)
    { dev=14, cmd=3120, vals={0}, label="Gear Handle Lock" },

    -- Gear Warn Lights Brightness
    { dev=47, cmd=3079, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gear Warn Lights Brightness" },

    -- GS-23 Gun
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3171, vals={0}, label="GS-23 Gun" },

    -- Gun Camera
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3172, vals={0}, label="Gun Camera" },

    -- Gunsight
    -- ON=0% / OFF=100%(default)
    { dev=41, cmd=3155, vals={0}, label="Gunsight" },

    -- Gunsight Auto/Manual
    -- AUTO=100%(default) / MANUAL=0%
    { dev=41, cmd=3156, vals={1}, label="Gunsight Auto/Manual" },

    -- Gunsight Fixed Net
    -- ON=0% / OFF=100%(default)
    { dev=41, cmd=3161, vals={0}, label="Gunsight Fixed Net" },

    -- Gunsight Fixed Net Brightness
    { dev=41, cmd=3166, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gunsight Fixed Net Brightness" },

    -- Gunsight Gun/Missile Select
    -- GUN=100%(default) / MISSILE=0%
    { dev=41, cmd=3158, vals={1}, label="Gunsight Gun/Missile Select" },

    -- Gunsight Gyro/Missile Select
    -- GYRO=100%(default) / MISSILE=0%
    { dev=41, cmd=3159, vals={1}, label="Gunsight Gyro/Missile Select" },

    -- Gunsight Intercept Angle
    { dev=41, cmd=3163, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gunsight Intercept Angle" },

    -- Gunsight Pipper
    -- ON=0% / OFF=100%(default)
    { dev=41, cmd=3160, vals={0}, label="Gunsight Pipper" },

    -- Gunsight Pipper Brightness
    { dev=41, cmd=3165, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gunsight Pipper Brightness" },

    -- Gunsight Scale Brightness
    { dev=41, cmd=3164, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gunsight Scale Brightness" },

    -- Gunsight Shoot/Bombard Select
    -- SHOOT=100%(default) / BOMBARD=0%
    { dev=41, cmd=3157, vals={1}, label="Gunsight Shoot/Bombard Select" },

    -- Gunsight Target Size
    { dev=41, cmd=3162, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gunsight Target Size" },

    -- Gyro, NPP, SAU, RLS Signal, KPP Power
    -- ON=0% / OFF=100%(default)
    { dev=21, cmd=3008, vals={0}, label="Gyro, NPP, SAU, RLS Signal, KPP Power" },

    -- Harness Loose/Tight
    { dev=51, cmd=3273, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Harness Loose/Tight" },

    -- Harness Separation
    -- ON=0% / OFF=100%(default)
    { dev=51, cmd=3270, vals={0}, label="Harness Separation" },

    -- Helmet Air Conditioning
    -- ON=0% / OFF=100%(default)
    { dev=19, cmd=3147, vals={0}, label="Helmet Air Conditioning" },

    -- Helmet Heat Auto/Manual
    -- AUTO=100%(default) / MANUAL=0%
    { dev=45, cmd=3205, vals={1}, label="Helmet Heat Auto/Manual" },

    -- Helmet Visor
    -- ON=0% / OFF=100%(default)
    { dev=45, cmd=3207, vals={0}, label="Helmet Visor" },

    -- Inboard Pylon Jettison Cover
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3181, vals={0}, label="Inboard Pylon Jettison Cover" },

    -- IR Missile Seeker Volume
    { dev=42, cmd=3189, vals={0, 0.25, 0.5, 0.75, 1.0}, label="IR Missile Seeker Volume" },

    -- IR/Neutral/SAR Missile Mode
    -- IR MISSILE=100%(default) / NEUTRAL=0% / SAR MISSILE=0%
    { dev=42, cmd=3184, vals={0}, label="IR/Neutral/SAR Missile Mode" },

    -- KPP Main/Emergency
    -- MAIN=100%(default) / EMERGENCY=0%
    { dev=28, cmd=3139, vals={1}, label="KPP Main/Emergency" },

    -- KPP Set Pitch
    { dev=28, cmd=3141, vals={0, 0.25, 0.5, 0.75, 1.0}, label="KPP Set Pitch" },

    -- Landing Lights
    -- OFF=100%(default) / TAXI=0% / LANDING=0%
    { dev=46, cmd=3033, vals={0}, label="Landing Lights" },

    -- Lock Canopy
    -- ON=0% / OFF=100%(default)
    { dev=43, cmd=3151, vals={0}, label="Lock Canopy" },

    -- Mach Test Button Cover
    -- ON=0% / OFF=100%(default)
    { dev=17, cmd=3260, vals={0}, label="Mach Test Button Cover" },

    -- Main Warn Lights Brightness
    { dev=47, cmd=3075, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Main Warn Lights Brightness" },

    -- Master Warn Light Brightness
    { dev=47, cmd=3277, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Master Warn Light Brightness" },

    -- Missile/Rocket Heat
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3167, vals={0}, label="Missile/Rocket Heat" },

    -- Missile/Rocket Launch
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3168, vals={0}, label="Missile/Rocket Launch" },

    -- Mixture/Oxygen
    -- MIXTURE=100%(default) / OXYGEN=0%
    { dev=19, cmd=3149, vals={1}, label="Mixture/Oxygen" },

    -- Nav Lights
    -- OFF=100%(default) / DIM=0% / MED=0% / BRIGHT=0%
    { dev=46, cmd=3032, vals={0}, label="Nav Lights" },

    -- Nosecone
    -- ON=0% / OFF=100%(default)
    { dev=17, cmd=3133, vals={0}, label="Nosecone" },

    -- Nosecone Auto/Manual control
    -- AUTO=100%(default) / MANUAL=0%
    { dev=17, cmd=3134, vals={1}, label="Nosecone Auto/Manual control" },

    -- Nosecone Manual Adjust
    { dev=17, cmd=3135, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Nosecone Manual Adjust" },

    -- Nosegear Brake
    -- ON=0% / OFF=100%(default)
    { dev=13, cmd=3118, vals={0}, label="Nosegear Brake" },

    -- NPP
    -- ON=0% / OFF=100%(default)
    { dev=23, cmd=3142, vals={0}, label="NPP" },

    -- NPP Course Set
    { dev=23, cmd=3144, vals={0, 0.25, 0.5, 0.75, 1.0}, label="NPP Course Set" },

    -- Nuke Air/Ground Burst
    -- AIR=100%(default) / GROUND=0%
    { dev=56, cmd=3202, vals={1}, label="Nuke Air/Ground Burst" },

    -- Nuke brake chute
    -- ON=0% / OFF=100%(default)
    { dev=56, cmd=3201, vals={0}, label="Nuke brake chute" },

    -- Nuke Emergency Jettison
    -- ON=0% / OFF=100%(default)
    { dev=56, cmd=3197, vals={0}, label="Nuke Emergency Jettison" },

    -- Nuke Emergency Jettison - ARM
    -- ON=0% / OFF=100%(default)
    { dev=56, cmd=3198, vals={0}, label="Nuke Emergency Jettison - ARM" },

    -- Nuke Tactical Drop
    -- ON=0% / OFF=100%(default)
    { dev=56, cmd=3199, vals={0}, label="Nuke Tactical Drop" },

    -- Outboard Pylon Jettison Cover
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3179, vals={0}, label="Outboard Pylon Jettison Cover" },

    -- Pitot Main/Emergency Select
    -- MAIN=100%(default) / EMERGENCY=0%
    { dev=27, cmd=3019, vals={1}, label="Pitot Main/Emergency Select" },

    -- Pitot, Clock, Periscope Heat
    -- ON=0% / OFF=100%(default)
    { dev=27, cmd=3020, vals={0}, label="Pitot, Clock, Periscope Heat" },

    -- PO-750 Inverter #1
    -- ON=0% / OFF=100%(default)
    { dev=2, cmd=3006, vals={0}, label="PO-750 Inverter #1" },

    -- PO-750 Inverter #2
    -- ON=0% / OFF=100%(default)
    { dev=2, cmd=3005, vals={0}, label="PO-750 Inverter #2" },

    -- Pressurize Canopy
    -- ON=0% / OFF=100%(default)
    { dev=43, cmd=3150, vals={0}, label="Pressurize Canopy" },

    -- PRMG Channel
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 10=0% / 11=0% / 12=0% / 13=0% / 14=0% / 15=0% / 16=0% / 17=0% / 18=0% / 19=0% / 20=0% / 21=0% / 22=0% / 23=0% / 24=0% / 25=0% / 26=0% / 27=0% / 28=0% / 29=0% / 30=0% / 31=0% / 32=0% / 33=0% / 34=0% / 35=0% / 36=0% / 37=0% / 38=0% / 39=0% / 40=0% / 41=0% / 42=0% / 43=0% / 44=0% / 45=0% / 46=0% / 47=0% / 48=0% / 49=0% / 50=0% / 51=0% / 52=0% / 53=0% / 54=0% / 55=0% / 56=0% / 57=0% / 58=0% / 59=0% / 60=0% / 61=0% / 62=0% / 63=0% / 64=0% / 65=0% / 66=0% / 67=0% / 68=0% / 69=0% / 70=0% / 71=0% / 72=0% / 73=0% / 74=0% / 75=0% / 76=0% / 77=0% / 78=0% / 79=0% / 80=0% / 81=0% / 82=0% / 83=0% / 84=0% / 85=0% / 86=0% / 87=0% / 88=0% / 89=0% / 90=0% / 91=0% / 92=0% / 93=0% / 94=0% / 95=0% / 96=0% / 97=0% / 98=0% / 99=0% / 100=0%
    { dev=25, cmd=3060, vals={0}, label="PRMG Channel" },

    -- Pylon Empty Warn Lights Brightness
    { dev=47, cmd=3077, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Pylon Empty Warn Lights Brightness" },

    -- Pylon Loaded Warn Lights Brightness
    { dev=47, cmd=3078, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Pylon Loaded Warn Lights Brightness" },

    -- Pylons 1-2
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3169, vals={0}, label="Pylons 1-2" },

    -- Pylons 3-4
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3170, vals={0}, label="Pylons 3-4" },

    -- RADAR
    -- ON=0% / STANDBY=0% / OFF=100%(default)
    { dev=40, cmd=3094, vals={1}, label="RADAR" },

    -- RADAR Emission Mode
    -- ON=0% / OFF=100%(default)
    { dev=40, cmd=3255, vals={0}, label="RADAR Emission Mode" },

    -- RADAR Emission Mode Cover
    -- ON=0% / OFF=100%(default)
    { dev=40, cmd=3254, vals={0}, label="RADAR Emission Mode Cover" },

    -- RADAR Fixed Beam
    -- ON=0% / OFF=100%(default)
    { dev=40, cmd=3096, vals={0}, label="RADAR Fixed Beam" },

    -- RADAR Low Altitude
    -- OFF=100%(default) / COMP=0% / ON=0%
    { dev=40, cmd=3095, vals={0}, label="RADAR Low Altitude" },

    -- RADAR Polar Filter
    { dev=40, cmd=3239, vals={0, 0.25, 0.5, 0.75, 1.0}, label="RADAR Polar Filter" },

    -- Radio
    -- ON=0% / OFF=100%(default)
    { dev=22, cmd=3041, vals={0}, label="Radio" },

    -- Radio Altimeter On
    -- ON=0% / OFF=100%(default)
    { dev=33, cmd=3145, vals={0}, label="Radio Altimeter On" },

    -- Radio Channel
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 10=0% / 11=0% / 12=0% / 13=0% / 14=0% / 15=0% / 16=0% / 17=0% / 18=0% / 19=0% / 20=0%
    { dev=22, cmd=3045, vals={0}, label="Radio Channel" },

    -- Radio Squelch
    -- ON=0% / OFF=100%(default)
    { dev=22, cmd=3043, vals={0}, label="Radio Squelch" },

    -- Radio Volume
    { dev=22, cmd=3044, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Radio Volume" },

    -- Radio/Compass Audio
    -- RADIO=100%(default) / COMPASS=0%
    { dev=22, cmd=3042, vals={1}, label="Radio/Compass Audio" },

    -- Red Lights
    { dev=46, cmd=3233, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Red Lights" },

    -- RSBN
    -- ON=0% / OFF=100%(default)
    { dev=25, cmd=3054, vals={0}, label="RSBN" },

    -- RSBN Bearing
    -- ON=0% / OFF=100%(default)
    { dev=25, cmd=3062, vals={0}, label="RSBN Bearing" },

    -- RSBN Channel
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 10=0% / 11=0% / 12=0% / 13=0% / 14=0% / 15=0% / 16=0% / 17=0% / 18=0% / 19=0% / 20=0% / 21=0% / 22=0% / 23=0% / 24=0% / 25=0% / 26=0% / 27=0% / 28=0% / 29=0% / 30=0% / 31=0% / 32=0% / 33=0% / 34=0% / 35=0% / 36=0% / 37=0% / 38=0% / 39=0% / 40=0% / 41=0% / 42=0% / 43=0% / 44=0% / 45=0% / 46=0% / 47=0% / 48=0% / 49=0% / 50=0% / 51=0% / 52=0% / 53=0% / 54=0% / 55=0% / 56=0% / 57=0% / 58=0% / 59=0% / 60=0% / 61=0% / 62=0% / 63=0% / 64=0% / 65=0% / 66=0% / 67=0% / 68=0% / 69=0% / 70=0% / 71=0% / 72=0% / 73=0% / 74=0% / 75=0% / 76=0% / 77=0% / 78=0% / 79=0% / 80=0% / 81=0% / 82=0% / 83=0% / 84=0% / 85=0% / 86=0% / 87=0% / 88=0% / 89=0% / 90=0% / 91=0% / 92=0% / 93=0% / 94=0% / 95=0% / 96=0% / 97=0% / 98=0% / 99=0% / 100=0%
    { dev=25, cmd=3059, vals={0}, label="RSBN Channel" },

    -- RSBN Distance
    -- ON=0% / OFF=100%(default)
    { dev=25, cmd=3063, vals={0}, label="RSBN Distance" },

    -- RSBN Mode
    -- LAND=100%(default) / NAVIGATION=0% / DESCEND=0%
    { dev=25, cmd=3055, vals={0}, label="RSBN Mode" },

    -- RSBN Volume
    { dev=25, cmd=3058, vals={0, 0.25, 0.5, 0.75, 1.0}, label="RSBN Volume" },

    -- RSBN/ARC Select
    -- RSBN=100%(default) / ARC=0%
    { dev=25, cmd=3056, vals={1}, label="RSBN/ARC Select" },

    -- SAU
    -- ON=0% / OFF=100%(default)
    { dev=8, cmd=3064, vals={0}, label="SAU" },

    -- SAU Limit Altitude
    -- ON=0% / OFF=100%(default)
    { dev=8, cmd=3069, vals={0}, label="SAU Limit Altitude" },

    -- SAU Pitch
    -- ON=0% / OFF=100%(default)
    { dev=8, cmd=3065, vals={0}, label="SAU Pitch" },

    -- Secondary Pitot Heat
    -- ON=0% / OFF=100%(default)
    { dev=27, cmd=3021, vals={0}, label="Secondary Pitot Heat" },

    -- SOD IFF
    -- ON=0% / OFF=100%(default)
    { dev=39, cmd=3090, vals={0}, label="SOD IFF" },

    -- SOD Mode Select
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0%
    { dev=39, cmd=3093, vals={0}, label="SOD Mode Select" },

    -- SOD Wave Selector
    -- 3=100%(default) / 1=0% / 2=0%
    { dev=39, cmd=3092, vals={0}, label="SOD Wave Selector" },

    -- SPO
    -- ON=0% / OFF=100%(default)
    { dev=37, cmd=3083, vals={0}, label="SPO" },

    -- SPO Day/Night
    -- DAY=100%(default) / NIGHT=0%
    { dev=37, cmd=3085, vals={1}, label="SPO Day/Night" },

    -- SPO Volume
    { dev=37, cmd=3086, vals={0, 0.25, 0.5, 0.75, 1.0}, label="SPO Volume" },

    -- SPRD
    -- ON=0% / OFF=100%(default)
    { dev=48, cmd=3106, vals={0}, label="SPRD" },

    -- SPRD Drop System
    -- ON=0% / OFF=100%(default)
    { dev=48, cmd=3107, vals={0}, label="SPRD Drop System" },

    -- SPRD Start Cover
    -- ON=0% / OFF=100%(default)
    { dev=48, cmd=3108, vals={0}, label="SPRD Start Cover" },

    -- SPRD/Flare Drop Cover
    -- ON=0% / OFF=100%(default)
    { dev=48, cmd=3109, vals={0}, label="SPRD/Flare Drop Cover" },

    -- SPS System
    -- ON=0% / OFF=100%(default)
    { dev=10, cmd=3112, vals={0}, label="SPS System" },

    -- SPS-141-100
    -- ON=0% / OFF=100%(default)
    { dev=57, cmd=3214, vals={0}, label="SPS-141-100" },

    -- SPS-141-100
    -- OFF=100%(default) / PARALLEL=0% / FULL=0%
    { dev=57, cmd=3220, vals={0}, label="SPS-141-100" },

    -- SPS-141-100 Auto/Manual
    -- AUTO=100%(default) / MANUAL=0%
    { dev=57, cmd=3219, vals={1}, label="SPS-141-100 Auto/Manual" },

    -- SPS-141-100 Continuous/Impulse
    -- CONTINUOUS=100%(default) / IMPULSE=0%
    { dev=57, cmd=3217, vals={1}, label="SPS-141-100 Continuous/Impulse" },

    -- SPS-141-100 Manual Activation Cover
    -- ON=0% / OFF=100%(default)
    { dev=57, cmd=3221, vals={0}, label="SPS-141-100 Manual Activation Cover" },

    -- SPS-141-100 Program I/II
    -- I=100%(default) / II=0%
    { dev=57, cmd=3216, vals={1}, label="SPS-141-100 Program I/II" },

    -- SPS-141-100 Transmit/Receive
    -- TRANSMIT=100%(default) / RECEIVE=0%
    { dev=57, cmd=3215, vals={1}, label="SPS-141-100 Transmit/Receive" },

    -- SRZO Codes
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 10=0% / 11=0% / 12=0%
    { dev=38, cmd=3088, vals={0}, label="SRZO Codes" },

    -- SRZO Emergency Transmit
    -- ON=0% / OFF=100%(default)
    { dev=38, cmd=3211, vals={0}, label="SRZO Emergency Transmit" },

    -- SRZO Emergency Transmit Cover
    -- ON=0% / OFF=100%(default)
    { dev=38, cmd=3210, vals={0}, label="SRZO Emergency Transmit Cover" },

    -- SRZO IFF Coder/Decoder
    -- ON=0% / OFF=100%(default)
    { dev=38, cmd=3087, vals={0}, label="SRZO IFF Coder/Decoder" },

    -- SRZO Self Destruct Cover
    -- ON=0% / OFF=100%(default)
    { dev=38, cmd=3229, vals={0}, label="SRZO Self Destruct Cover" },

    -- SRZO Type 81
    -- ON=0% / OFF=100%(default)
    { dev=38, cmd=3089, vals={0}, label="SRZO Type 81" },

    -- Suit Ventilation
    { dev=51, cmd=3269, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Suit Ventilation" },

    -- Surge Doors Auto/Manual
    -- AUTO=100%(default) / MANUAL=0%
    { dev=6, cmd=3022, vals={1}, label="Surge Doors Auto/Manual" },

    -- Tactical Drop
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3174, vals={0}, label="Tactical Drop" },

    -- Tactical Drop Cover
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3173, vals={0}, label="Tactical Drop Cover" },

    -- TDC Range/Pipper Span
    { dev=41, cmd=3213, vals={0, 0.25, 0.5, 0.75, 1.0}, label="TDC Range/Pipper Span" },

    -- Text Backlights
    { dev=46, cmd=3231, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Text Backlights" },

    -- Throttle Fixation
    { dev=51, cmd=3274, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Throttle Fixation" },

    -- Trimmer
    -- ON=0% / OFF=100%(default)
    { dev=9, cmd=3131, vals={0}, label="Trimmer" },

    -- UK-2M Mic Amplifier GS/KM
    -- GS=100%(default) / KM=0%
    { dev=51, cmd=3268, vals={1}, label="UK-2M Mic Amplifier GS/KM" },

    -- UK-2M Mic Amplifier M/L
    -- M=100%(default) / L=0%
    { dev=51, cmd=3267, vals={1}, label="UK-2M Mic Amplifier M/L" },

    -- UPK-23-250-2
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3223, vals={0}, label="UPK-23-250-2" },

    -- UPK-23-250-2 Gun Select
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3224, vals={0}, label="UPK-23-250-2 Gun Select" },

    -- Weapon Select Toggle
    -- ON=0% / OFF=100%(default)
    { dev=56, cmd=3200, vals={0}, label="Weapon Select Toggle" },

    -- Weapon Selector
    -- 1=100%(default) / 2=0% / 3=0% / 4=0% / 5=0% / 6=0% / 7=0% / 8=0% / 9=0% / 10=0% / 11=0%
    { dev=42, cmd=3188, vals={0}, label="Weapon Selector" },

    -- Weapons AA/AG Mode
    -- AA=100%(default) / AG=0%
    { dev=42, cmd=3183, vals={1}, label="Weapons AA/AG Mode" },

    -- Weapons Release Cover
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3192, vals={0}, label="Weapons Release Cover" },

    -- White Lights
    { dev=46, cmd=3234, vals={0, 0.25, 0.5, 0.75, 1.0}, label="White Lights" },

    -- Wing Drop Tank Jettison Cover
    -- ON=0% / OFF=100%(default)
    { dev=42, cmd=3177, vals={0}, label="Wing Drop Tank Jettison Cover" },

}, 3.0)
