-- Generated by CockpitRandomizer GUI
-- Aircraft: Spitfire LF Mk. IX
-- DO NOT EDIT MANUALLY — use the Settings dialog

CR.register("SpitfireLFMkIX", {

    -- Booster Coil Button Cover
    -- CLOSED=95%(default) / OPEN=5%
    { dev=2, cmd=3025, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Booster Coil Button Cover" },

    -- Canopy Open/Close Control
    -- CLOSED=85%(default) / OPEN=15%
    { dev=1, cmd=3051, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Canopy Open/Close Control" },

    -- Carburettor Air Control Lever
    -- COLD=70%(default) / WARM=30%
    { dev=2, cmd=3045, vals={0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Carburettor Air Control Lever" },

    -- De-Icer Lever
    -- OFF=85%(default) / ON=15%
    { dev=1, cmd=3021, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="De-Icer Lever" },

    -- Drop Tank Cock
    -- OFF=85%(default) / ON=15%
    { dev=2, cmd=3041, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Drop Tank Cock" },

    -- Flaps Lever
    -- UP=70%(default) / DOWN=30%
    { dev=1, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Flaps Lever" },

    -- Fuel Cock
    -- OFF=80%(default) / ON=20%
    { dev=2, cmd=3037, vals={0, 0, 0, 0, 1}, label="Fuel Cock" },

    -- Fuel Pump Toggle
    -- OFF=75%(default) / ON=25%
    { dev=2, cmd=3043, vals={0, 0, 0, 1}, label="Fuel Pump Toggle" },

    -- Gun Sight Master Switch
    -- OFF=85%(default) / ON=15%
    { dev=5, cmd=3018, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Gun Sight Master Switch" },

    -- Gun Sight Tint Screen
    -- CLEAR=80%(default) / TINTED=20%
    { dev=5, cmd=3016, vals={0, 0, 0, 0, 1}, label="Gun Sight Tint Screen" },

    -- ID Lamp Down Mode Selector
    -- OFF=70%(default) / SLOW=15% / FAST=15%
    { dev=4, cmd=3011, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1, 1, 1}, label="ID Lamp Down Mode Selector" },

    -- ID Lamp Up Mode Selector
    -- OFF=70%(default) / SLOW=15% / FAST=15%
    { dev=4, cmd=3007, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1, 1, 1}, label="ID Lamp Up Mode Selector" },

    -- I.F.F. Protective Cover
    -- CLOSED=95%(default) / OPEN=5%
    { dev=4, cmd=3021, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="I.F.F. Protective Cover" },

    -- I.F.F. Upper Toggle (Type B)
    -- OFF=85%(default) / ON=15%
    { dev=4, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="I.F.F. Upper Toggle (Type B)" },

    -- I.F.F. Lower Toggle (Type D)
    -- OFF=85%(default) / ON=15%
    { dev=4, cmd=3019, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="I.F.F. Lower Toggle (Type D)" },

    -- Magneto Left
    -- OFF=85%(default) / ON=15%
    { dev=2, cmd=3015, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Magneto Left" },

    -- Magneto Right
    -- OFF=85%(default) / ON=15%
    { dev=2, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Magneto Right" },

    -- Mixture Cut-Off Lever
    -- RICH=85%(default) / CUT OFF=15%
    { dev=2, cmd=3009, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Mixture Cut-Off Lever" },

    -- Nav Lights Toggle
    -- OFF=80%(default) / ON=20%
    { dev=1, cmd=3007, vals={0, 0, 0, 0, 1}, label="Nav Lights Toggle" },

    -- Oil Diluter Button Cover
    -- CLOSED=95%(default) / OPEN=5%
    { dev=2, cmd=3051, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Oil Diluter Button Cover" },

    -- Oxygen Valve
    -- CLOSE=90%(default) / OPEN=10%
    { dev=3, cmd=3003, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Oxygen Valve" },

    -- Pitot Heater Toggle
    -- OFF=80%(default) / ON=20%
    { dev=1, cmd=3035, vals={0, 0, 0, 0, 1}, label="Pitot Heater Toggle" },

    -- Radiator Control Toggle
    -- AUTOMATIC=70%(default) / MANUAL=30%
    { dev=1, cmd=3033, vals={0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Radiator Control Toggle" },

    -- Radiator Flap Test Button Cover
    -- CLOSED=95%(default) / OPEN=5%
    { dev=2, cmd=3059, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Radiator Flap Test Button Cover" },

    -- Radio Dimmer Toggle
    -- BRIGHT=80%(default) / DIM=20%
    { dev=15, cmd=3006, vals={0, 0, 0, 0, 1}, label="Radio Dimmer Toggle" },

    -- Radio Mode Selector
    -- R/T=80%(default) / R/T+T/R=20%
    { dev=15, cmd=3007, vals={0, 0, 0, 0, 1}, label="Radio Mode Selector" },

    -- Radio Transmit Lock Toggle
    -- UNLOCKED=85%(default) / LOCKED=15%
    { dev=15, cmd=3017, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Radio Transmit Lock Toggle" },

    -- Safety Lever
    -- SAFE=90%(default) / FIRE=10%
    { dev=5, cmd=3001, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Safety Lever" },

    -- Cockpit Side Door
    -- CLOSED=75%(default) / OPEN=25%
    { dev=1, cmd=3059, vals={0, 0, 0, 1}, label="Cockpit Side Door" },

    -- Starter Button Cover
    -- CLOSED=95%(default) / OPEN=5%
    { dev=2, cmd=3021, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Starter Button Cover" },

    -- Supercharger Mode Toggle
    -- MS=70%(default) / FS=30%
    { dev=2, cmd=3019, vals={0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Supercharger Mode Toggle" },

    -- Supercharger Mode Test Button Cover
    -- CLOSED=95%(default) / OPEN=5%
    { dev=2, cmd=3055, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="Supercharger Mode Test Button Cover" },

    -- Tank Pressurizer Lever
    -- OFF=70%(default) / ON=30%
    { dev=2, cmd=3033, vals={0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="Tank Pressurizer Lever" },

    -- U/C Indicator Blind
    -- OPEN=70%(default) / CLOSED=30%
    { dev=1, cmd=3011, vals={0, 0, 0, 0, 0, 0, 0, 1, 1, 1}, label="U/C Indicator Blind" },

    -- U/C Indicator Cut-Off Toggle
    -- NORMAL=90%(default) / CUT OFF=10%
    { dev=2, cmd=3099, vals={0, 0, 0, 0, 0, 0, 0, 0, 0, 1}, label="U/C Indicator Cut-Off Toggle" },

    -- Undercarriage Lever
    -- UP=60%(default) / DOWN=40%
    { dev=1, cmd=3025, vals={0, 0, 0, 1, 1}, label="Undercarriage Lever" },

    -- Altimeter Pressure Setting Knob
    { dev=1, cmd=3037, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Altimeter Pressure Setting Knob" },

    -- Compass Azimuth Ring
    { dev=1, cmd=3017, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Compass Azimuth Ring" },

    -- Direction Indicator Knob
    { dev=1, cmd=3041, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Direction Indicator Knob" },

    -- Gun Sight Dimmer
    { dev=5, cmd=3020, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gun Sight Dimmer" },

    -- Gun Sight Range Setter
    { dev=5, cmd=3007, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gun Sight Range Setter" },

    -- Gun Sight Span Setter
    { dev=5, cmd=3010, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Gun Sight Span Setter" },

    -- Cockpit Illumination LH
    { dev=4, cmd=3001, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Cockpit Illumination LH" },

    -- Cockpit Illumination RH
    { dev=4, cmd=3004, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Cockpit Illumination RH" },

    -- Propeller Pitch Lever
    { dev=2, cmd=3006, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Propeller Pitch Lever" },

    -- Throttle Lever
    { dev=2, cmd=3003, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Throttle Lever" },

    -- Elevator Trim Wheel
    { dev=1, cmd=3029, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Elevator Trim Wheel" },

    -- Rudder Trim Wheel
    { dev=1, cmd=3044, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Rudder Trim Wheel" },

    -- Wheel Brakes
    { dev=1, cmd=3002, vals={0, 0.25, 0.5, 0.75, 1.0}, label="Wheel Brakes" },

}, 3.0)
